### ISSUE TITLE
Documentation on how to use spark_write_jdbc to connect to MySql 

### ISSUE THREAD

**Issue by mike-vogel** [sparklyr/sparklyr#1067]
I get the following exception when calling spark_write_jdbc

Error: java.sql.SQLException: No suitable driver
at java.sql.DriverManager.getDriver(DriverManager.java:315)

I put the .jar file in a folder on the server where RStudio is running, config details below. We're able to access MySql via the RMySql package.

---
config$`spark.sparklyr.shell.driver-class-path` <- "/dev/shm/temp/mysql-connector-java-5.1.44-bin.jar"

spark_write_jdbc(members_df,
                   name    = "Mbrs",
                   options = list(url      = paste0("jdbc:mysql://",mysql_host,":",mysql_port,"/",dbname),
                                  user     = mysql_user,
                                  password = mysql_password), mode = "append")

**Comment by geoHeil** [comment]
duplicate of https://github.com/rstudio/sparklyr/issues/1816

**Comment by geoHeil** [comment]
I also have the same problem.

My database resides in docker to make the example reproducible:
```
version: "3.1"
services:
  postgis:
    image: mdillon/postgis:11
    ports:
      - "5432:5432"
    volumes:
      - "./postgis/data:/data"
      - "./postgis/postgis:/var/lib/postgresql"
    environment:
      - POSTGRES_PASSWORD=analytics
      - POSTGRES_USER=analytics
      - POSTGRES_DB=analytics
```
To start it run: `docker-compose up``
Then:

```r
library(sparklyr)
library(dplyr)
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"
# conf$`sparklyr.shell.jars` <- "org.postgresql:postgresql:42.2.6"
conf$`sparklyr.shell.driver-class-path` <- "/absolute/path/to/jar/postgresql-42.2.6.jar"


dummy_data_tbl <- copy_to(spark, iris)

spark_write_jdbc(dummy_data_tbl, "dumm_table", options = list(
  url = "jdbc:mysql://localhost:5432/analytics",
  user = "analytics",
  password = "analytics",
 driver = "org.postgresql.Driver"))

spark_read_jdbc(spark, "sample_jdbc",  options = list(
  url = "jdbc:mysql://localhost:5432/analytics",
  user = "analytics",
  password = "analytics",
  dbtable = "dumm_table",
  driver = "org.postgresql.Driver"))
```

- Spark Version: 2.4.3
-  SparklyR Version: 1.0.2

When trying to access the database it fails as the proper driver's class is not found. i.e. `NullPointerException` at:

```
java.lang.NullPointerException
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:85)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

When setting `conf$`sparklyr.shell.jars` <- "org.postgresql:postgresql:42.2.6"` it fails with:

```
Using Spark: 2.4.3
Fehler in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (50871): Gateway in localhost:8880 did not respond.
    Path: /Users/geoheil/spark/spark-2.4.3-bin-hadoop2.7/bin/spark-submit
    Parameters: --driver-memory, 8G, --jars, org.postgresql:postgresql:42.2.6, --class, sparklyr.Shell, '/Users/geoheil/development/curriculae/UII-R-BigData/course-content/packrat/lib/x86_64-apple-darwin18.2.0/3.5.3/sparklyr/java/sparklyr-2.3-2.11.jar', 8880, 50871
    Log: /var/folders/lz/vlbj1rj12dzbvbmj16jbp0k80000gn/T//Rtmp9F4Q5m/file17f9c64d238fa_spark.log


---- Output Log ----
19/07/21 09:46:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.io.IOException: No FileSystem for scheme: org.postgresql
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.spark.deploy.DependencyUtils$.org$apache$spark$deploy$DependencyUtils$$resolveGlobPath(DependencyUtils.scala:191)
	at org.apache.spark.deploy.DependencyUtils$$anonfun$resolveGlobPaths$2.apply(DependencyUtils.scala:147)
	at org.apache.spark.deploy.DependencyUtils$$anonfun$resolveGlobPaths$2.apply(DependencyUtils.scala:145)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.apache.spark.deploy.DependencyUtils$.resolveGlobPaths(DependencyUtils.scala:145)
	at org.apache.spark.deploy.SparkSubmit$$anonfun$prepareSubmitEnvironment$3.apply(SparkSubmit.scala:354)
	at org.apache.spark.deploy.SparkSubmit$$anonfun$prepareSubmitEnvironment$3.apply(SparkSubmit.scala:354)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:354)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
it looks strange to me that all the `,` delimiters are in the command sent to spark-submit.

**Comment by geoHeil** [comment]
@javierluraschi how can I add to `--packages`?

```r
conf$`spark.jars.packages` <- "org.postgresql:postgresql:42.2.6"
```

shows up in sparks environment UI, but does not download the jar.

**Comment by geoHeil** [comment]
So I finally found the required parameters:
```
conf$`sparklyr.shell.packages` <- "org.postgresql:postgresql:42.2.6"
```
will pass to `--packages` and load the jar via maven coordinates.

**Comment by elfatherbrown** [comment]
Hey this one bit me too, but its another use case. I was happily doing fine with 
``` yml
  sparklyr.shell.driver-class-path: "/home/alex/jdbc/postgresql-42.2.19.jar"
```
spark_connect'ing as master="local". When I changed to have my spark cluster's master elsewhere, as master="spark://elsewhere:port", everything broke with "java.sql.SQLException: No suitable driver".

I used you advice adding
```yaml
sparklyr.shell.packages: "org.postgresql:postgresql:42.2.19"
```
To my sparkconf.yml  file (an alternative way of setting the config parameters in spark_connect), and errything worked fine.

So THANK YOU! And hopefully the docs can be mended for this, because it would seem a common path forward.

**Comment by yitao-li** [comment]
The fact that one needs some SQL driver to make use of `spark_write_jdbc()` was kind of "documented" in section 8.7.3 of https://therinspark.com/data.html

It would have been much better if there were at least 1 concrete example of that included in the R documentation of `sparklyr` though. I'm working on it now.
