### ISSUE TITLE
spark_write_table() unable to append to existing Hive table

### ISSUE THREAD

**Issue by ckrietemeyer** [sparklyr/sparklyr#1258]
Current Spark version 2.2.0

Ran into an error when using spark_write_table() to append new rows to an existing Hive table using the code below:
`sdf_copy_to(sc, append_table, "spark_append", overwrite = TRUE) `
`sdf_append_table <- tbl(sc, "spark_append")`
`spark_write_table(sdf_append_table, "calendar", mode = "append")`

The following error was generated from the above code:
`Error: org.apache.spark.sql.AnalysisException: The format of the existing table non_reg_meters.calendar is `HiveFileFormat`. It doesn't match the specified format `ParquetFileFormat`.;
         at org.apache.spark.sql.execution.datasources.PreprocessTableCreation$$anonfun$apply$2.applyOrElse(rules.scala:115)
         at org.apache.spark.sql.execution.datasources.PreprocessTableCreation$$anonfun$apply$2.applyOrElse(rules.scala:75)
         at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
         at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
         at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
         at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:266)
         at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:256)
         at org.apache.spark.sql.execution.datasources.PreprocessTableCreation.apply(rules.scala:75)
         at org.apache.spark.sql.execution.datasources.PreprocessTableCreation.apply(rules.scala:71)
         at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
         at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
         at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
         at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
         at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
         at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
         at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
         at scala.collection.immutable.List.foreach(List.scala:381)
         at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
         at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:69)
         at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:67)
         at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:50)
         at org.apache.spark.sql.execution.QueryExecution.withCachedData$lzycompute(QueryExecution.scala:73)
         at org.apache.spark.sql.execution.QueryExecution.withCachedData(QueryExecution.scala:72)
         at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:78)
         at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:78)
         at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
         at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
         at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
         at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
         at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
         at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
         at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
         at org.apache.spark.sql.DataFrameWriter.createTable(DataFrameWriter.scala:420)
         at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:399)
         at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:354)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:497)
         at sparklyr.Invoke$.invoke(invoke.scala:102)
         at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
         at sparklyr.StreamHandler$.read(stream.scala:62)
         at sparklyr.BackendHandler.channelRead0(handler.scala:52)
         at sparklyr.BackendHandler.channelRead0(handler.scala:14)
         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
         at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
         at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
         at java.lang.Thread.run(Thread.java:745)`

After further research, it was determined that spark_write_table() could be used to:
1.) Create new tables, but could not read them back into R using the tbl() from dplyr
2.) Cannot append to an existing Hive table
3.) However, using spark_write_parquet() to create a new Parquet file formatted table worked successfully and could be read into R using spark_read_parquet()

The workaround to this issue was to use the DBI package's dbGetQuery() function, using the syntax below:
`DBI::dbGetQuery(sc, "INSERT INTO TABLE calendar SELECT * FROM spark_append")` To append to an existing table

`DBI::dbGetQuery(sc, "CREATE TABLE cody_trial_5 SELECT * FROM spark_append")` To create a new table that is able to be read back into R

**NOTE: None of the above issues occurred when using Spark version 1.6** 

Javier Luraschi stated that it could be the use of SQL API through the DBI package versus Dataframe API for spark_write_*(). 

Could support for SQL API be added to the spark_write_table() function?

Let me know if there are any questions or concerns.

Thank you

**Comment by javierluraschi** [comment]
@ckrietemeyer thanks for opening this one.

**Comment by warmdev** [comment]
Ran into an issue (as stated above) where HIVE tables written with spark_write_table() cannot be read back into R with tbl() (Spark 2.2). Hope this can be resolved soon.

**Comment by Tagar** [comment]
This is a known issue described in 
https://docs.cloudera.com/documentation/enterprise/release-notes/topics/cdh_rn_spark_ki.html#ki_sparksql_dataframe_saveastable

**Workaround**: Explicitly create a Hive table to store the data. For example:

```
df.registerTempTable(tempName)
hsc.sql(s"""
CREATE TABLE $tableName (
// field definitions   )
STORED AS $format """)
hsc.sql(s"INSERT INTO TABLE $tableName SELECT * FROM $tempName")
```

Cloudera Bug: **CDH-33639**
