### ISSUE TITLE
allow 'tbl_spark's to be constructed from streaming Spark DataFrames

### ISSUE THREAD

**Issue by kevinushey** [sparklyr/sparklyr#140]
E.g. with this code as a dummy example:

``` R
library(sparklyr)
library(dplyr)
library(ggplot2)
library(survival)
library(sparkapi)
library(nycflights13)

devtools::load_all(".")

flights_path <- path.expand("~/scratch/flights.csv")
data(flights, package = "nycflights13")
write.table(flights, file = flights_path, row.names = FALSE, col.names = TRUE, sep = ",")

sc <- spark_connect(master = "local", version = "2.0.0")
flights_tbl <- copy_to(sc, flights, overwrite = TRUE)

schema <- spark_dataframe(flights_tbl) %>% invoke("schema")

sdf <- hive_context(sc) %>%
  invoke("readStream") %>%
  invoke("format", "org.apache.spark.sql.execution.datasources.csv.CSVFileFormat") %>%
  invoke("option", "header", TRUE) %>%
  invoke("schema", schema) %>%
  invoke("load", flights_path)

sdf %>%
  invoke("isStreaming")

streaming_tbl <- sdf_register(sdf, "streaming")
```

We get the error:

``` R
> streaming_tbl <- sdf_register(sdf, "streaming")
 Error: org.apache.spark.sql.AnalysisException: Queries with streaming sources must be executed with writeStream.start();
    at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.org$apache$spark$sql$catalyst$analysis$UnsupportedOperationChecker$$throwError(UnsupportedOperationChecker.scala:173)
    at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$$anonfun$checkForBatch$1.apply(UnsupportedOperationChecker.scala:33)
    at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$$anonfun$checkForBatch$1.apply(UnsupportedOperationChecker.scala:31)
    at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:125)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:125)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:125 
```

**Comment by kevinushey** [comment]
This might also require RStudio IDE changes, since attempting to expand a streaming Spark DataFrame in the IDE produces the same error.

**Comment by ElianoMarques** [comment]
This would be very cool. specially if we can add an invalidate after option to. The other I setup a stream job via python that spin out a csv file which then was picked up by Shiny with an invalidate after to re-read the file after a while. If we could do this directly would be even better.

**Comment by jjallaire** [comment]
Yes absolutely! Once we get the mechanics of this working we'll create a
Shiny wrapper that will turn the streaming data frame directly into a Shiny
reactive.

**Comment by ElianoMarques** [comment]
Awesome

**Comment by yitao-li** [comment]
I'm gonna close this as there are already a number of functions in `sparklyr` such as `stream_read_csv` and `stream_read_json` that can load streaming data into a Spark dataframes.
