### ISSUE TITLE
collect fails outside of spark

### ISSUE THREAD

**Issue by mattpollock** [sparklyr/sparklyr#1463]
It seems that `collect` fails inside of the sparklyr java utils

```r
library(bit64)
library(stringi)
nrows <- 4000000
sample_df <- data.frame(
  sting1=stri_rand_strings(n=nrows, length=32, pattern="[A-Za-z0-9]"),
  sting2=stri_rand_strings(n=nrows, length=5, pattern="[A-Za-z0-9]"),
  sting3=stri_rand_strings(n=nrows, length=6, pattern="[A-Za-z0-9]"),
  sting4=stri_rand_strings(n=nrows, length=14, pattern="[0-9]"),
  number1=stri_rand_strings(n=nrows, length=13, pattern="[0-9]") %>% as.integer64(),
  number2=stri_rand_strings(n=nrows, length=20, pattern="[0-9]") %>% as.integer64(),
  number3=stri_rand_strings(n=nrows, length=20, pattern="[0-9]") %>% as.integer64(),
  number4=stri_rand_strings(n=nrows, length=20, pattern="[0-9]") %>% as.integer64(),
  number5=stri_rand_strings(n=nrows, length=20, pattern="[0-9]") %>% as.integer64()
)
data.table::fwrite(sample_df, "/my/local/path/spark_test.csv")

spk_df <- spark_read_csv(sc, name="test", path="file:///my/local/path/spark_test.csv")

sample_df2 <- spk_df %>% sdf_repartition(30) %>% collect()
```

For me this results in the follow exception
```
Error: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:200)
	at sparklyr.Utils$.collectImplString(utils.scala:138)
	at sparklyr.Utils$.collectImpl(utils.scala:189)
	at sparklyr.Utils$$anonfun$collect$1.apply(utils.scala:213)
	at sparklyr.Utils$$anonfun$collect$1.apply(utils.scala:213)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sparklyr.Utils$.collect(utils.scala:213)
	at sparklyr.Utils.collect(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
```

The interesting thing is the the spark UI shows that the collect job completes successfully. The java stack doesn't include any spark (proper) references. 

I've tried simple fixes like driving up the spark driver memory and max result size (before I noticed where the exception is thrown) as well as setting `java-parameters` locally to give sparklyr plenty of memory to operate on.

**Comment by mattpollock** [comment]
My spark configs are as follows:
```r
> sc
$master
[1] "yarn-client"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$spark.executor.memory
[1] "2G"

$config$spark.driver.memory
[1] "4G"

$config$spark.driver.maxResultSize
[1] "4G"

$config$spark.executor.cores
[1] "5"

$config$spark.dynamicAllocation.enabled
[1] "true"

$config$spark.shuffle.service.enabled
[1] "true"

$config$spark.dynamicAllocation.minExecutors
[1] "0"

$config$spark.dynamicAllocation.maxExecutors
[1] "60"

$config$spark.dynamicAllocation.executorIdleTimeout
[1] "300"

$config$spark.dynamicAllocation.cachedExecutorIdleTimeout
[1] "600"

$config$spark.yarn.queue
[1] "fast"


$spark_home
[1] "/<path to>/spark-2.2.1-SNAPSHOT-bin-caasd"

$backend
A connection with                               
description "->localhost:44683"
class       "sockconn"         
mode        "wb"               
text        "binary"           
opened      "opened"           
can read    "yes"              
can write   "yes"              

$monitor
A connection with                               
description "->localhost:36092"
class       "sockconn"         
mode        "rb"               
text        "binary"           
opened      "opened"           
can read    "yes"              
can write   "yes"              

$output_file
[1] "/tmp/RtmpNHOfE5/file69ac1f57aa12_spark.log"

$spark_context
<jobj[17]>
  org.apache.spark.SparkContext
  org.apache.spark.SparkContext@624ddcb4

$java_context
<jobj[18]>
  org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@7403b114

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection" 
```

**Comment by yitao-li** [comment]
I think the changes in https://github.com/sparklyr/sparklyr/issues/1834 will help (NOTE: not on CRAN yet)
Reason I think so: `spark_write_rds()` will offload the work of creating RDS files for each Spark partition to Spark workers and Spark workers simply produce RDS files and store them in HDFS instead of sending data back to Spark driver node.
You'd have to fetch the RDS files from HDFS yourself though (by using some external CLI tool such as `hadoop fs -get ...`), and then call `collect_from_rds()` to turn the raw RDS data into an actual R dataframe (`collect_from_rds()` does some important post-processing after it calls `readRDS()` on a local RDS file).
