### ISSUE TITLE
spark_write_csv fails with java.lang.NoSuchMethodError for Spark 1.6.3 and Scala 2.10

### ISSUE THREAD

**Issue by ffocke** [sparklyr/sparklyr#1466]
When trying to write a Spark dataframe to csv with spark_write_csv, a java.lang.NoSuchMethodError occurs in our setup (Spark 1.6.3 and Scala 2.10).

Here is an example: 

```
library(sparklyr)
library(dplyr)

# Set up environment 
Sys.setenv(HADOOP_CONF_DIR = '/etc/hadoop/conf')
Sys.setenv(YARN_CONF_DIR = '/etc/hadoop/conf')
config <- spark_config()
config$`spark.driver.cores`      <- 2
config$`spark.driver.memory`     <- "512M"
config$`spark.executor.cores`    <- 4
config$`spark.executor.memory`   <- "4G"
config$`sparklyr.gateway.port`   <- "8884"
config$`spark.deploy.mode`       <- "cluster"
config$`spark.submit.deployMode` <- "cluster"

sc <- spark_connect(master     = "yarn-client",
                   config     = config,
                   version    = "1.6.3",
                   spark_home = "/<PATH>/current/spark-client")



a <- data.frame('a'=c(1,2,3), 'b'=c(2,3,4), 'c'=c(NA, NA, NA), 'd'=c(1,NA,2), 'e'=c('a', NA, 'b'))
sdf <- sdf_copy_to(sc, a, "strings_na_test", overwrite=TRUE) 
sdf
spark_write_csv(sdf, path="hdfs:///user/user/test.csv", mode="overwrite")
spark_disconnect(sc)
```

The output is: 
```
> sdf
# Source:   table<strings_na_test> [?? x 5]
# Database: spark_connection
      a     b     c     d     e
  <dbl> <dbl> <lgl> <dbl> <chr>
1     1     2 FALSE     1     a
2     2     3 FALSE   NaN    NA
3     3     4 FALSE     2     b
> spark_write_csv(sdf, path="hdfs:///user/user/test.csv", mode="overwrite")
Error: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at com.databricks.spark.csv.util.CompressionCodecs$.<init>(CompressionCodecs.scala:29)
	at com.databricks.spark.csv.util.CompressionCodecs$.<clinit>(CompressionCodecs.scala)
	at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:198)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

In our case, this could be fixed my overwriting the default JARs and pointing to a version of Spark-csv compiled under Scala 2.10 (spark-csv_2.10-1.5.0.jar). We used the following config settings for this: 

```
config$`sparklyr.csv.embedded` <- FALSE
config$`sparklyr.jars.default` <- c("/<PATH>/current/spark-client/lib/spark-csv_2.10-1.5.0.jar", '/<PATH>/R/3.2.5/lib/R/library/sparklyr/java/commons-csv-1.5.jar','/<PATH>/R/3.2.5/lib/R/library/sparklyr/java/univocity-parsers-1.5.1.jar')
```

As far as I could see, no documentation on this exists yet and the embedded JARs are hard-coded in https://github.com/rstudio/sparklyr/blob/master/R/shell_connection.R, so wanted to raise this in case there is an option to make the source of the error as well as the ideal fix more apparent to users. 

Output from sessionInfo(): 
```
R version 3.2.5 (2016-04-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.4

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4    sparklyr_0.7.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13     dbplyr_1.1.0     plyr_1.8.3       bindr_0.1       
 [5] base64enc_0.1-3  tools_3.2.5      digest_0.6.12    jsonlite_1.5    
 [9] tibble_1.3.4     nlme_3.1-125     lattice_0.20-33  pkgconfig_2.0.1 
[13] rlang_0.2.0      psych_1.7.8      shiny_1.0.5      DBI_0.7         
[17] rstudioapi_0.7   yaml_2.1.13      parallel_3.2.5   bindrcpp_0.2    
[21] withr_2.1.0      httr_1.3.1       stringr_1.2.0    rprojroot_1.2   
[25] grid_3.2.5       glue_1.2.0       R6_2.2.2         foreign_0.8-66  
[29] reshape2_1.4.1   tidyr_0.4.1      magrittr_1.5     backports_1.0.2 
[33] htmltools_0.3.5  assertthat_0.2.0 mnormt_1.5-4     mime_0.5        
[37] xtable_1.8-2     httpuv_1.3.5     config_0.2       stringi_1.0-1   
[41] openssl_0.9.7    lazyeval_0.2.1   broom_0.4.2     
```

**Comment by yitao-li** [comment]
This is fixed by now
