### ISSUE TITLE
Error: Unable to use sparklyr to query large data

### ISSUE THREAD

**Issue by Karthick333031** [sparklyr/sparklyr#1815]
I have my datasets in Parquet format (gzipped) in S3 and is indexed in AWS glue. I have launched EMR (4 r4.4xlarge nodes and 1 r4.4xlarge master) and have made sure cluster has access to data in S3 via the Glue Catalog. I have a massive transactional dataset (~1 TB) partitioned on date. 

I have a standard SQL query that uses multiple joins to produce the output. I have been using the SQL currently against warehouse and am moving it to Spark SQL. When I run my query, I am able to process the same for 2 weeks of data with the configuration. When I increase the volume of data to be filtered and processed to 4 weeks, I get the below error

---- Configuration

```
Sys.setenv(SPARK_HOME="/usr/lib/spark")
config <- spark_config()
config$spark.driver.memory <- "80G"
config$spark.executor.memory <- "15G"
config$spark.dynamicAllocation.enabled <- "true"
#config$spark.yarn.am.memory <- "8G" 
#config$`sparklyr.shell.driver-memory` <- "80G"
#config$`sparklyr.shell.executor-memory` <- "4G"
config$`spark.yarn.executor.memoryOverhead` <- "2G"
config$spark.local.dir <- "s3://spark-temp-dir/"

sc <- spark_connect(master = "yarn-client", config = config)
```

---- Error
```
> df_q1 <- dbGetQuery(sc, mysqlquery, stringsAsFactors=F)
Error in value[[3L]](cond) : 
  Failed to fetch data: java.lang.IllegalArgumentException: Object not found 21
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:115)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.inv
```

---- Spark context logs

```
18/12/18 22:11:47 INFO TaskSetManager: Finished task 176.0 in stage 10.0 (TID 6956) in 3359 ms on ip-10-168-172-62.ec2.internal (executor 33) (166/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed taskresult_6888 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 1540.0 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed taskresult_6910 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 1853.4 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 198.0 in stage 10.0 (TID 6978) in 2102 ms on ip-10-168-172-62.ec2.internal (executor 31) (167/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 146.0 in stage 10.0 (TID 6926) in 4145 ms on ip-10-168-172-62.ec2.internal (executor 30) (168/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 180.0 in stage 10.0 (TID 6960) in 3025 ms on ip-10-168-172-62.ec2.internal (executor 33) (169/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 185.0 in stage 10.0 (TID 6965) in 2775 ms on ip-10-168-172-62.ec2.internal (executor 32) (170/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 193.0 in stage 10.0 (TID 6973) in 2347 ms on ip-10-168-172-62.ec2.internal (executor 31) (171/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 155.0 in stage 10.0 (TID 6935) in 3940 ms on ip-10-168-172-62.ec2.internal (executor 34) (172/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 171.0 in stage 10.0 (TID 6951) in 3610 ms on ip-10-168-172-62.ec2.internal (executor 33) (173/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 178.0 in stage 10.0 (TID 6958) in 3313 ms on ip-10-168-172-62.ec2.internal (executor 34) (174/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 160.0 in stage 10.0 (TID 6940) in 3736 ms on ip-10-168-172-62.ec2.internal (executor 32) (175/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 179.0 in stage 10.0 (TID 6959) in 3232 ms on ip-10-168-172-62.ec2.internal (executor 34) (176/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_16_piece0 on 10.168.172.18:41167 in memory (size: 40.6 KB, free: 61.9 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_16_piece0 on ip-10-168-172-62.ec2.internal:45485 in memory (size: 40.6 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_16_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 40.6 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_16_piece0 on ip-10-168-172-62.ec2.internal:35195 in memory (size: 40.6 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_16_piece0 on ip-10-168-172-62.ec2.internal:35433 in memory (size: 40.6 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 158.0 in stage 10.0 (TID 6938) in 3842 ms on ip-10-168-172-62.ec2.internal (executor 32) (177/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_16_piece0 on ip-10-168-172-62.ec2.internal:38663 in memory (size: 40.6 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_16_piece0 on ip-10-168-172-62.ec2.internal:46343 in memory (size: 40.6 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 170.0 in stage 10.0 (TID 6950) in 3737 ms on ip-10-168-172-62.ec2.internal (executor 33) (178/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_15_piece0 on 10.168.172.18:41167 in memory (size: 37.5 KB, free: 61.9 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_15_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 37.5 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_14_piece0 on 10.168.172.18:41167 in memory (size: 35.2 KB, free: 61.9 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 172.0 in stage 10.0 (TID 6952) in 3782 ms on ip-10-168-172-62.ec2.internal (executor 33) (179/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed broadcast_14_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 35.2 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 199.0 in stage 10.0 (TID 6979) in 2438 ms on ip-10-168-172-62.ec2.internal (executor 31) (180/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 181.0 in stage 10.0 (TID 6961) in 3306 ms on ip-10-168-172-62.ec2.internal (executor 33) (181/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 165.0 in stage 10.0 (TID 6945) in 3916 ms on ip-10-168-172-62.ec2.internal (executor 31) (182/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Added taskresult_6901 in memory on ip-10-168-172-62.ec2.internal:35433 (size: 1646.0 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 174.0 in stage 10.0 (TID 6954) in 3856 ms on ip-10-168-172-62.ec2.internal (executor 33) (183/200)
18/12/18 22:11:47 INFO TransportClientFactory: Successfully created connection to ip-10-168-172-62.ec2.internal/10.168.172.62:35433 after 0 ms (0 ms spent in bootstraps)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 116.0 in stage 10.0 (TID 6896) in 5648 ms on ip-10-168-172-62.ec2.internal (executor 32) (184/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Added taskresult_6858 in memory on ip-10-168-172-62.ec2.internal:35195 (size: 1709.8 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 121.0 in stage 10.0 (TID 6901) in 5665 ms on ip-10-168-172-62.ec2.internal (executor 30) (185/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Added taskresult_6870 in memory on ip-10-168-172-62.ec2.internal:35195 (size: 1823.0 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 169.0 in stage 10.0 (TID 6949) in 3971 ms on ip-10-168-172-62.ec2.internal (executor 34) (186/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed taskresult_6901 on ip-10-168-172-62.ec2.internal:35433 in memory (size: 1646.0 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TransportClientFactory: Successfully created connection to ip-10-168-172-62.ec2.internal/10.168.172.62:35195 after 0 ms (0 ms spent in bootstraps)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 148.0 in stage 10.0 (TID 6928) in 4537 ms on ip-10-168-172-62.ec2.internal (executor 34) (187/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 90.0 in stage 10.0 (TID 6870) in 11781 ms on ip-10-168-172-62.ec2.internal (executor 33) (188/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 78.0 in stage 10.0 (TID 6858) in 11784 ms on ip-10-168-172-62.ec2.internal (executor 33) (189/200)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 157.0 in stage 10.0 (TID 6937) in 4237 ms on ip-10-168-172-62.ec2.internal (executor 32) (190/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed taskresult_6870 on ip-10-168-172-62.ec2.internal:35195 in memory (size: 1823.0 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed taskresult_6858 on ip-10-168-172-62.ec2.internal:35195 in memory (size: 1709.8 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO BlockManagerInfo: Added taskresult_6854 in memory on ip-10-168-172-62.ec2.internal:46343 (size: 2.7 MB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 187.0 in stage 10.0 (TID 6967) in 3410 ms on ip-10-168-172-62.ec2.internal (executor 33) (191/200)
18/12/18 22:11:47 INFO TransportClientFactory: Successfully created connection to ip-10-168-172-62.ec2.internal/10.168.172.62:46343 after 0 ms (0 ms spent in bootstraps)
18/12/18 22:11:47 INFO BlockManagerInfo: Added taskresult_6971 in memory on ip-10-168-172-62.ec2.internal:35433 (size: 1859.4 KB, free: 8.8 GB)
18/12/18 22:11:47 INFO TaskSetManager: Finished task 191.0 in stage 10.0 (TID 6971) in 3105 ms on ip-10-168-172-62.ec2.internal (executor 30) (192/200)
18/12/18 22:11:47 INFO BlockManagerInfo: Removed taskresult_6971 on ip-10-168-172-62.ec2.internal:35433 in memory (size: 1859.4 KB, free: 8.8 GB)
18/12/18 22:11:48 INFO BlockManagerInfo: Added taskresult_6934 in memory on ip-10-168-172-62.ec2.internal:45485 (size: 1590.8 KB, free: 8.8 GB)
18/12/18 22:11:48 INFO TaskSetManager: Finished task 154.0 in stage 10.0 (TID 6934) in 4669 ms on ip-10-168-172-62.ec2.internal (executor 34) (193/200)
18/12/18 22:11:48 INFO BlockManagerInfo: Removed taskresult_6934 on ip-10-168-172-62.ec2.internal:45485 in memory (size: 1590.8 KB, free: 8.8 GB)
18/12/18 22:11:48 INFO BlockManagerInfo: Added taskresult_6968 in memory on ip-10-168-172-62.ec2.internal:46305 (size: 2.7 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO TaskSetManager: Finished task 74.0 in stage 10.0 (TID 6854) in 12069 ms on ip-10-168-172-62.ec2.internal (executor 32) (194/200)
18/12/18 22:11:48 INFO BlockManagerInfo: Removed taskresult_6854 on ip-10-168-172-62.ec2.internal:46343 in memory (size: 2.7 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO TaskSetManager: Finished task 188.0 in stage 10.0 (TID 6968) in 3439 ms on ip-10-168-172-62.ec2.internal (executor 8) (195/200)
18/12/18 22:11:48 INFO BlockManagerInfo: Removed taskresult_6968 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 2.7 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO BlockManagerInfo: Added taskresult_6815 in memory on ip-10-168-172-62.ec2.internal:38663 (size: 1854.9 KB, free: 8.8 GB)
18/12/18 22:11:48 INFO TransportClientFactory: Successfully created connection to ip-10-168-172-62.ec2.internal/10.168.172.62:38663 after 0 ms (0 ms spent in bootstraps)
18/12/18 22:11:48 INFO TaskSetManager: Finished task 35.0 in stage 10.0 (TID 6815) in 12121 ms on ip-10-168-172-62.ec2.internal (executor 31) (196/200)
18/12/18 22:11:48 INFO BlockManagerInfo: Removed taskresult_6815 on ip-10-168-172-62.ec2.internal:38663 in memory (size: 1854.9 KB, free: 8.8 GB)
18/12/18 22:11:48 INFO BlockManagerInfo: Added taskresult_6970 in memory on ip-10-168-172-62.ec2.internal:46343 (size: 1810.9 KB, free: 8.8 GB)
18/12/18 22:11:48 INFO TaskSetManager: Finished task 190.0 in stage 10.0 (TID 6970) in 3340 ms on ip-10-168-172-62.ec2.internal (executor 32) (197/200)
18/12/18 22:11:48 INFO BlockManagerInfo: Removed taskresult_6970 on ip-10-168-172-62.ec2.internal:46343 in memory (size: 1810.9 KB, free: 8.8 GB)
18/12/18 22:11:48 INFO BlockManagerInfo: Added taskresult_6953 in memory on ip-10-168-172-62.ec2.internal:46343 (size: 2.5 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO TaskSetManager: Finished task 173.0 in stage 10.0 (TID 6953) in 4544 ms on ip-10-168-172-62.ec2.internal (executor 32) (198/200)
18/12/18 22:11:48 INFO BlockManagerInfo: Removed taskresult_6953 on ip-10-168-172-62.ec2.internal:46343 in memory (size: 2.5 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO BlockManagerInfo: Added taskresult_6941 in memory on ip-10-168-172-62.ec2.internal:35195 (size: 2.7 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO TaskSetManager: Finished task 161.0 in stage 10.0 (TID 6941) in 4690 ms on ip-10-168-172-62.ec2.internal (executor 33) (199/200)
18/12/18 22:11:48 INFO BlockManagerInfo: Removed taskresult_6941 on ip-10-168-172-62.ec2.internal:35195 in memory (size: 2.7 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO BlockManagerInfo: Added taskresult_6946 in memory on ip-10-168-172-62.ec2.internal:38663 (size: 2.4 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO TaskSetManager: Finished task 166.0 in stage 10.0 (TID 6946) in 4808 ms on ip-10-168-172-62.ec2.internal (executor 31) (200/200)
18/12/18 22:11:48 INFO YarnScheduler: Removed TaskSet 10.0, whose tasks have all completed, from pool 
18/12/18 22:11:48 INFO DAGScheduler: ResultStage 10 (collect at utils.scala:200) finished in 12.544 s
18/12/18 22:11:48 INFO DAGScheduler: Job 2 finished: collect at utils.scala:200, took 839.026094 s
18/12/18 22:11:48 INFO BlockManagerInfo: Removed taskresult_6946 on ip-10-168-172-62.ec2.internal:38663 in memory (size: 2.4 MB, free: 8.8 GB)
18/12/18 22:11:48 INFO CodeGenerator: Code generated in 15.497482 ms
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_17_piece0 on 10.168.172.18:41167 in memory (size: 65.7 KB, free: 61.9 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_17_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 65.7 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_17_piece0 on ip-10-168-172-62.ec2.internal:35195 in memory (size: 65.7 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_17_piece0 on ip-10-168-172-62.ec2.internal:35433 in memory (size: 65.7 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_17_piece0 on ip-10-168-172-62.ec2.internal:45485 in memory (size: 65.7 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_17_piece0 on ip-10-168-172-62.ec2.internal:38663 in memory (size: 65.7 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_17_piece0 on ip-10-168-172-62.ec2.internal:46343 in memory (size: 65.7 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_9_piece0 on 10.168.172.18:41167 in memory (size: 6.7 KB, free: 61.9 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_9_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 6.7 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_10_piece0 on 10.168.172.18:41167 in memory (size: 6.7 KB, free: 61.9 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_12_piece0 on 10.168.172.18:41167 in memory (size: 8.2 KB, free: 61.9 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_12_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 8.2 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 10.168.172.18:41167 in memory (size: 30.6 KB, free: 61.9 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_0_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 30.6 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_2_piece0 on 10.168.172.18:41167 in memory (size: 5.4 KB, free: 61.9 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_2_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 5.4 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_11_piece0 on 10.168.172.18:41167 in memory (size: 7.6 KB, free: 61.9 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_11_piece0 on ip-10-168-172-62.ec2.internal:46305 in memory (size: 7.6 KB, free: 8.8 GB)
18/12/18 22:11:50 INFO BlockManagerInfo: Removed broadcast_13_piece0 on 10.168.172.18:41167 in memory (size: 8.2 KB, free: 61.9 GB)
**18/12/18 22:11:54 ERROR sparklyr: Gateway (28169) failed calling columns on 21**
```

I referred to few issues and solutions in sparklyr github repo but not sure if they are relevant
- https://github.com/rstudio/sparklyr/issues/1322
- https://github.com/rstudio/sparklyr/pull/1611
- https://github.com/rstudio/sparklyr/issues/1289

I am blocked on this and I am unable to proceed any further with development due to this. Kindly advise if I am overlooking any obvious configuration to resolve this issue. If not, it would be useful to get this issue resolved.

**Comment by kevinykuo** [comment]
Is `dbGetQuery(sc, mysqlquery, stringsAsFactors=F)` supposed to return a (relatively) small data frame?

If the query works for weeks {1, 2} but fails for weeks {1, 2, 3, 4} have you tried running it on {3, 4}?

**Comment by Karthick333031** [comment]
The query wouldn't return a small data frame. Should I then not use dbGetQuery? At scale, I actually want to run it for ~12 to 15 weeks data  

I will try out {3 & 4} and update back if that works

**Comment by kevinykuo** [comment]
`dbGetQuery()` forces collection, so if your resulting table doesn't fit in memory locally I wouldn't use it. Look into `sdf_sql()` to return a `tbl_spark` instead.

**Comment by Karthick333031** [comment]
Thanks ! sdf_sql resolves the problem of querying at scale. I have a few follow up questions that require little more direction. I am unable to find info on how to query a tbl_spark and cache the same. After running sdf_sql, I tried running sdf_register? Does my question in some way related to https://github.com/rstudio/sparklyr/issues/742 and do I have to use dbSendQuery to be able to later use the dataframe for downstream consumption ?

**Comment by kevinykuo** [comment]
You'd query it as with any other Spark DataFrame, since that's what it is. If you want to use some results in R locally you'd have to call `collect()`.

**Comment by Karthick333031** [comment]
Thanks for your inputs. let me try out the process end to end and post back

**Comment by benmwhite** [comment]
You can also use `compute()` if you want to cache your table or query results in your cluster's memory but not bring it in locally. I usually use the `name` argument in there as well, since this makes it easier to track via the Spark web UI (in the "Storage" tab).

**Comment by Karthick333031** [comment]
sure. Thanks for the input. sdf_sql, followed by sdf_register & tbl_cache helped as well.
