### ISSUE TITLE
Problem using another CRAN package in UDF and spark_apply

### ISSUE THREAD

**Issue by curtisburkhalter** [sparklyr/sparklyr#1818]
Hello I'm currently attempting to apply a user defined function with spark_apply to calculate SHAP values from a XGBoost model I created using H2O. It seems that spark_apply doesn't like the embedded function that I'm calling from the R package 'iml' and I'm getting the following error: 

Error : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 175.0 failed 4 times, most recent failure: Lost task 0.3 in stage 175.0 (TID 2417, 10.139.64.6, executor 0): java.lang.Exception: sparklyr

```
Error : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 175.0 failed 4 times, most recent failure: Lost task 0.3 in stage 175.0 (TID 2417, 10.139.64.6, executor 0): java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:106)
	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:113)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1747)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1735)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1734)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1734)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:962)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:962)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:962)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1970)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1918)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1906)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:759)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2141)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2238)
	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:212)
	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:247)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:64)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:70)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:497)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:469)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:319)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectResult(Dataset.scala:2775)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3350)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2742)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2742)
	at org.apache.spark.sql.Dataset$$anonfun$54.apply(Dataset.scala:3334)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:89)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:175)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:84)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:126)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3333)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2742)
	at sparklyr.Utils$.collect(utils.scala:200)
	at sparklyr.Utils.collect(utils.scala)
	at sun.reflect.GeneratedMethodAccessor387.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:106)
	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:113)

In addition: Warning messages:
1: In do.call(.f, args, envir = .env) :
  'what' must be a function or character string
2: In do.call(.f, args, envir = .env) :
  'what' must be a function or character string
```

**Here is the minimal amount of code needed to generate the error:**

```
library(sparklyr)

#configure spark cluster, running in Azure Databricks
#there are 8 nodes in the cluster and each node has 8 vCPUs
config <- spark_config()
config$spark.executor.cores <- 64
config$spark.executor.memory <-"3G"

sc <- spark_connect(method = "databricks", config = config)

library(h2o)
library(rsparkling)
library(tidyverse)
library(iml)

features_iml <- as.data.frame(df_testR) %>% dplyr::select(-returned)

response_iml <- as.numeric(as.vector(df_testR$returned))

pred <- function(model, newdata)  {
  results <- as.data.frame(h2o.predict(model, as.h2o(newdata)))
  return(results[[3L]])
}

predictor = iml::Predictor$new(model = GBM3, data = features_iml, y = response_iml,  predict.fun = pred,  class = "classification")

class(GBM3)
[1] "H2OBinomialModel"
attr(,"package")
[1] "h2o"

subsets_spark <- sdf_copy_to(sc = sc, subsets_df, "subset_tbl3", overwrite = T)

spark_apply(subsets_spark, 
            function(x) apply(x, 1, function(w) iml::Shapley$new(predictor, x.interest = w)), 
            context = sc)
```

**and here is a minimal chunk of the datasets being used (df_testR, and subsets_df).**

```
df_testR <- structure(list(dlr_id_cur = c("01117", "01120", "01127"), date_eff = c(1383609600, 
1331942400, 1360540800), new_vec_ind = c("N", "N", "N"), cntrct_term = c(26.1435645703053, 
33, 36), amt_financed = c(45219.5, 42245.13, 12088.5), reg_payment = c(615.49, 
556.53, 126.38), acct_stat_cd = c("3", "3", "3"), base_rental = c(0, 
548.18, 121.93), down_pymt = c(0, 1466.87, 1430), car_count = c(1L, 
1L, 1L), dur_lease = c(1096L, 1001L, 1094L), returned = c("0", 
"1", "0"), state = c("LA", "AL", "AL"), zip = c(70119, 35811, 
35243), zip_two_digits = c("70", "35", "35"), mod_year_date = c(2014, 
2012, 2013), vehic_mod_fam_code = c("C", "C", "T"), mod_class_code = c("GLK", 
"C", "SMT"), count_dl_DL_CDE_CSPS_A_NP = c(391, 666, 1521), DL_CDE_CSPS_A_NP_avg_dl = c(97.5191815856777, 
97.7927927927928, 98.2314266929652), count_sv_DL_CDE_CSPS_A_NP = c(3371, 
4169, 8741), DL_CDE_CSPS_A_NP_avg_sv = c(92.2990210619994, 92.4682177980331, 
93.6952293787896), count_dl_NUM_CSPS_INIT_SCR = c(368, 554, 1336
), NUM_CSPS_INIT_SCR_avg_dl = c(972.666666032609, 972.657039711191, 
976.567697679641), count_sv_NUM_CSPS_INIT_SCR = c(2695, 3189, 
6807), NUM_CSPS_INIT_SCR_avg_sv = c(936.154359925789, 926.282220131703, 
940.03405319524), count_FFV = c(4888, 5905, 13466), average_FFV = c(0.901595744680851, 
0.948348856900931, 0.932422397148374), csps_NUM_SV = c(0L, 1L, 
0L), avg_SV_rating = c(952.528718288985, 952.528718288985, 952.528718288985
), csps_FFV_ratio = c(0.948619406611736, 0, 0.948619406611736
), avg_DL_rating = c(980.410441044104, 980.410441044104, 980.410441044104
), has_DL_rating = c(0L, 0L, 0L), has_bad_DL_rating = c(0L, 0L, 
0L), serv_has_MNT = c(0L, 0L, 0L), serv_has_SCP = c(0L, 0L, 0L
), serv_has_ELW = c(0L, 0L, 0L), serv_has_LCP = c(0L, 0L, 0L), 
    ro_count = c(0L, 5L, 0L), ro_tot_cust_pay = c(0, 133.45, 
    0), ro_tot_pay = c(0, 800.44, 0), date_eff_weekday = c("Tuesday", 
    "Saturday", "Monday"), date_eff_month_int = c(11L, 3L, 2L
    ), date_eff_day = c(5L, 17L, 11L)), .Names = c("dlr_id_cur", 
"date_eff", "new_vec_ind", "cntrct_term", "amt_financed", "reg_payment", 
"acct_stat_cd", "base_rental", "down_pymt", "car_count", "dur_lease", 
"returned", "state", "zip", "zip_two_digits", "mod_year_date", 
"vehic_mod_fam_code", "mod_class_code", "count_dl_DL_CDE_CSPS_A_NP", 
"DL_CDE_CSPS_A_NP_avg_dl", "count_sv_DL_CDE_CSPS_A_NP", "DL_CDE_CSPS_A_NP_avg_sv", 
"count_dl_NUM_CSPS_INIT_SCR", "NUM_CSPS_INIT_SCR_avg_dl", "count_sv_NUM_CSPS_INIT_SCR", 
"NUM_CSPS_INIT_SCR_avg_sv", "count_FFV", "average_FFV", "csps_NUM_SV", 
"avg_SV_rating", "csps_FFV_ratio", "avg_DL_rating", "has_DL_rating", 
"has_bad_DL_rating", "serv_has_MNT", "serv_has_SCP", "serv_has_ELW", 
"serv_has_LCP", "ro_count", "ro_tot_cust_pay", "ro_tot_pay", 
"date_eff_weekday", "date_eff_month_int", "date_eff_day"), row.names = c(NA, 
-3L), class = c("tbl_df", "tbl", "data.frame"))

```
and 

```
subsets_df <- structure(list(dlr_id_cur = c("05705", "59106", "74303"), date_eff = c(1428019200, 
1400025600, 1371859200), new_vec_ind = c("N", "N", "N"), cntrct_term = c(36, 
36, 26.1435645703053), amt_financed = c(76670, 22350.96, 14400
), reg_payment = c(1244.09, 295.18, 189.53), acct_stat_cd = c("3", 
"1", "3"), base_rental = c(1141.37, 287.07, 0), down_pymt = c(0, 
1144.04, 0), car_count = c(1L, 1L, 1L), dur_lease = c(26L, 1096L, 
1096L), state = c("CA", "NC", "TN"), zip = c(90503, 27603, 37917
), zip_two_digits = c("90", "27", "37"), mod_year_date = c(2015, 
2014, 2013), vehic_mod_fam_code = c("M", "T", "T"), mod_class_code = c("GL", 
"SMT", "SMT"), count_dl_DL_CDE_CSPS_A_NP = c(3347, 764, 820), 
    DL_CDE_CSPS_A_NP_avg_dl = c(97.7472363310427, 97.9842931937173, 
    98.1341463414634), count_sv_DL_CDE_CSPS_A_NP = c(12490, 6796, 
    5364), DL_CDE_CSPS_A_NP_avg_sv = c(92.2642113690953, 92.8987639788111, 
    92.2315436241611), count_dl_NUM_CSPS_INIT_SCR = c(2963, 630, 
    784), NUM_CSPS_INIT_SCR_avg_dl = c(976.999737462032, 976.053968253968, 
    967.816609438776), count_sv_NUM_CSPS_INIT_SCR = c(9710, 5066, 
    4556), NUM_CSPS_INIT_SCR_avg_sv = c(931.544945715757, 934.315041452823, 
    931.331431079895), count_FFV = c(18101, 10362, 8143), average_FFV = c(0.930224849455831, 
    0.941710094576337, 0.888370379467027), csps_NUM_SV = c(0L, 
    0L, 0L), avg_SV_rating = c(952.528718288985, 952.528718288985, 
    952.528718288985), csps_FFV_ratio = c(0.948619406611736, 
    0.948619406611736, 0.948619406611736), avg_DL_rating = c(980.410441044104, 
    980.410441044104, 980.410441044104), has_DL_rating = c(0L, 
    0L, 0L), has_bad_DL_rating = c(0L, 0L, 0L), serv_has_MNT = c(0L, 
    0L, 0L), serv_has_SCP = c(0L, 0L, 0L), serv_has_ELW = c(0L, 
    0L, 0L), serv_has_LCP = c(0L, 0L, 0L), ro_count = c(0L, 4L, 
    4L), ro_tot_cust_pay = c(0, 1147.53, 448.73), ro_tot_pay = c(0, 
    1308.77, 470.23), date_eff_weekday = c("Friday", "Wednesday", 
    "Saturday"), date_eff_month_int = 4:6, date_eff_day = c(3L, 
    14L, 22L)), .Names = c("dlr_id_cur", "date_eff", "new_vec_ind", 
"cntrct_term", "amt_financed", "reg_payment", "acct_stat_cd", 
"base_rental", "down_pymt", "car_count", "dur_lease", "state", 
"zip", "zip_two_digits", "mod_year_date", "vehic_mod_fam_code", 
"mod_class_code", "count_dl_DL_CDE_CSPS_A_NP", "DL_CDE_CSPS_A_NP_avg_dl", 
"count_sv_DL_CDE_CSPS_A_NP", "DL_CDE_CSPS_A_NP_avg_sv", "count_dl_NUM_CSPS_INIT_SCR", 
"NUM_CSPS_INIT_SCR_avg_dl", "count_sv_NUM_CSPS_INIT_SCR", "NUM_CSPS_INIT_SCR_avg_sv", 
"count_FFV", "average_FFV", "csps_NUM_SV", "avg_SV_rating", "csps_FFV_ratio", 
"avg_DL_rating", "has_DL_rating", "has_bad_DL_rating", "serv_has_MNT", 
"serv_has_SCP", "serv_has_ELW", "serv_has_LCP", "ro_count", "ro_tot_cust_pay", 
"ro_tot_pay", "date_eff_weekday", "date_eff_month_int", "date_eff_day"
), row.names = c(38315L, 38820L, 33389L), class = "data.frame")
```

**Comment by dkincaid** [comment]
I am getting the same error running `invoke()`:

this code:
```R
 newTransactions <- newTransactions %>% 
    spark_dataframe() %>%
    invoke("checkpoint", TRUE)
```
produces this error:
```
Error in do.call(.f, args, envir = .env) : 
  'what' must be a function or character string
```

**Comment by curtisburkhalter** [comment]
@javierluraschi I should have been more clear, I'm not actually using an XGBoost model, I created a gradient boosted model in H2O, so the model type used in the code above is an H2O model. 

I think that this maybe causing the issues with my code in that I can't seem to 'tell' spark_apply that H2O should be initialized across all worker nodes in the cluster.

**Comment by lucabarbaglia** [comment]
@curtisburkhalter  do you have any update on this issue?

**Comment by yitao-li** [comment]
If you look at the bottom of the stack trace it says ... RScript ... which means the R closure you were trying to run threw an error. Maybe a first step would be running the R closure directly without spark_apply() on a small subset of data to debug what that error is and fix it, and after that try to run your R closure distributively with spark_apply().
