### ISSUE TITLE
UDF problem with spark_apply

### ISSUE THREAD

**Issue by hanfernandes** [sparklyr/sparklyr#1838]
```

library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", spark_home = "D:\\spark-2.3.1-bin-hadoop2.7")
iris_tbl <- sdf_copy_to(sc, iris)

#it's work
iris %>% mutate(ks2(Sepal.Length,Species))

iris_tbl %>%
  spark_apply(function(df) {
    library(dplyr)
    
    defining the UDF
    ks2 = function(score, alvo){
      b2 <- table(score, alvo)
      freq_bom <- b2[,1]/sum(b2[,1])
      freq_mau <- b2[,2]/sum(b2[,2])
      freq_ac_bom <- cumsum( freq_bom )
      freq_ac_mau <- cumsum( freq_mau )
      diff <- round(abs(freq_ac_bom-freq_ac_mau),3)
      ks <- (max(diff))*100
      return(ks)
    }
    
    df %>% mutate(ks2(Sepal_Length,Species))
  })
```

> Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\HEITOR~1\AppData\Local\Temp\RtmpyOag50\file24e818a5e95_spark.log': Permission denied

Why this error happened ?

Is there a way to use create UDF like done in pyspark?

Exemple: [/spark-sql/udf-python](https://docs.databricks.com/spark/latest/spark-sql/udf-python.html)

**Comment by harryprince** [comment]
you need to specify the mutate variable name like this

```
df %>% mutate(your_var = ks(xxx))
```

**Comment by hanfernandes** [comment]
Does not make sense, even so I tested and the same error happened.

**Comment by benmwhite** [comment]
Are you trying to do a two-sample Kolmogorov-Smirnoff test? `spark_apply()` operates independently on each partition of the input data set, so it's going to give you a separate ECDF for each partition. I really don't think that's what you want exactly. 

Fortunately you can use Spark SQL's `cume_dist` inside a `mutate()` call to get the ECDF values.

```
iris_tbl %>%
  group_by(Species) %>%
  mutate(group_ecdf = cume_dist(Sepal_Length))
```

You can use that as your starting point to get the KS test statistic.

**Comment by vidyasagarbhargava** [comment]
Hi
I am facing issue with udf inside spark_apply. Here is the reprex
``` r
library(sparklyr)

df <- data.frame(units_sold = c(10,15,20,25), visitors = c(100,200, 250, 300))
sc <- spark_connect(master = "local")


df_tbl <- copy_to(sc, df)

df_tbl %>% 
  spark_apply(function(df){
    library(dplyr)
    conversion_rate <- function(col1, col2){
      res = col1/col2
      return <- as.numeric(res)
      
    }
   df %>% mutate(conversion = conversion_rate(units_sold, visitors))
})
#> Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 7.0 failed 1 times, most recent failure: Lost task 0.0 in stage 7.0 (TID 7, localhost, executor driver): java.lang.AssertionError: assertion failed
#>  at scala.Predef$.assert(Predef.scala:156)
#>  at org.apache.spark.storage.BlockInfo.checkInvariants(BlockInfoManager.scala:84)
#>  at org.apache.spark.storage.BlockInfo.readerCount_$eq(BlockInfoManager.scala:66)
#>  at org.apache.spark.storage.BlockInfoManager$$anonfun$releaseAllLocksForTask$2$$anonfun$apply$2.apply(BlockInfoManager.scala:362)
#>  at org.apache.spark.storage.BlockInfoManager$$anonfun$releaseAllLocksForTask$2$$anonfun$apply$2.apply(BlockInfoManager.scala:361)
#>  at scala.Option.foreach(Option.scala:257)
#>  at org.apache.spark.storage.BlockInfoManager$$anonfun$releaseAllLocksForTask$2.apply(BlockInfoManager.scala:361)
#>  at org.apache.spark.storage.BlockInfoManager$$anonfun$releaseAllLocksForTask$2.apply(BlockInfoManager.scala:356)
#>  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
#>  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
#>  at org.apache.spark.storage.BlockInfoManager.releaseAllLocksForTask(BlockInfoManager.scala:356)
#>  at org.apache.spark.storage.BlockManager.releaseAllLocksForTask(BlockManager.scala:670)
#>  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:289)
#>  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
#>  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
#>  at java.lang.Thread.run(Unknown Source)
#> 
#> Driver stacktrace:
#>  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
#>  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
#>  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
#>  at scala.Option.foreach(Option.scala:257)
#>  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
#>  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
#>  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1931)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
#>  at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:333)
#>  at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
#>  at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
#>  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
#>  at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
#>  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
#>  at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collect$1.apply(Dataset.scala:2375)
#>  at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collect$1.apply(Dataset.scala:2375)
#>  at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2778)
#>  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2375)
#>  at org.apache.spark.sql.Dataset.collect(Dataset.scala:2351)
#>  at sparklyr.Utils$.collect(utils.scala:204)
#>  at sparklyr.Utils.collect(utils.scala)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#>  at java.lang.reflect.Method.invoke(Unknown Source)
#>  at sparklyr.Invoke.invoke(invoke.scala:139)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
#>  at sparklyr.StreamHandler.read(stream.scala:66)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:51)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:4)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Unknown Source)
#> Caused by: java.lang.AssertionError: assertion failed
#>  at scala.Predef$.assert(Predef.scala:156)
#>  at org.apache.spark.storage.BlockInfo.checkInvariants(BlockInfoManager.scala:84)
#>  at org.apache.spark.storage.BlockInfo.readerCount_$eq(BlockInfoManager.scala:66)
#>  at org.apache.spark.storage.BlockInfoManager$$anonfun$releaseAllLocksForTask$2$$anonfun$apply$2.apply(BlockInfoManager.scala:362)
#>  at org.apache.spark.storage.BlockInfoManager$$anonfun$releaseAllLocksForTask$2$$anonfun$apply$2.apply(BlockInfoManager.scala:361)
#>  at scala.Option.foreach(Option.scala:257)
#>  at org.apache.spark.storage.BlockInfoManager$$anonfun$releaseAllLocksForTask$2.apply(BlockInfoManager.scala:361)
#>  at org.apache.spark.storage.BlockInfoManager$$anonfun$releaseAllLocksForTask$2.apply(BlockInfoManager.scala:356)
#>  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
#>  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
#>  at org.apache.spark.storage.BlockInfoManager.releaseAllLocksForTask(Bl
```

<sup>Created on 2019-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yitao-li** [comment]
I think the code above would only fail with some older version of Spark. It works just fine with Spark 3.0 and `sparklyr` 1.6.
