### ISSUE TITLE
filter() + sample_frac() return an error

### ISSUE THREAD

**Issue by edgararuiz-zz** [sparklyr/sparklyr#1843]
reprex:

``` r
library(sparklyr) 
#> Warning: package 'sparklyr' was built under R version 3.5.2
library(dplyr, warn.conflicts = FALSE)
sc <- spark_connect("local")
m <- sdf_copy_to(sc, mtcars)

m %>%
  filter(am == 0) %>%
  sample_frac(0.5) 
#> Error: org.apache.spark.sql.catalyst.parser.ParseException: 
#> mismatched input 'FROM' expecting <EOF>(line 2, pos 0)
#> 
#> == SQL ==
#> SELECT *
#> FROM (SELECT *
#> ^^^
#> FROM `mtcars`
#> WHERE (`am` = 0.0) TABLESAMPLE (50 PERCENT)) `kqzmpqmbbf`
#> 
#>  at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:239)
#>  at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:115)
#>  at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
#>  at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:69)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:638)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#>  at java.lang.reflect.Method.invoke(Unknown Source)
#>  at sparklyr.Invoke.invoke(invoke.scala:139)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
#>  at sparklyr.StreamHandler.read(stream.scala:66)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:51)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:4)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
#>  at java.lang.Thread.run(Unknown Source)
```

<sup>Created on 2019-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by nik-maheshwari** [comment]
You will have to collect the dataframe before calling sample_frac. Something like this : 

```
m %>% dplyr::filter(am == 0) %>%
  sdf_collect() %>% dplyr::sample_frac(0.5)
```

**Comment by benmwhite** [comment]
@nik-maheshwari I think `sdf_sample()` is a better alternative since most of the time people are using sampling because the original data is too big to collect anyway.

This might already be known at this point but the same bug also looks like it affects `dplyr::sample_n()`:
```
m <- sdf_copy_to(sc, mtcars)
m %>%
  filter(am == 0) %>%
  dplyr::sample_n(10) 
```
This returns an an error message similar to the one in the original post, with the top lines

```
Error: org.apache.spark.sql.catalyst.parser.ParseException: 
mismatched input 'FROM' expecting <EOF>(line 2, pos 0)

== SQL ==
SELECT *
FROM (SELECT *
^^^
FROM `mtcars`
WHERE (`am` = 0.0) TABLESAMPLE (10 rows) ) `intbksjddi`
```

**Comment by nik-maheshwari** [comment]
@benmwhite Thanks, it is good to know that sdf_sample() or compute() can solve this bug. I prefer using sdf_sample().

**Comment by yitao-li** [comment]
FYI the

```
  m %>%
    filter(am == 0) %>%
    sample_frac(0.5)
```

query works with recent versions of `sparklyr` because `sample_n()` and `sample_frac()` were revised to not use `tablesample` anymore.
