### ISSUE TITLE
sparklyr cannot find sparklyr.ArrowHelper when use with arrow

### ISSUE THREAD

**Issue by bingweiliu** [sparklyr/sparklyr#1962]
Hi,
Our cluster is HDP 2.6.1 with spark 2.1.1. We have been having issue when trying to use arrow with sparklyr to copy data from R to spark.

We install arrow using the source package's r folder.
No issue during installation. 
```r
pkgs = c('vctrs', 'fs','bit64') 
install.packages(pkgs)
install.packages("~/arrow/r", repos = NULL)
```
But then when we try to copy data from R. It's not finding sparklyr.ArrowHelper. Looks like some jars are not found.

```r
Sys.setenv(SPARK_HOME='/usr/hdp/current/spark2-client')
config <- spark_config() # Create your config object
config$sparklyr.defaultPackages <- NULL
config$sparklyr.shell.master <- 'yarn'
config$spark.master <- 'yarn'
config$`sparklyr.shell.driver-memory` <- '5g'
config$spark.executor.memory <- '5g'
config$spark.sql.orc.filterPushdown <- TRUE
config$spark.sql.hive.convertMetastoreOrc <- FALSE
config$spark.shuffle.service.enabled <- TRUE
config$spark.dynamicAllocation.enabled <- TRUE
config$spark.dynamicAllocation.initialExecutors <- 1
config$spark.dynamicAllocation.minExecutors <- 1
config$spark.dynamicAllocation.maxExecutors <- 40
config$spark.dynamicAllocation.executorIdleTimeout <- 150 

spark_version <- "2.1.1"
sc <- spark_connect(config = config, version = spark_version) 
mtcars_tbl <- copy_to(sc, mtcars, overwrite = TRUE)
```
```bash
Error: java.lang.ClassNotFoundException: sparklyr.ArrowHelper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:111)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

## Result of `utils::sessionInfo()`:
```r
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.5 (Maipo)

Matrix products: default
BLAS: /opt/microsoft/ropen/3.5.0/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.5.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.0.1     arrow_0.12.0.9000 DBI_1.0.0         config_0.3        sparklyr_1.0.0   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       rstudioapi_0.9.0 magrittr_1.5     bit_1.1-14       tidyselect_0.2.5 R6_2.4.0        
 [7] rlang_0.3.1      httr_1.4.0       tools_3.5.0      parallel_3.5.0   packrat_0.5.0    withr_2.1.2     
[13] dbplyr_1.3.0     askpass_1.1      ellipsis_0.1.0   htmltools_0.3.6  bit64_0.9-7      openssl_1.2.2   
[19] yaml_2.2.0       assertthat_0.2.0 digest_0.6.18    rprojroot_1.3-2  tibble_2.0.1     forge_0.2.0     
[25] crayon_1.3.4     purrr_0.3.1      base64enc_0.1-3  htmlwidgets_1.3  glue_1.3.1       compiler_3.5.0  
[31] pillar_1.3.1     generics_0.0.2   r2d3_0.2.3       backports_1.1.3  jsonlite_1.6     pkgconfig_2.0.2 
```

**Comment by harryprince** [comment]
maybe try to use spark2.2+, it will be more stable.
And you can directly install spark 2.2+ in your client by 
`sparklyr::spark_install(version = "2.3",hadoop_version="2.6")`

**Comment by yitao-li** [comment]
At the moment `sparklyr` only supports Arrow for Spark 2.3 or above.
