### ISSUE TITLE
Error on loading data frames with escaped characters

### ISSUE THREAD

**Issue by dlindelof** [sparklyr/sparklyr#2014]
``` r
library(sparklyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
sc <- spark_connect(master = "local")
#> Registered S3 method overwritten by 'openssl':
#>   method      from
#>   print.bytes Rcpp
h <- data.frame(name = "h\xf4tel")
copy_to(sc, h)
#> Error: java.nio.charset.MalformedInputException: Input length = 1
#>  at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
#>  at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
#>  at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
#>  at java.io.InputStreamReader.read(InputStreamReader.java:184)
#>  at java.io.BufferedReader.fill(BufferedReader.java:161)
#>  at java.io.BufferedReader.readLine(BufferedReader.java:324)
#>  at java.io.BufferedReader.readLine(BufferedReader.java:389)
#>  at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
#>  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
#>  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
#>  at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
#>  at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:732)
#>  at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:708)
#>  at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
#>  at scala.collection.AbstractIterator.to(Iterator.scala:1336)
#>  at scala.collection.TraversableOnce$class.toIndexedSeq(TraversableOnce.scala:300)
#>  at scala.collection.AbstractIterator.toIndexedSeq(Iterator.scala:1336)
#>  at sparklyr.Utils$.createDataFrameFromCsv(utils.scala:366)
#>  at sparklyr.Utils.createDataFrameFromCsv(utils.scala)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:498)
#>  at sparklyr.Invoke.invoke(invoke.scala:139)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
#>  at sparklyr.StreamHandler.read(stream.scala:66)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:51)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:4)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
#>  at java.lang.Thread.run(Thread.java:748)
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yitao-li** [comment]
Sparklyr uses an intermediate format to facilitate transfer of data from R dataframe to Spark dataframe. This format used to be CSV but has been replaced with RDS in recent versions of sparklyr. The latter is binary instead of textual and is therefore free from CSV-related issues such as the one reported here.
