### ISSUE TITLE
Web UI Port issue 4040

### ISSUE THREAD

**Issue by moldach** [sparklyr/sparklyr#2086]
I'm having difficulty accessing Spark's web interface through `sparklyr`.

When I run the following code it opens a webpage (http://localhost:4040/jobs/) which has an error: **Firefox can’t establish a connection to the server at localhost:4040.** 

```
library(sparklyr)
sc <- spark_connect(master = "local", version = "2.3") # create active Spark Connection
spark_web(sc) # access the web application interface
```

According to the ?`spark_connect()` man page you can specify `master = spark://HOST:PORT`. Our IT specialist confirmed that the HOST:PORT is 172.100.100.101:8081 (and that the port _is_ open with _netstat_).

However, when I run `sc <- spark_connect(master = "spark://172.100.100.101:8081")` I get the following error:
> Error in shell_connection(master = master, spark_home = spark_home, app_name = app_name, : Failed to connect to Spark (SPARK_HOME is not set).

Okay this shouldn't be a big problem as I can find the path with `spark_installed_versions()`:

Then set `SPARK_HOME` via: `Sys.setenv(SPARK_HOME = "/exports/meaney.lab/moldach/spark/spark-2.3.3-bin-hadoop2.7")`

Now run it again:

```
sc <- spark_connect(master = "spark://172.100.100.101:8081")

Error in force(code) : 
  Failed during initialize_connection: java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:91)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:515)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:934)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:925)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:925)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

Log: /tmp/RtmpX6PPYQ/file67b116fe613b_spark.log
---- Output Log ----
19/07/15 16:30:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, cortex.meaney.lab, 34675, None)
19/07/15 16:30:54 INFO BlockManagerMasterEndpoint: Registering block manager cortex.meaney.lab:34675 with 366.3 MB RAM, BlockManagerId(driver, cortex.meaney.lab, 34675, None)
19/07/15 16:30:54 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
19/07/15 16:30:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, cortex.meaney.lab, 34675, None)
19/07/15 16:30:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, cortex.meaney.lab, 34675, None)
19/07/15 16:30:54 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/07/15 16:30:54 INFO MemoryStore: MemoryStore cleared
19/07/15 16:30:54 INFO BlockManager: BlockManager stopped
19/07/15 16:30:55 INFO BlockManagerMaster: BlockManagerMaster stopped
19/07/15 16:30:55 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/07/15 16:30:55 ERROR SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:91)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:515)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:934)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:925)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:925)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel
```

Here's the `sessionInfo()`:

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /share/apps/anaconda2/lib/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.0.0       microbenchmark_1.4-6 doParallel_1.0.14    iterators_1.0.10     foreach_1.4.4       
[6] usethis_1.5.0        devtools_2.0.2      

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5    forge_0.2.0         remotes_2.0.4       purrr_0.3.2         lookup_0.0.0.9000   vctrs_0.1.0        
 [7] generics_0.0.2      testthat_2.1.1      htmltools_0.3.6     yaml_2.2.0          base64enc_0.1-3     utf8_1.1.4         
[13] rlang_0.3.4         pkgbuild_1.0.3      pillar_1.4.1        glue_1.3.1          withr_2.1.2         DBI_1.0.0          
[19] rappdirs_0.3.1      dbplyr_1.4.0        sessioninfo_1.1.1   htmlwidgets_1.3     codetools_0.2-16    memoise_1.1.0.9000 
[25] callr_3.2.0         ps_1.3.0            fansi_0.4.0         r2d3_0.2.3          Rcpp_1.0.1          openssl_1.3        
[31] backports_1.1.4     desc_1.2.0          pkgload_1.0.2       jsonlite_1.6        config_0.3          fs_1.2.7           
[37] askpass_1.1         digest_0.6.19       processx_3.3.0      dplyr_0.8.0.1       rprojroot_1.3-2     cli_1.1.0          
[43] tools_3.5.3         highlite_0.0.0.9000 magrittr_1.5        tibble_2.1.2        zeallot_0.1.0       crayon_1.3.4       
[49] pkgconfig_2.0.2     ellipsis_0.1.0      prettyunits_1.0.2   assertthat_0.2.1    httr_1.4.0          rstudioapi_0.10    
[55] R6_2.4.0            compiler_3.5.3  
```

**Comment by javierluraschi** [comment]
@moldach does the following command work?

```r
library(sparklyr)
sc <- spark_connect(master = "local", version = "2.3")
```

If it doesn't, retry with the following and share the output with us.

```r
sc <- spark_connect(master = "local", version = "2.3", config = list(sparklyr.log.console = TRUE))
```

You should not use `sc <- spark_connect(master = "spark://172.100.100.101:8081")` unless you have a Spark standalone installation, which I don't think is the case.

**Comment by moldach** [comment]
Hey @javierluraschi thanks for the prompt response!

The output for `sc <- spark_connect(master = "local", version = "2.3", config = list(sparklyr.log.console = TRUE))` is:

```
sc <- spark_connect(master = "local", version = "2.3", config = list(sparklyr.log.console = TRUE))
19/07/15 17:00:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/07/15 17:00:08 INFO sparklyr: Session (25613) is starting under 127.0.0.1 port 8880
19/07/15 17:00:08 INFO sparklyr: Session (25613) found port 8880 is not available
19/07/15 17:00:08 INFO sparklyr: Backend (25613) found port 8882 is available
19/07/15 17:00:08 INFO sparklyr: Backend (25613) is registering session in gateway
19/07/15 17:00:08 INFO sparklyr: Backend (25613) is waiting for registration in gateway
19/07/15 17:00:08 INFO sparklyr: Backend (25613) finished registration in gateway with status 0
19/07/15 17:00:08 INFO sparklyr: Backend (25613) is waiting for sparklyr client to connect to port 8882
19/07/15 17:00:09 INFO sparklyr: Backend (25613) accepted connection
19/07/15 17:00:09 INFO sparklyr: Backend (25613) is waiting for sparklyr client to connect to port 8882
19/07/15 17:00:09 INFO sparklyr: Backend (25613) received command 0
19/07/15 17:00:09 INFO sparklyr: Backend (25613) found requested session matches current session
19/07/15 17:00:09 INFO sparklyr: Backend (25613) is creating backend and allocating system resources
19/07/15 17:00:09 INFO sparklyr: Backend (25613) is using port 8883 for backend channel
19/07/15 17:00:09 INFO sparklyr: Backend (25613) created the backend
19/07/15 17:00:09 INFO sparklyr: Backend (25613) is waiting for r process to end
19/07/15 17:00:09 INFO SparkContext: Running Spark version 2.3.3
19/07/15 17:00:09 INFO SparkContext: Submitted application: sparklyr
19/07/15 17:00:09 INFO SecurityManager: Changing view acls to: moldach
19/07/15 17:00:09 INFO SecurityManager: Changing modify acls to: moldach
19/07/15 17:00:09 INFO SecurityManager: Changing view acls groups to: 
19/07/15 17:00:09 INFO SecurityManager: Changing modify acls groups to: 
19/07/15 17:00:09 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(moldach); groups with view permissions: Set(); users  with modify permissions: Set(moldach); groups with modify permissions: Set()
19/07/15 17:00:09 INFO Utils: Successfully started service 'sparkDriver' on port 37579.
19/07/15 17:00:09 INFO SparkEnv: Registering MapOutputTracker
19/07/15 17:00:09 INFO SparkEnv: Registering BlockManagerMaster
19/07/15 17:00:09 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
19/07/15 17:00:09 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
19/07/15 17:00:09 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-43a88955-dbb8-4e19-a538-390f23211869
19/07/15 17:00:09 INFO MemoryStore: MemoryStore started with capacity 912.3 MB
19/07/15 17:00:09 INFO SparkEnv: Registering OutputCommitCoordinator
19/07/15 17:00:10 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/07/15 17:00:10 INFO Utils: Successfully started service 'SparkUI' on port 4041.
19/07/15 17:00:10 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://cortex.meaney.lab:4041
19/07/15 17:00:10 INFO SparkContext: Added JAR file:/usr/lib64/R/library/sparklyr/java/sparklyr-2.3-2.11.jar at spark://cortex.meaney.lab:37579/jars/sparklyr-2.3-2.11.jar with timestamp 1563224410466
19/07/15 17:00:10 INFO Executor: Starting executor ID driver on host localhost
19/07/15 17:00:10 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36162.
19/07/15 17:00:10 INFO NettyBlockTransferService: Server created on cortex.meaney.lab:36162
19/07/15 17:00:10 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/07/15 17:00:10 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, cortex.meaney.lab, 36162, None)
19/07/15 17:00:10 INFO BlockManagerMasterEndpoint: Registering block manager cortex.meaney.lab:36162 with 912.3 MB RAM, BlockManagerId(driver, cortex.meaney.lab, 36162, None)
19/07/15 17:00:10 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, cortex.meaney.lab, 36162, None)
19/07/15 17:00:10 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, cortex.meaney.lab, 36162, None)
19/07/15 17:00:11 INFO SharedState: loading hive config file: file:/exports/meaney.lab/moldach/spark/spark-2.3.3-bin-hadoop2.7/conf/hive-site.xml
19/07/15 17:00:11 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/exports/meaney.lab/moldach/spark-warehouse').
19/07/15 17:00:11 INFO SharedState: Warehouse path is 'file:/exports/meaney.lab/moldach/spark-warehouse'.
19/07/15 17:00:12 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
19/07/15 17:00:14 INFO CodeGenerator: Code generated in 204.362813 ms
```

Now calling `spark_web(sc)` opens the UI correctly (URL = http://cortex.meaney.lab:4041/jobs/)

It appears that without the `config` parameter in the command it's trying to force the `SparkUI` to bind on port 4040 and was forcing local instead of the correct host
