### ISSUE TITLE
sparklyr_1.0.4.9003 fails to start with Spark 2.4.4 / Scala 2.12.8 

### ISSUE THREAD

**Issue by peter-friedland-bose** [sparklyr/sparklyr#2165]
brief description of the problem

```
Under Spark 2.4.4, Scala 2.12.8
sparklyr fails to stark with error:
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
```

reproducible example here
```
$ sparkR
WARNING: ignoring environment value of R_HOME

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Launching java with spark-submit command /usr/local/spark-2.4.4-bin-hadoop-2.8.5/bin/spark-submit   "sparkr-shell" /tmp/RtmpWfS6uQ/backend_port55b37a06a4fe
19/11/12 15:16:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
19/11/12 15:16:42 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/11/12 15:16:43 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.

 Welcome to
    ____              __
   / __/__  ___ _____/ /__
  _\ \/ _ \/ _ `/ __/  '_/
 /___/ .__/\_,_/_/ /_/\_\   version  2.4.4
    /_/


 SparkSession available as 'spark'.
> library(sparklyr)

Attaching package: ‘sparklyr’

The following object is masked from ‘package:SparkR’:

    collect

> sparkconfig <- spark_config()
> sc <- spark_connect(master = "yarn-client", config = sparkconfig)
Error in force(code) :
  Failed while connecting to sparklyr to port (8880) for sessionid (9444): Gateway in localhost:8880 did not respond.
    Path: /usr/local/spark-2.4.4-bin-hadoop-2.8.5/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/usr/local/lib/R/site-library/sparklyr/java/sparklyr-2.4-2.11.jar', 8880, 9444
    Log: /tmp/RtmpWfS6uQ/file55b31985ac87_spark.log


---- Output Log ----
19/11/12 15:17:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
        at sparklyr.Shell$.main(shell.scala:9)
        at sparklyr.Shell.main(shell.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/11/12 15:17:50 INFO ShutdownHookManager: Shutdown hook called
19/11/12 15:17:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-02f66313-9cfb-4896-b2a2-0fe35a6b30d6

---- Error Log ----


> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.04

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] sparklyr_1.0.4.9003 SparkR_2.4.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        rstudioapi_0.10   magrittr_1.5      tidyselect_0.2.5
 [5] R6_2.4.0          rlang_0.4.1       httr_1.4.1        dplyr_0.8.3
 [9] tools_3.6.1       parallel_3.6.1    config_0.3        DBI_1.0.0
[13] withr_2.1.2       dbplyr_1.4.2      askpass_1.1       ellipsis_0.3.0
[17] htmltools_0.4.0   openssl_1.4.1     yaml_2.2.0        assertthat_0.2.1
[21] digest_0.6.22     rprojroot_1.3-2   tibble_2.1.3      forge_0.2.0
[25] crayon_1.3.4      purrr_0.3.3       base64enc_0.1-3   htmlwidgets_1.5.1
[29] glue_1.3.1        compiler_3.6.1    pillar_1.4.2      generics_0.0.2
[33] r2d3_0.2.3        backports_1.1.5   jsonlite_1.6      pkgconfig_2.0.3

For reference, spark-shell:
$ spark-shell
19/11/12 15:23:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
19/11/12 15:23:14 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/11/12 15:23:15 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Spark context Web UI available at http://10.141.9.42:4041
Spark context available as 'sc' (master = yarn, app id = application_1573506585000_0020).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.4
      /_/

Using Scala version 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_222)
Type in expressions to have them evaluated.
Type :help for more information.

scala>

**Comment by benmwhite** [comment]
You need to be running sparklyr in a standard R session, not in a SparkR session.

**Comment by peter-friedland-bose** [comment]
@benmwhite do you mean like this:

```
$ R
WARNING: ignoring environment value of R_HOME

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(sparklyr)
> sparkconfig <- spark_config()
> sc <- spark_connect(master = "yarn-client", config = sparkconfig)
Error in force(code) :
  Failed while connecting to sparklyr to port (8880) for sessionid (75249): Gateway in localhost:8880 did not respond.
    Path: /usr/local/spark-2.4.4-bin-hadoop-2.8.5/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/usr/local/lib/R/site-library/sparklyr/java/sparklyr-2.4-2.11.jar', 8880, 75249
    Log: /tmp/RtmpBqrp64/file5bd636ed602_spark.log


---- Output Log ----
19/11/12 16:52:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
        at sparklyr.Shell$.main(shell.scala:9)
        at sparklyr.Shell.main(shell.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/11/12 16:52:20 INFO ShutdownHookManager: Shutdown hook called
19/11/12 16:52:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-ceb99627-902e-4c0b-bbb3-5e874954355e

---- Error Log ----
>

```

**Comment by benmwhite** [comment]
Hmm, maybe try specifying the Spark and Java home directories [like in this comment](https://github.com/rstudio/sparklyr/issues/254#issuecomment-329529699). You might also need to specify [Hadoop home too.](https://stackoverflow.com/questions/40015416/spark-unable-to-load-native-hadoop-library-for-your-platform#40022657). You should be able to do this with something like 
```
Sys.setenv(
  SPARK_HOME = x,
  JAVA_HOME = y,
  HADOOP_HOME = z
)
```
within R before you call `spark_connect()`, after finding the appropriate file paths on your system.

**Comment by javierluraschi** [comment]
Can you try with the CRAN version? I hit this issue as well and recompiling the JARs fixed the issue.

**Comment by yl790** [comment]
In sparklyr 1.3, this type of issue can be addressed by specifying the Scala version explicitly (e.g.,`sc <- spark_connect(..., scala_version = "2.12")`).
