### ISSUE TITLE
copy_to fails with databricks-connect 6.4.0

### ISSUE THREAD

**Issue by blairj09** [sparklyr/sparklyr#2320]
`copy_to()` works with `databricks-connect 6.3.1` but fails with `databricks-connect 6.4.0`. This is related to #2282

```r
library(sparklyr)

Sys.setenv(SPARK_HOME = "/Users/jamesblair/anaconda3/envs/databricks/lib/python3.7/site-packages/pyspark/")

sc <- spark_connect(master = "local", method = "databricks")

cars <- copy_to(sc, mtcars, overwrite = TRUE)
#> Error: java.io.InvalidClassException: failed to read class descriptor
#>  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1859)
#>  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
#>  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
#>  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
#>  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
#>  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
#>  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
#>  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
#>  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
#>  at org.apache.spark.sql.util.ProtoSerializer.deserializeObject(ProtoSerializer.scala:4312)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anonfun$deserializeContext$1.apply(ProtoSerializer.scala:259)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anonfun$deserializeContext$1.apply(ProtoSerializer.scala:258)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
#>  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
#>  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
#>  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
#>  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
#>  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
#>  at org.apache.spark.sql.util.ProtoSerializer.deserializeContext(ProtoSerializer.scala:258)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anonfun$deserializePlan$1.apply(ProtoSerializer.scala:2897)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anonfun$deserializePlan$1.apply(ProtoSerializer.scala:2897)
#>  at scala.Option.foreach(Option.scala:257)
#>  at org.apache.spark.sql.util.ProtoSerializer.deserializePlan(ProtoSerializer.scala:2897)
#>  at com.databricks.service.SparkServiceImpl$.com$databricks$service$SparkServiceImpl$$sessionOperation0(SparkServiceImpl.scala:399)
#>  at com.databricks.service.SparkServiceImpl$$anonfun$sessionOperation$1.apply(SparkServiceImpl.scala:127)
#>  at com.databricks.service.SparkServiceImpl$$anonfun$sessionOperation$1.apply(SparkServiceImpl.scala:127)
#>  at com.databricks.logging.UsageLogging$$anonfun$recordOperation$1.apply(UsageLogging.scala:440)
#>  at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:251)
#>  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
#>  at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:246)
#>  at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:18)
#>  at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:288)
#>  at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:18)
#>  at com.databricks.logging.UsageLogging$class.recordOperation(UsageLogging.scala:421)
#>  at com.databricks.spark.util.PublicDBLogging.recordOperation(DatabricksSparkUsageLogger.scala:18)
#>  at com.databricks.spark.util.PublicDBLogging.recordOperation0(DatabricksSparkUsageLogger.scala:55)
#>  at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:98)
#>  at com.databricks.spark.util.UsageLogger$class.recordOperation(UsageLogger.scala:67)
#>  at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:67)
#>  at com.databricks.spark.util.UsageLogging$class.recordOperation(UsageLogger.scala:342)
#>  at com.databricks.service.SparkServiceImpl$.recordOperation(SparkServiceImpl.scala:54)
#>  at com.databricks.service.SparkServiceImpl$.sessionOperation(SparkServiceImpl.scala:126)
#>  at com.databricks.service.SparkServiceRPCHandler.com$databricks$service$SparkServiceRPCHandler$$execute0(SparkServiceRPCHandler.scala:498)
#>  at com.databricks.service.SparkServiceRPCHandler$$anonfun$executeRPC0$1.apply(SparkServiceRPCHandler.scala:376)
#>  at com.databricks.service.SparkServiceRPCHandler$$anonfun$executeRPC0$1.apply(SparkServiceRPCHandler.scala:317)
#>  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
#>  at com.databricks.service.SparkServiceRPCHandler.executeRPC0(SparkServiceRPCHandler.scala:317)
#>  at com.databricks.service.SparkServiceRPCHandler$$anon$3.call(SparkServiceRPCHandler.scala:272)
#>  at com.databricks.service.SparkServiceRPCHandler$$anon$3.call(SparkServiceRPCHandler.scala:260)
#>  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
#>  at com.databricks.service.SparkServiceRPCHandler$$anonfun$executeRPC$1.apply(SparkServiceRPCHandler.scala:304)
#>  at com.databricks.service.SparkServiceRPCHandler$$anonfun$executeRPC$1.apply(SparkServiceRPCHandler.scala:284)
#>  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
#>  at com.databricks.service.SparkServiceRPCHandler.executeRPC(SparkServiceRPCHandler.scala:283)
#>  at com.databricks.service.SparkServiceRPCServlet.doPost(SparkServiceRPCServer.scala:124)
#>  at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
#>  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
#>  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
#>  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
#>  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
#>  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
#>  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
#>  at org.eclipse.jetty.server.Server.handle(Server.java:539)
#>  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
#>  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
#>  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
#>  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
#>  at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
#>  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
#>  at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
#>  at java.lang.Thread.run(Thread.java:748)
#> Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.SparkSession$clienta8207399be$$anonfun$4
#>  at java.lang.ClassLoader.findClass(ClassLoader.java:523)
#>  at org.apache.spark.util.ParentClassLoader.findClass(ParentClassLoader.java:35)
#>  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
#>  at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.java:40)
#>  at org.apache.spark.util.ChildFirstURLClassLoader.loadClass(ChildFirstURLClassLoader.java:48)
#>  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
#>  at java.lang.Class.forName0(Native Method)
#>  at java.lang.Class.forName(Class.java:348)
#>  at org.apache.spark.util.Utils$.classForName(Utils.scala:257)
#>  at org.apache.spark.sql.util.ProtoSerializer.org$apache$spark$sql$util$ProtoSerializer$$readResolveClassDescriptor(ProtoSerializer.scala:4321)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anon$4.readClassDescriptor(ProtoSerializer.scala:4309)
#>  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1857)
#>  ... 75 more

cars
#>    speed dist
#> 1      4    2
#> 2      4   10
#> 3      7    4
#> 4      7   22
#> 5      8   16
#> 6      9   10
#> 7     10   18
#> 8     10   26
#> 9     10   34
#> 10    11   17
#> 11    11   28
#> 12    12   14
#> 13    12   20
#> 14    12   24
#> 15    12   28
#> 16    13   26
#> 17    13   34
#> 18    13   34
#> 19    13   46
#> 20    14   26
#> 21    14   36
#> 22    14   60
#> 23    14   80
#> 24    15   20
#> 25    15   26
#> 26    15   54
#> 27    16   32
#> 28    16   40
#> 29    17   32
#> 30    17   40
#> 31    17   50
#> 32    18   42
#> 33    18   56
#> 34    18   76
#> 35    18   84
#> 36    19   36
#> 37    19   46
#> 38    19   68
#> 39    20   32
#> 40    20   48
#> 41    20   52
#> 42    20   56
#> 43    20   64
#> 44    22   66
#> 45    23   54
#> 46    24   70
#> 47    24   92
#> 48    24   93
#> 49    24  120
#> 50    25   85

spark_disconnect(sc)
```

**Comment by blairj09** [comment]
Some further context with this after further investigation. It seems like `copy_to()` reports an error the first time it's run, but the copy successfully completes. Subsequent calls to `copy_to()` succeed as expected.

``` r
library(sparklyr)
library(DBI)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

sc <- spark_connect(method = "databricks", 
                    spark_home = "/Users/jamesblair/anaconda3/envs/databricks/lib/python3.7/site-packages/pyspark")

tbl_name <- "mtcars"

dbListTables(sc)
#> [1] "credit_card_default" "flights"             "iris_csv"
dbExistsTable(sc, tbl_name)
#> [1] FALSE

cars_tbl <- copy_to(sc, mtcars, tbl_name, overwrite = TRUE)
#> Error: java.io.InvalidClassException: failed to read class descriptor
#>  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1859)
#>  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
#>  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
#>  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
#>  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
#>  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
#>  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
#>  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
#>  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
#>  at org.apache.spark.sql.util.ProtoSerializer.deserializeObject(ProtoSerializer.scala:4312)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anonfun$deserializeContext$1.apply(ProtoSerializer.scala:259)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anonfun$deserializeContext$1.apply(ProtoSerializer.scala:258)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
#>  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
#>  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
#>  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
#>  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
#>  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
#>  at org.apache.spark.sql.util.ProtoSerializer.deserializeContext(ProtoSerializer.scala:258)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anonfun$deserializePlan$1.apply(ProtoSerializer.scala:2897)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anonfun$deserializePlan$1.apply(ProtoSerializer.scala:2897)
#>  at scala.Option.foreach(Option.scala:257)
#>  at org.apache.spark.sql.util.ProtoSerializer.deserializePlan(ProtoSerializer.scala:2897)
#>  at com.databricks.service.SparkServiceImpl$.com$databricks$service$SparkServiceImpl$$sessionOperation0(SparkServiceImpl.scala:399)
#>  at com.databricks.service.SparkServiceImpl$$anonfun$sessionOperation$1.apply(SparkServiceImpl.scala:127)
#>  at com.databricks.service.SparkServiceImpl$$anonfun$sessionOperation$1.apply(SparkServiceImpl.scala:127)
#>  at com.databricks.logging.UsageLogging$$anonfun$recordOperation$1.apply(UsageLogging.scala:440)
#>  at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:251)
#>  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
#>  at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:246)
#>  at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:18)
#>  at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:288)
#>  at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:18)
#>  at com.databricks.logging.UsageLogging$class.recordOperation(UsageLogging.scala:421)
#>  at com.databricks.spark.util.PublicDBLogging.recordOperation(DatabricksSparkUsageLogger.scala:18)
#>  at com.databricks.spark.util.PublicDBLogging.recordOperation0(DatabricksSparkUsageLogger.scala:55)
#>  at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:98)
#>  at com.databricks.spark.util.UsageLogger$class.recordOperation(UsageLogger.scala:67)
#>  at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:67)
#>  at com.databricks.spark.util.UsageLogging$class.recordOperation(UsageLogger.scala:342)
#>  at com.databricks.service.SparkServiceImpl$.recordOperation(SparkServiceImpl.scala:54)
#>  at com.databricks.service.SparkServiceImpl$.sessionOperation(SparkServiceImpl.scala:126)
#>  at com.databricks.service.SparkServiceRPCHandler.com$databricks$service$SparkServiceRPCHandler$$execute0(SparkServiceRPCHandler.scala:498)
#>  at com.databricks.service.SparkServiceRPCHandler$$anonfun$executeRPC0$1.apply(SparkServiceRPCHandler.scala:376)
#>  at com.databricks.service.SparkServiceRPCHandler$$anonfun$executeRPC0$1.apply(SparkServiceRPCHandler.scala:317)
#>  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
#>  at com.databricks.service.SparkServiceRPCHandler.executeRPC0(SparkServiceRPCHandler.scala:317)
#>  at com.databricks.service.SparkServiceRPCHandler$$anon$3.call(SparkServiceRPCHandler.scala:272)
#>  at com.databricks.service.SparkServiceRPCHandler$$anon$3.call(SparkServiceRPCHandler.scala:260)
#>  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
#>  at com.databricks.service.SparkServiceRPCHandler$$anonfun$executeRPC$1.apply(SparkServiceRPCHandler.scala:304)
#>  at com.databricks.service.SparkServiceRPCHandler$$anonfun$executeRPC$1.apply(SparkServiceRPCHandler.scala:284)
#>  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
#>  at com.databricks.service.SparkServiceRPCHandler.executeRPC(SparkServiceRPCHandler.scala:283)
#>  at com.databricks.service.SparkServiceRPCServlet.doPost(SparkServiceRPCServer.scala:124)
#>  at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
#>  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
#>  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
#>  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
#>  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
#>  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
#>  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
#>  at org.eclipse.jetty.server.Server.handle(Server.java:539)
#>  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
#>  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
#>  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
#>  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
#>  at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
#>  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
#>  at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
#>  at java.lang.Thread.run(Thread.java:748)
#> Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.SparkSession$client3dadd36ab9$$anonfun$4
#>  at java.lang.ClassLoader.findClass(ClassLoader.java:523)
#>  at org.apache.spark.util.ParentClassLoader.findClass(ParentClassLoader.java:35)
#>  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
#>  at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.java:40)
#>  at org.apache.spark.util.ChildFirstURLClassLoader.loadClass(ChildFirstURLClassLoader.java:48)
#>  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
#>  at java.lang.Class.forName0(Native Method)
#>  at java.lang.Class.forName(Class.java:348)
#>  at org.apache.spark.util.Utils$.classForName(Utils.scala:257)
#>  at org.apache.spark.sql.util.ProtoSerializer.org$apache$spark$sql$util$ProtoSerializer$$readResolveClassDescriptor(ProtoSerializer.scala:4321)
#>  at org.apache.spark.sql.util.ProtoSerializer$$anon$4.readClassDescriptor(ProtoSerializer.scala:4309)
#>  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1857)
#>  ... 75 more
cars_tbl
#> Error in eval(expr, envir, enclos): object 'cars_tbl' not found

dbListTables(sc)
#> [1] "credit_card_default" "flights"             "iris_csv"           
#> [4] "mtcars"

if (dbExistsTable(sc, tbl_name)) {
  cars_tbl_read <- dbReadTable(sc, tbl_name)
}

head(cars_tbl_read)
#>    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> 1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> 2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> 3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> 4 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> 5 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> 6 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1

cars_tbl <- copy_to(sc, mtcars, tbl_name, overwrite = TRUE)
head(cars_tbl)
#> # Source: spark<?> [?? x 11]
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  21       6   160   110  3.9   2.62  16.5     0     1     4     4
#> 2  21       6   160   110  3.9   2.88  17.0     0     1     4     4
#> 3  22.8     4   108    93  3.85  2.32  18.6     1     1     4     1
#> 4  21.4     6   258   110  3.08  3.22  19.4     1     0     3     1
#> 5  18.7     8   360   175  3.15  3.44  17.0     0     0     3     2
#> 6  18.1     6   225   105  2.76  3.46  20.2     1     0     3     1

iris_tbl <- copy_to(sc, iris)
head(iris_tbl)
#> # Source: spark<?> [?? x 5]
#>   Sepal_Length Sepal_Width Petal_Length Petal_Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#> 1          5.1         3.5          1.4         0.2 setosa 
#> 2          4.9         3            1.4         0.2 setosa 
#> 3          4.7         3.2          1.3         0.2 setosa 
#> 4          4.6         3.1          1.5         0.2 setosa 
#> 5          5           3.6          1.4         0.2 setosa 
#> 6          5.4         3.9          1.7         0.4 setosa

spark_disconnect(sc)
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
