### ISSUE TITLE
"Unexpected end of input" error when using spark_apply

### ISSUE THREAD

**Issue by ponolson** [sparklyr/sparklyr#2328]
Hi,

I am running into a timing-related error when using `spark_apply`.  I am running on Windows with `master = "local"`.  When this situation occurs, the spark job fails out completely (i.e. it doesn't retry) and the entire job has to be re-executed.  

The main symptom I see is that the `spark.log` file contains:
```
Error: unexpected end of input
Execution halted
```

A broader context for the errors is a sequence such as the following:
```
20/03/18 18:53:19 INFO sparklyr: Worker (3179) is tracking worker context under 0
20/03/18 18:53:19 INFO sparklyr: Worker (3179) initializing backend
20/03/18 18:53:19 INFO sparklyr: Session (3179) is starting under 127.0.0.1 port 8880
20/03/18 18:53:19 INFO sparklyr: Worker (3179) is waiting using lock for RScript to complete
20/03/18 18:53:19 INFO sparklyr: Worker (3179) starting backend
20/03/18 18:53:19 INFO sparklyr: Worker (3179) is starting rscript
20/03/18 18:53:19 INFO sparklyr: Session (3179) is waiting for sparklyr client to connect to port 49310
20/03/18 18:53:19 INFO sparklyr: Worker (3179) using source file C:\Users\****\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7\tmp\local\spark-9ceaf65c-67a9-40ea-a953-08e1bfbe4078\userFiles-5f79455b-d40c-432b-93e9-7810d02130d6\sparkworker.R
20/03/18 18:53:19 INFO sparklyr: Worker (3179) launching command Rscript --vanilla C:\Users\****\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7\tmp\local\spark-9ceaf65c-67a9-40ea-a953-08e1bfbe4078\userFiles-5f79455b-d40c-432b-93e9-7810d02130d6\sparkworker.R 3179 49310 FALSE;8880;localhost;FALSE;FALSE;FALSE
20/03/18 18:53:19 INFO sparklyr: Worker (3179) is starting R process
.
.
.
20/03/18 18:53:21 INFO sparklyr: Worker (8491) is tracking worker context under 0
20/03/18 18:53:21 INFO sparklyr: Worker (8491) initializing backend
20/03/18 18:53:21 INFO sparklyr: Session (8491) is starting under 127.0.0.1 port 8880
20/03/18 18:53:21 INFO sparklyr: Worker (8491) is waiting using lock for RScript to complete
20/03/18 18:53:21 INFO sparklyr: Worker (8491) starting backend
20/03/18 18:53:21 INFO sparklyr: Session (8491) is waiting for sparklyr client to connect to port 49317
20/03/18 18:53:21 INFO sparklyr: Worker (8491) is starting rscript
Error: unexpected end of input
Execution halted
20/03/18 18:53:21 INFO sparklyr: Worker (8491) using source file C:\Users\****\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7\tmp\local\spark-9ceaf65c-67a9-40ea-a953-08e1bfbe4078\userFiles-5f79455b-d40c-432b-93e9-7810d02130d6\sparkworker.R
20/03/18 18:53:21 INFO sparklyr: Worker (8491) launching command Rscript --vanilla C:\Users\****\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7\tmp\local\spark-9ceaf65c-67a9-40ea-a953-08e1bfbe4078\userFiles-5f79455b-d40c-432b-93e9-7810d02130d6\sparkworker.R 8491 49317 FALSE;8880;localhost;FALSE;FALSE;FALSE
20/03/18 18:53:21 INFO sparklyr: Worker (8491) is starting R process
20/03/18 18:53:21 ERROR sparklyr: Worker (3179) failed to complete R process
(20/03/18 18:53:21 ERROR sparklyr: Worker (3179) failed to run rscript: ,java.lang.Exception: sparklyr worker rscript failure with status 1, check worker logs for details.)
20/03/18 18:53:21 INFO sparklyr: Worker (3179) completed wait using lock for RScript
20/03/18 18:53:21 ERROR Executor: Exception in task 72.0 in stage 2.0 (TID 573)
java.lang.Exception: sparklyr worker rscript failure with status 1, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:83)
	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:123)

```
In this example, session 3179 starts up then a couple seconds later session 8491 starts up.  I believe the `Error: unexpected end of input` is coming from session 3179, and that session subsequently fails out.

After looking at the `sparklyr` code, I believe the root issue is that both sessions are trying to use the exact same file location for `sparkworker.R`.  In this example, session 3179 has written that file but while the `Rscript` process for 3179 is still reading `sparkworker.R`, session 8491 rewrites the file out from underneath 3179.

This is definitely a timing related issue, but I am able to reproduce it pretty consistently with the following code:
```r
library(sparklyr)

sc <- spark_connect(master = "local")

df_result <- sdf_len(sc, 500, repartition = 500) %>%
  spark_apply(function(df) df * 10) %>%
  collect()
```

I tested a fix/workaround in `workerapply.scala` to include the `sessionId` in the `sparkerworker.R` file name so that each session has its own copy:
```scala
  def workerSourceFile(rscript: Rscript, sessionId: Int): String = {
    val rsources = new Sources()
    val source = rsources.sources

    val tempFile: File = new File(rscript.getScratchDir() + File.separator + "sparkworker_" + sessionId.toString + ".R")
    val outStream: FileWriter = new FileWriter(tempFile)
    outStream.write(source)
    outStream.flush()

    tempFile.getAbsolutePath()
  }
```
So far this seems to avoid/resolve the issue, though there may be better solutions (e.g. perhaps just write the file once instead of re-writing for every session?).

Thanks!

Output from devtools::session_info():
```
- Session info -----------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Chicago             
 date     2020-03-18                  

- Packages ---------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
 backports     1.1.5   2019-10-02 [1] CRAN (R 3.5.3)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.5.0)
 callr         3.3.2   2019-09-22 [1] CRAN (R 3.5.3)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
 colorspace    1.3-2   2016-12-14 [1] CRAN (R 3.5.1)
 config        0.3     2018-03-27 [1] CRAN (R 3.5.1)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
 DBI           1.0.0   2018-05-02 [1] CRAN (R 3.5.1)
 dbplyr        1.4.2   2019-06-17 [1] CRAN (R 3.5.3)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.1)
 devtools      2.0.2   2019-04-08 [1] CRAN (R 3.5.3)
 digest        0.6.22  2019-10-21 [1] CRAN (R 3.5.3)
 dplyr         0.8.3   2019-07-04 [1] CRAN (R 3.5.3)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.5.3)
 fansi         0.4.0   2018-10-05 [1] CRAN (R 3.5.3)
 forge         0.2.0   2019-02-26 [1] CRAN (R 3.5.3)
 fs            1.2.5   2018-07-30 [1] CRAN (R 3.5.1)
 generics      0.0.2   2018-11-29 [1] CRAN (R 3.5.3)
 ggplot2       3.2.1   2019-08-10 [1] CRAN (R 3.5.3)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
 gtable        0.2.0   2016-02-26 [1] CRAN (R 3.5.1)
 htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
 htmlwidgets   1.3     2018-09-30 [1] CRAN (R 3.5.1)
 httr          1.4.1   2019-08-05 [1] CRAN (R 3.5.3)
 jsonlite      1.6     2018-12-07 [1] CRAN (R 3.5.3)
 lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.5.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.1)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.1)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 3.5.1)
 openssl       1.0.2   2018-07-30 [1] CRAN (R 3.5.1)
 pillar        1.4.3   2019-12-20 [1] CRAN (R 3.5.3)
 pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.5.3)
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.3)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.3)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.1)
 processx      3.4.1   2019-07-18 [1] CRAN (R 3.5.3)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.3)
 purrr         0.3.3   2019-10-18 [1] CRAN (R 3.5.3)
 r2d3          0.2.3   2018-12-18 [1] CRAN (R 3.5.3)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.3)
 rappdirs      0.3.1   2016-03-28 [1] CRAN (R 3.5.1)
 Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.5.3)
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.3)
 rlang         0.4.1   2019-10-24 [1] CRAN (R 3.5.3)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.1)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.5.3)
 scales        1.0.0   2018-08-09 [1] CRAN (R 3.5.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.3)
 sparklyr    * 1.1.0   2020-01-11 [1] CRAN (R 3.5.1)
 testthat      2.1.1   2019-04-23 [1] CRAN (R 3.5.3)
 tibble        2.1.3   2019-06-06 [1] CRAN (R 3.5.3)
 tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.3)
 usethis       1.5.0   2019-04-07 [1] CRAN (R 3.5.3)
 utf8          1.1.4   2018-05-24 [1] CRAN (R 3.5.1)
 vctrs         0.2.1   2019-12-17 [1] CRAN (R 3.5.3)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)
 zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.5.3)

[1] C:/Users/****/Documents/R/R-3.5.1/library
```

**Comment by yl790** [comment]
@ponolson Wow thanks for reporting this bug!! I think your suggested fix sounds legit. I'll get it tested & code-reviewed soon.
