### ISSUE TITLE
JVM object might disappear before method invocation happens

### ISSUE THREAD

**Issue by yl790** [sparklyr/sparklyr#2334]
The following would eventually fail on a host having high memory pressure (e.g., only having 100MB or less free memory left):

create_two_connections.R:

```
library(sparklyr) 

sc <- spark_connect(master = "local")  # spark version appears to be irrelevant here
sc2 <- spark_connect(master = "local", app_name = "other")

```

stress-test script:
```
#!/bin/bash

TEST_LOG='/tmp/test.log'
echo > "$TEST_LOG"

while true; do
  R --no-save < ./create_two_connections.R 2>&1 | tee -a "$TEST_LOG"
  sleep 1
done

```

with the following

> > library(sparklyr)
> >
> > sc <- spark_connect(master = "local")
> > sc2 <- spark_connect(master = "local", app_name = "other")
> Error in force(code) :
>   Failed during initialize_connection: java.lang.IllegalArgumentException: Object not found 8
>         at sparklyr.StreamHandler.handleMethodCall(stream.scala:114)
>         at sparklyr.StreamHandler.read(stream.scala:65)
>         at sparklyr.BackendHandler.channelRead0(handler.scala:53)
>         at sparklyr.BackendHandler.channelRead0(handler.scala:12)
>         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.lang.Thread.run(Thread.java:748)
> 
>     Log: /tmp/RtmpPFBvQJ/file708d6ae3e6f5_spark.log
> 
> 
> ---- Output Log ----
> 20/03/20 17:13:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> 20/03/20 17:13:49 INFO sparklyr: Session (1010) is starting under 127.0.0.1 port 8880
> 20/03/20 17:13:49 INFO sparklyr: Session (1010) found port 8880 is not available
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) found port 8882 is available
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) is registering session in gateway
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) is waiting for registration in gateway
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) finished registration in gateway with status 0
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) is waiting for sparklyr client to connect to port 8882
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) accepted connection
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) is waiting for sparklyr client to connect to port 8882
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) received command 0
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) found requested session matches current session
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) is creating backend and allocating system resources
> 20/03/20 17:13:49 INFO sparklyr: Backend (1010) is using port 8883 for backend channel
> 20/03/20 17:13:50 INFO sparklyr: Backend (1010) created the backend
> 20/03/20 17:13:50 INFO sparklyr: Backend (1010) is waiting for r process to end
> 20/03/20 17:13:50 ERROR sparklyr: Backend (1010) failed calling config on 8: java.lang.IllegalArgumentException: Object not found 8
>         at sparklyr.StreamHandler.handleMethodCall(stream.scala:114)
>         at sparklyr.StreamHandler.read(stream.scala:65)
>         at sparklyr.BackendHandler.channelRead0(handler.scala:53)
>         at sparklyr.BackendHandler.channelRead0(handler.scala:12)
>         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.lang.Thread.run(Thread.java:748)
> 

which looks like it could be either some ref counting bug with R 3.6.3 (the version I'm running to test this) or ref counting bug with java objects / jvm object tracker in sparklyr.

There was a recent change in jvm object tracker but I just verified reverting that change did not help.

**Comment by yl790** [comment]
cc @javierluraschi -- we actually saw this in one of the pull requests I was working with but was not actively looking into it at that time because the said pull request was replaced with another one which didn't trigger this race condition. Most likely we need to look into this now (and I would say it's at least mid-pri)
