### ISSUE TITLE
Error using sparklyr spark_write_csv when writing into s3 bucket

### ISSUE THREAD

**Issue by dhcrc** [sparklyr/sparklyr#2591]
I am trying to write a spark DataFrame to S3 bucket using sparklyr R package. I have both read and write access to the bucket. When writing back, I get job aborted error. The destination folder is created in the S3 but it is empty. I can use the same command and write the file in a local drive without any issues.

```r

# spark_version:  "2.3.3"

Sys.setenv("AWS_ACCESS_KEY_ID" = "hidden","AWS_SECRET_ACCESS_KEY" = "hidden")

data <- spark_read_csv(sc,
                       name = "mt_tbl", 
                       path = "s3a://my-bucket.name/mt.txt",
                       delimiter = ",",
                       memory = TRUE,
                       overwrite = TRUE,
                       infer_schema = TRUE)

myData <- data %>% select(mpg,cyl) %>% filter(cyl == 6) %>% compute()

spark_write_csv(myData , path = 's3a://my-bucket.name/cars', mode = "overwrite")
```
Error: org.apache.spark.SparkException: Job aborted. at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:224) at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:154) at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104) at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102) at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127) at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155) ...

**Comment by yl790** [comment]
@dhcrc Does your `spark-defaults.conf` file contain the required `spark.hadoop.fs.s3a.access.key` and `spark.hadoop.fs.s3a.secret.key`? Also please see https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html and https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html#Authentication_properties (unfortunately it looks like the correct configuration needed here is not as simple as `Sys.setenv("AWS_ACCESS_KEY_ID" = "hidden","AWS_SECRET_ACCESS_KEY" = "hidden")`)

**Comment by dhcrc** [comment]
Thanks a lot for the reply, 
I tried the solution in [here](https://stackoverflow.com/questions/45190188/sparklyr-connection-to-s3-bucket-throwing-up-error) to set  `spark.hadoop.fs.s3a.access.key` and `spark.hadoop.fs.s3a.secret.key` but got the same error. I wonder if the credentials are the issue, how come I can read from the bucket and the `spark_write_csv` command creates the empty folder in the destination bucket?
