### ISSUE TITLE
Copy the dataframe to Spark not working!

### ISSUE THREAD

**Issue by SieSiongWong** [sparklyr/sparklyr#2603]
Hi,

I have a data frame dimension (4247, 2460) and try copy to Spark but getting below java error. Please help!

In my local machine, I do slicing and can load successfully. But when I do the same thing in the AWS RStudio it throws me below error. Note that I can do the copy with another data frame successfully in the AWS RStudio.  I could not figure out why it works on one machine but no the other. Please help!

Error: java.lang.IllegalArgumentException: Invalid type null
	at sparklyr.SQLUtils$.getSQLDataType(sqlutils.scala:77)
	at sparklyr.SQLUtils$.createStructField(sqlutils.scala:82)
	at sparklyr.SQLUtils.createStructField(sqlutils.scala)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at sparklyr.BackendHandler.channelRead0(handler.scala:38)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by SieSiongWong** [comment]
This is the SessionInfo:

sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=C.UTF-8      
 [2] LC_NUMERIC=C          
 [3] LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8   
 [6] LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8      
 [8] LC_NAME=C             
 [9] LC_ADDRESS=C          
[10] LC_TELEPHONE=C        
[11] LC_MEASUREMENT=C.UTF-8
[12] LC_IDENTIFICATION=C   

attached base packages:
[1] grid      stats     graphics  grDevices
[5] utils     datasets  methods   base     

other attached packages:
 [1] plyr_1.8.4               
 [2] knitr_1.22               
 [3] tidyr_0.8.3              
 [4] kableExtra_1.1.0         
 [5] gridExtra_2.3            
 [6] Hmisc_4.4-0              
 [7] Formula_1.2-3            
 [8] survival_3.2-3           
 [9] lattice_0.20-38          
[10] h2o_3.30.0.1             
[11] tictoc_1.0               
[12] reshape2_1.4.3           
[13] sparklyr_1.3.1           
[14] forcats_0.4.0            
[15] stringr_1.4.0            
[16] dplyr_1.0.0              
[17] purrr_0.3.2              
[18] readr_1.3.1              
[19] tibble_3.0.2             
[20] ggplot2_3.1.1            
[21] tidyverse_1.2.1          
[22] rsparkling_3.30.0.6-1-2.4
[23] data.table_1.12.8        
[24] recommenderlab_0.2-6     
[25] registry_0.5-1           
[26] proxy_0.4-24             
[27] arules_1.6-6             
[28] Matrix_1.2-17            

loaded via a namespace (and not attached):
 [1] nlme_3.1-139       
 [2] matrixStats_0.54.0 
 [3] bitops_1.0-6       
 [4] lubridate_1.7.4    
 [5] webshot_0.5.2      
 [6] RColorBrewer_1.1-2 
 [7] httr_1.4.0         
 [8] rprojroot_1.3-2    
 [9] rstan_2.18.2       
[10] tools_3.6.0        
[11] backports_1.1.4    
[12] R6_2.4.0           
[13] irlba_2.3.3        
[14] rpart_4.1-15       
[15] DBI_1.0.0          
[16] lazyeval_0.2.2     
[17] colorspace_1.4-1   
[18] nnet_7.3-12        
[19] withr_2.1.2        
[20] prettyunits_1.0.2  
[21] processx_3.3.0     
[22] tidyselect_1.1.0   
[23] curl_3.3           
[24] compiler_3.6.0     
[25] cli_1.1.0          
[26] rvest_0.3.3        
[27] htmlTable_2.0.1    
[28] forge_0.2.0        
[29] xml2_1.2.0         
[30] scales_1.1.1       
[31] checkmate_1.9.3    
[32] askpass_1.1        
[33] callr_3.2.0        
[34] rappdirs_0.3.1     
[35] StanHeaders_2.18.1 
[36] digest_0.6.18      
[37] foreign_0.8-70     
[38] rmarkdown_1.12     
[39] base64enc_0.1-3    
[40] jpeg_0.1-8.1       
[41] pkgconfig_2.0.2    
[42] htmltools_0.3.6    
[43] highr_0.8          
[44] dbplyr_1.4.0       
[45] htmlwidgets_1.3    
[46] rlang_0.4.6        
[47] readxl_1.3.1       
[48] rstudioapi_0.10    
[49] recosystem_0.4.3   
[50] generics_0.0.2     
[51] jsonlite_1.6       
[52] config_0.3         
[53] acepack_1.4.1      
[54] inline_0.3.15      
[55] RCurl_1.98-1.2     
[56] magrittr_1.5       
[57] loo_2.1.0          
[58] Rcpp_1.0.5         
[59] munsell_0.5.0      
[60] lifecycle_0.2.0    
[61] yaml_2.2.0         
[62] stringi_1.4.3      
[63] pkgbuild_1.0.3     
[64] parallel_3.6.0     
[65] crayon_1.3.4       
[66] haven_2.1.0        
[67] splines_3.6.0      
[68] hms_0.4.2          
[69] ps_1.3.0           
[70] pillar_1.4.4       
[71] stats4_3.6.0       
[72] glue_1.4.1         
[73] evaluate_0.13      
[74] latticeExtra_0.6-29
[75] modelr_0.1.4       
[76] png_0.1-7          
[77] vctrs_0.3.1        
[78] cellranger_1.1.0   
[79] openssl_1.3        
[80] gtable_0.3.0       
[81] assertthat_0.2.1   
[82] r2d3_0.2.3         
[83] xfun_0.6           
[84] broom_0.5.2        
[85] viridisLite_0.3.0  
[86] cluster_2.0.8      
[87] ellipsis_0.3.1

**Comment by SieSiongWong** [comment]
This issue resolved as I found that the df which some columns don't have name. It works now.
