### ISSUE TITLE
Can't load table or copy data when arrow is enabled

### ISSUE THREAD

**Issue by wangyuchen** [sparklyr/sparklyr#2604]
When the arrow package is loaded, sparklyr can't print Hive table headers (using `tbl`) or copy table to Spark cluster (using `copy_to`). I think the same error happens whenever sparklyr tries to engage arrow. 

Cluster HDP 2.6.1 with spark 2.1.1 in yarn client mode. 

See reprex below:
``` r
library(sparklyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
sc <- spark_connect(master = "yarn")


# copy a table to cluster
sdf_along(sc, 1:10) %>% 
  copy_to(sc, .)
#> # Source: spark<?> [?? x 1]
#>       id
#>    <int>
#>  1     1
#>  2     2
#>  3     3
#>  4     4
#>  5     5
#>  6     6
#>  7     7
#>  8     8
#>  9     9
#> 10    10


# read a hive table
tbl(sc, "nyse_stocks")
#> # Source: spark<nyse_stocks> [?? x 9]
#>    exch  stock_symbol date  stock_price_open stock_price_high stock_price_low
#>    <chr> <chr>        <chr> <chr>            <chr>            <chr>          
#>  1 NYSE  ASP          2001… 12.55            12.8             12.42          
#>  2 NYSE  ASP          2001… 12.5             12.55            12.42          
#>  3 NYSE  ASP          2001… 12.59            12.59            12.5           
#>  4 NYSE  ASP          2001… 12.45            12.6             12.45          
#>  5 NYSE  ASP          2001… 12.61            12.61            12.61          
#>  6 NYSE  ASP          2001… 12.4             12.78            12.4           
#>  7 NYSE  ASP          2001… 12.35            12.58            12.35          
#>  8 NYSE  ASP          2001… 12.42            12.6             12.35          
#>  9 NYSE  ASP          2001… 12.37            12.5             12.37          
#> 10 NYSE  ASP          2001… 12.4             12.52            12.4           
#> # … with more rows, and 3 more variables: stock_price_close <chr>,
#> #   stock_volume <chr>, stock_price_adj_close <chr>



library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp

arrow_available()
#> [1] TRUE


sdf_along(sc, 1:10) %>% 
  copy_to(sc, .)
#> Error: java.lang.IllegalArgumentException: invalid method sessionLocalTimeZone for object 110/org.apache.spark.sql.internal.SQLConf fields 0 selected 0
#>  at sparklyr.Invoke.invoke(invoke.scala:174)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
#>  at sparklyr.StreamHandler.read(stream.scala:61)
#>  at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:58)
#>  at scala.util.control.Breaks.breakable(Breaks.scala:38)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:38)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Thread.java:748)


tbl(sc, "nyse_stocks")
#> Error: java.lang.IllegalArgumentException: invalid method sessionLocalTimeZone for object 138/org.apache.spark.sql.internal.SQLConf fields 0 selected 0
#>  at sparklyr.Invoke.invoke(invoke.scala:174)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
#>  at sparklyr.StreamHandler.read(stream.scala:61)
#>  at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:58)
#>  at scala.util.control.Breaks.breakable(Breaks.scala:38)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:38)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Thread.java:748)
```

<sup>Created on 2020-07-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                                      
#>  version  R version 3.5.0 (2018-04-23)               
#>  os       Red Hat Enterprise Linux Server 7.7 (Maipo)
#>  system   x86_64, linux-gnu                          
#>  ui       X11                                        
#>  language (EN)                                       
#>  collate  en_US.UTF-8                                
#>  ctype    en_US.UTF-8                                
#>  tz       America/New_York                           
#>  date     2020-07-14                                 
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  arrow       * 0.17.1  2020-05-19 [1] RSPM (R 3.5.0)
#>  askpass       1.1     2019-01-13 [1] RSPM (R 3.5.0)
#>  assertthat    0.2.1   2019-03-21 [1] RSPM (R 3.5.0)
#>  backports     1.1.8   2020-06-17 [1] RSPM (R 3.5.0)
#>  base64enc     0.1-3   2015-07-28 [1] RSPM (R 3.5.0)
#>  bit           1.1-14  2018-05-29 [1] RSPM (R 3.5.0)
#>  bit64         0.9-7   2017-05-08 [1] RSPM (R 3.5.0)
#>  blob          1.2.1   2020-01-20 [1] RSPM (R 3.5.0)
#>  callr         3.3.2   2019-09-22 [1] RSPM (R 3.5.0)
#>  cli           2.0.2   2020-02-28 [1] RSPM (R 3.5.0)
#>  config        0.3     2018-03-27 [1] RSPM (R 3.5.0)
#>  crayon        1.3.4   2017-09-16 [1] RSPM (R 3.5.0)
#>  DBI           1.1.0   2019-12-15 [1] RSPM (R 3.5.0)
#>  dbplyr        1.4.4   2020-05-27 [1] RSPM (R 3.5.0)
#>  desc          1.2.0   2018-05-01 [1] RSPM (R 3.5.0)
#>  devtools      2.2.1   2019-09-24 [1] RSPM (R 3.5.0)
#>  digest        0.6.25  2020-02-23 [1] RSPM (R 3.5.0)
#>  dplyr       * 1.0.0   2020-05-29 [1] RSPM (R 3.5.0)
#>  ellipsis      0.3.1   2020-05-15 [1] RSPM (R 3.5.0)
#>  evaluate      0.14    2019-05-28 [1] RSPM (R 3.5.0)
#>  fansi         0.4.1   2020-01-08 [1] RSPM (R 3.5.0)
#>  forge         0.2.0   2019-02-26 [1] RSPM (R 3.5.0)
#>  fs            1.3.1   2019-05-06 [1] RSPM (R 3.5.0)
#>  generics      0.0.2   2018-11-29 [1] RSPM (R 3.5.0)
#>  glue          1.4.1   2020-05-13 [1] RSPM (R 3.5.0)
#>  highr         0.8     2019-03-20 [1] RSPM (R 3.5.0)
#>  htmltools     0.5.0   2020-06-16 [1] RSPM (R 3.5.0)
#>  htmlwidgets   1.5.1   2019-10-08 [1] RSPM (R 3.5.0)
#>  httr          1.4.1   2019-08-05 [1] RSPM (R 3.5.0)
#>  jsonlite      1.6.1   2020-02-02 [1] RSPM (R 3.5.0)
#>  knitr         1.27    2020-01-16 [1] RSPM (R 3.5.0)
#>  lifecycle     0.2.0   2020-03-06 [1] RSPM (R 3.5.0)
#>  magrittr      1.5     2014-11-22 [1] RSPM (R 3.5.0)
#>  memoise       1.1.0   2017-04-21 [1] RSPM (R 3.5.0)
#>  openssl       1.4.1   2019-07-18 [1] RSPM (R 3.5.0)
#>  pillar        1.4.4   2020-05-05 [1] RSPM (R 3.5.0)
#>  pkgbuild      1.0.6   2019-10-09 [1] RSPM (R 3.5.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] RSPM (R 3.5.0)
#>  pkgload       1.0.2   2018-10-29 [1] RSPM (R 3.5.0)
#>  prettyunits   1.0.2   2015-07-13 [1] RSPM (R 3.5.0)
#>  processx      3.4.1   2019-07-18 [1] RSPM (R 3.5.0)
#>  ps            1.3.0   2018-12-21 [1] RSPM (R 3.5.0)
#>  purrr         0.3.4   2020-04-17 [1] RSPM (R 3.5.0)
#>  r2d3          0.2.3   2018-12-18 [1] RSPM (R 3.5.0)
#>  R6            2.4.1   2019-11-12 [1] RSPM (R 3.5.0)
#>  Rcpp          1.0.4.6 2020-04-09 [1] RSPM (R 3.5.0)
#>  remotes       2.1.0   2019-06-24 [1] RSPM (R 3.5.0)
#>  rlang         0.4.6   2020-05-02 [1] RSPM (R 3.5.0)
#>  rmarkdown     2.3     2020-06-18 [1] RSPM (R 3.5.0)
#>  rprojroot     1.3-2   2018-01-03 [1] RSPM (R 3.5.0)
#>  rstudioapi    0.11    2020-02-07 [1] RSPM (R 3.5.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] RSPM (R 3.5.0)
#>  sparklyr    * 1.3.1   2020-07-09 [1] RSPM (R 3.5.0)
#>  stringi       1.4.6   2020-02-17 [1] RSPM (R 3.5.0)
#>  stringr       1.4.0   2019-02-10 [1] RSPM (R 3.5.0)
#>  testthat      2.3.1   2019-12-01 [1] RSPM (R 3.5.0)
#>  tibble        3.0.1   2020-04-20 [1] RSPM (R 3.5.0)
#>  tidyselect    1.1.0   2020-05-11 [1] RSPM (R 3.5.0)
#>  usethis       1.5.1   2019-07-04 [1] RSPM (R 3.5.0)
#>  utf8          1.1.4   2018-05-24 [1] RSPM (R 3.5.0)
#>  uuid          0.1-2   2015-07-28 [1] RSPM (R 3.5.0)
#>  vctrs         0.3.1   2020-06-05 [1] RSPM (R 3.5.0)
#>  withr         2.2.0   2020-04-20 [1] RSPM (R 3.5.0)
#>  xfun          0.12    2020-01-13 [1] RSPM (R 3.5.0)
#>  yaml          2.2.1   2020-02-01 [1] RSPM (R 3.5.0)
#> 
#> [1] /had/home/a377324/R/x86_64-pc-linux-gnu-library/3.5
#> [2] /opt/microsoft/ropen/3.5.0/lib64/R/library
```

</details>

**Comment by yl790** [comment]
@wangyuchen It looks like the lowest version of Spark that works with timezone semantic in latest version of Arrow is Spark 2.3.0.

I was able to run the following successfully:

```
library(sparklyr)

spark_install(version = "2.3.0")  # by default this will download Spark 2.3.0 into ~/spark/spark-2.3.0-bin-hadoop2.7
install.packages("arrow")

library(arrow)

arrow_available() # returns TRUE

sdf <- sdf_len(sc, 10)
print(sdf) # prints out content of a simple Spark dataframe
```

**Comment by wangyuchen** [comment]
Thanks @yl790 ! Installing 2.3.0 and run in local mode does work. However, the real usages is often in YARN mode and I'm stuck with 2.1.1 right now. Does the timezone semantic you mentioned an essential part for Arrow + sparklyr to work? Would there be a workaround if I install older version of Arrow? Given that my Spark version is fixed and I wanted to use the latest sparklyr, the only thing that I have control for is arrow.

**Comment by yitao-li** [comment]
Seems like the best we can do at the moment is supporting Arrow fully when Spark version is 2.3 or above.
