### ISSUE TITLE
Failure when using dplyr's across

### ISSUE THREAD

**Issue by konradzdeb** [sparklyr/sparklyr#2667]
Sparklyr fails to parse `dplyr` syntax that uses [`across`](https://dplyr.tidyverse.org/reference/across.html) function.

# Example
```r
# Settings
library("sparklyr", quietly = FALSE)
library("tidyverse", quietly = FALSE)

# spark_install(version = "2.1.0")
# Sys.setenv(JAVA_HOME = "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home")

sc <- spark_connect(master = "local")

copy_to(sc, mtcars)
tbl(sc, "mtcars") %>% transmute(across(c("cyl", "mpg"), ~ as.integer(.x) + 2))
```

## Error:

> Error in `UseMethod("escape")` : 
>   no applicable method for 'escape' applied to an object of class "formula"

# Desired results
```r
mtcars %>% transmute(across(c("cyl", "mpg"), ~ as.integer(.x) + 2))
#      cyl   mpg
# 1    8     23
# 2    8     23
# 3    6     24
```

--- 

# Session Info
```
utils::sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin19.5.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.10_1/lib/libopenblasp-r0.3.10.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.0   stringr_1.4.0   dplyr_1.0.1     purrr_0.3.4     readr_1.3.1     tidyr_1.1.1     tibble_3.0.3   
 [8] ggplot2_3.3.2   tidyverse_1.3.0 sparklyr_1.3.1 

loaded via a namespace (and not attached):
 [1] tinytex_0.25      tidyselect_1.1.0  xfun_0.16         forge_0.2.0       haven_2.3.1       colorspace_1.4-1 
 [7] vctrs_0.3.2       generics_0.0.2    htmltools_0.5.0   yaml_2.2.1        base64enc_0.1-3   utf8_1.1.4       
[13] blob_1.2.1        rlang_0.4.7       pillar_1.4.6      glue_1.4.1        withr_2.2.0       DBI_1.1.0        
[19] rappdirs_0.3.1    dbplyr_1.4.4      modelr_0.1.8      readxl_1.3.1      fortunes_1.5-4    lifecycle_0.2.0  
[25] munsell_0.5.0     gtable_0.3.0      cellranger_1.1.0  rvest_0.3.6       htmlwidgets_1.5.1 parallel_4.0.2   
[31] curl_4.3          fansi_0.4.1       broom_0.7.0       r2d3_0.2.3        Rcpp_1.0.5        openssl_1.4.2    
[37] backports_1.1.8   scales_1.1.1      jsonlite_1.7.0    config_0.3        fs_1.5.0          askpass_1.1      
[43] hms_0.5.3         digest_0.6.25     stringi_1.4.6     rprojroot_1.3-2   grid_4.0.2        cli_2.0.2        
[49] tools_4.0.2       magrittr_1.5      crayon_1.3.4      pkgconfig_2.0.3   ellipsis_0.3.1    xml2_1.3.2       
[55] reprex_0.3.0      lubridate_1.7.9   assertthat_0.2.1  httr_1.4.2        rstudioapi_0.11   R6_2.4.1         
[61] compiler_4.0.2 
```

**Comment by yitao-li** [comment]
@konradzdeb Thanks for reporting this bug!! I was running into this recently as well.
I believe some `dplyr`-related S3 methods in `sparklyr` need to be created or modified in order for this to work. The `across()`  method is a recent addition to `dplyr` so previous versions of `sparklyr` are not ready to work with `across()` yet.

**Comment by yitao-li** [comment]
@konradzdeb I'll aim to have the `across()` functionality as part of `sparklyr` 1.4 (assuming it's a non-complicated change to the dplyr interface of `sparklyr`).

Meanwhile if you just need to apply different aggregation functions to multiple columns in a Spark dataframe, you can use the following syntax:

```
library(sparklyr)
example_sdf <- tibble::tibble(id = seq(3), x = c(3, 1, 2), y = c(1, 3, 2)) %>%
  copy_to(sc, .)
example_sdf %>%
  dplyr::group_by(id) %>%
  dplyr::summarize(x = dplyr::sql("MAX(`x`)"), y = dplyr::sql("MAX(`y`)"))
```

(which is definitely not as nice as `dplyr::across()` which allows you to have `tidyselect(...)` expressions to select multiple columns, but it's sufficient for simple aggregations involving a small number of columns)

**Comment by yitao-li** [comment]
After looking into this a bit further, I think supporting `dplyr::across` would require some changes in `dbplyr`.

Reason: when one has a Spark dataframe (say, `sdf`) in `sparklyr` and runs `sdf %>% transmute(...)`, the S3 method dispatch turns that into a call to `dbplyr::transmute.tbl_lazy`, which performs some magic to translate the mutation into a SQL query.

**Comment by yitao-li** [comment]
Hmm was gonna file a `dbplyr` issue related to this and then saw there was already one filed: https://github.com/tidyverse/dbplyr/issues/491 :+1:

**Comment by yutannihilation** [comment]
`across()` seems to be implemented on dbplyr :tada: 

https://github.com/tidyverse/dbplyr/commit/84ecd65d04f9a72863831e559a1f9a56d6ecd186

**Comment by yitao-li** [comment]
Looks like `sparklyr` will get this for free, i.e., the following works after `remotes::install_github("tidyverse/dbplyr", ref = "master")`:

```
copy_to(sc, mtcars)
print(tbl(sc, "mtcars") %>% transmute(across(c("cyl", "mpg"), mean)))
```

Formula is not yet supported though, i.e.,
```
tbl(sc, "mtcars") %>% transmute(across(c("cyl", "mpg"), ~ as.integer(.x) + 2))
```
will fail with "Error: Unsupported `.fns` for dbplyr::across()"

**Comment by yitao-li** [comment]
Update: unfortunately `sparklyr` will actually not get it for free. However, after some changes, `across()` is now supported in the main branch of `sparklyr` now, so you can either run `sparklyr::install_github("sparklyr/sparklyr")` or wait for the next CRAN release of `sparklyr` in about 1 month to have the `across()` use cases working for Spark dataframes.

**Comment by yitao-li** [comment]
Hmm actually one more update: for `across()` on Spark dataframes, only functions (e.g., `grepl()`, `as.integer()`, etc) are supported by `sparklyr`. The formula syntax is not supported yet, but definitely worth looking into.

**Comment by saadaslam** [comment]
Is it possible to also add support for `ft_dplyr_transformer`?

**Comment by yitao-li** [comment]
@saadaslam `ft_dplyr_transformer()` runs `dbplyr` R-to-Spark-SQL translation internally, so, no additional change is needed for this to work with `ft_dplyr_transformer()`.

**Comment by billytcl** [comment]
Hi, I'm late to this issue, but can anyone comment on whether c_across() works in Sparklyr? I can't seem to get it to work. I'm on Sparklyr 1.7.5.

An example of what I'm trying to do:

```
  mat <- spark_read_csv(sc, name = "test", path = "[redacted]", delimiter="\t", null_value="NA", memory = F)

...
  mat_select <- mat %>% 
    select(c(1,2,3,sample_case,sample_control)) %>%
    group_by(chrom,start,end) %>%
    summarize(m.x=sum(c_across(sample_case-3), na.rm=T)/sum(!is.na(c_across(sample_case-3))),
              m.y=sum(c_across(sample_control-3), na.rm=T)/sum(!is.na(c_across(sample_control-3)))) %>%
    filter((m.x > 0 & m.y == 0) | (m.x == 0 & m.y > 0)) %>%
    mutate(class=ifelse(m.x>m.y,1,0), iteration=i)
```

With the warning message:

```
`summarise()` has grouped output by 'chrom', 'start'. You can override using the `.groups` argument.
Error: org.apache.spark.sql.AnalysisException: Undefined function: 'c_across'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 36
	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$25.$anonfun$applyOrElse$111(Analyzer.scala:2101)
	at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:60)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$25.applyOrElse(Analyzer.scala:2101)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$25.applyOrElse(Analyzer.scala:2091)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:486)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:595)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:486)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:486)
	at org.apache.spark.sql.catalyst.trees.BinaryLike.mapChildren(TreeNode.scala:1148)
	at org.apache.spark.sql.catalyst.trees.BinaryLike.mapChildren$(TreeNode.scala:1147)
	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.mapChildren(Expression.scala:555)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:486)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:486)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1122)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1121)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.mapChildren(Expression.scala:467)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:486)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$transformExpressionsDownWithPruning$1(QueryPlan.scala:152)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:193)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:193)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:204)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$3(QueryPlan.scala:209)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.immutable.List.map(List.scala:305)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:209)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$4(QueryPlan.scala:214)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:323)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:214)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsDownWithPruning(QueryPlan.scala:152)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsWithPruning(QueryPlan.scala:123)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$$anonfun$resolveExpressionsWithPruning$1.applyOrElse(AnalysisHelper.scala:245)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$$anonfun$resolveExpressionsWithPruning$1.applyOrElse(AnalysisHelper.scala:244)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:170)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:170)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:99)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:96)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveExpressionsWithPruning(AnalysisHelper.scala:244)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveExpressionsWithPruning$(AnalysisHelper.scala:242)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveExpressionsWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$.apply(Analyzer.scala:2091)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$.apply(Analyzer.scala:2088)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:211)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:208)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:200)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:200)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:222)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:218)
	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:167)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:218)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:182)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:179)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:179)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:203)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:202)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.sc
In addition: Warning message:
Missing values are always removed in SQL.
Use `SUM(x, na.rm = TRUE)` to silence this warning
This warning is displayed only once per session. 
```
