### ISSUE TITLE
sd with na.rm causes error when used in summarize

### ISSUE THREAD

**Issue by pf981** [sparklyr/sparklyr#2756]
`sd(x, na.rm = TRUE)` causes an error when used inside `summarize`.
```r
library(sparklyr)

sc <- spark_connect(master = "local", version = "3.0.0")

stats <- data.frame(x = 1:10, y = 10:1)
stats_tbl <- copy_to(sc, stats, overwrite = TRUE)

dplyr::summarize(stats_tbl, sd = sd(x, na.rm = TRUE))
```

```
Error: org.apache.spark.sql.catalyst.parser.ParseException: 
mismatched input 'AS' expecting {')', ',', '-'}(line 1, pos 29)

== SQL ==
SELECT stddev_samp(`x`, TRUE AS `na.rm`) AS `sd`
-----------------------------^^^
FROM `stats`

	at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:266)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:133)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:81)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:604)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:604)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:763)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:601)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:39)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
In addition: Warning message:
Named arguments ignored for SQL stddev_samp 
```

There is no error when used with `mutate`.
```r
dplyr::mutate(stats_tbl, sd = sd(x, na.rm = TRUE))
#> # Source: spark<?> [?? x 3]
#>        x     y    sd
#>    <int> <int> <dbl>
#>  1     1    10  3.03
#>  2     2     9  3.03
#>  3     3     8  3.03
#>  4     4     7  3.03
#>  5     5     6  3.03
#>  6     6     5  3.03
#>  7     7     4  3.03
#>  8     8     3  3.03
#>  9     9     2  3.03
#> 10    10     1  3.03
```

Or when used without `na.rm = TRUE`
```r
dplyr::summarize(stats_tbl, sd = sd(x))
#> # Source: spark<?> [?? x 1]
#>      sd
#>   <dbl>
#> 1  3.03
```

```r
utils::sessionInfo()
```

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] sparklyr_1.4.0

loaded via a namespace (and not attached):
 [1] pillar_1.4.6      compiler_4.0.2    dbplyr_1.4.4     
 [4] r2d3_0.2.3        base64enc_0.1-3   tools_4.0.2      
 [7] digest_0.6.25     jsonlite_1.7.1    evaluate_0.14    
[10] lifecycle_0.2.0   tibble_3.0.4      pkgconfig_2.0.3  
[13] rlang_0.4.8       cli_2.1.0         DBI_1.1.0        
[16] rstudioapi_0.11   yaml_2.2.1        parallel_4.0.2   
[19] xfun_0.18         withr_2.3.0       httr_1.4.2       
[22] stringr_1.4.0     dplyr_1.0.2.9000  knitr_1.30       
[25] generics_0.0.2    htmlwidgets_1.5.2 vctrs_0.3.4      
[28] askpass_1.1       rappdirs_0.3.1    rprojroot_1.3-2  
[31] tidyselect_1.1.0  glue_1.4.2        forge_0.2.0      
[34] R6_2.4.1          fansi_0.4.1       rmarkdown_2.4    
[37] purrr_0.3.4       tidyr_1.1.2       blob_1.2.1       
[40] magrittr_1.5      backports_1.1.10  ellipsis_0.3.1   
[43] htmltools_0.5.0   assertthat_0.2.1  config_0.3       
[46] utf8_1.1.4        stringi_1.5.3     openssl_1.4.3    
[49] crayon_1.3.4   
```

**Comment by yitao-li** [comment]
@pf981 Duly noted. At the moment `sparklyr` is using `dbplyr` to translate `dplyr` grammar into Spark SQL (see https://github.com/sparklyr/sparklyr/blob/main/R/dplyr_spark_connection.R#L185) -- while that interface approximately matches what `dplyr` has for R dataframes, there is no guarantee that both interfaces will be 100% identical.

Please also notice `sparklyr` is translating `sd(...)` into `stddev_samp(...)` in Spark SQL, the latter of which ignore null values already (e.g., you can try running this query to see it indeed does so:

```
sc <- spark_connect(...)
DBI::dbGetQuery(sc, "SELECT STDDEV_SAMP(col) FROM VALUES (1), (NULL), (3) AS tab(col);")
```
