### ISSUE TITLE
Error using distinct as intermediate step

### ISSUE THREAD

**Issue by tschutte** [sparklyr/sparklyr#2847]
It appears the new `distinct` function included in sparklyr 1.5.0 no longer allows additional processing on the resulting dataframe if the function is included in the middle of a processing pipeline.

When running additional dplyr operations against the result, the below Spark error is thrown.  I'm trying to determine if this change is intentional or if this is a new bug.  

Additionally, using the distinct function always throws Warnings regarding the usage of "ORDER BY", I assume due to recent changes in dplyr/dbplyr.

```r
library(dplyr)
library(sparklyr)

sc <- sparklyr::spark_connect(master = "local", version = "2.4.5")

df <- tibble::tibble(
  x = c(1, 1, 1, 1, 1),
  y = c(1, 1, 2, 2, 1),
  z = c(1, 2, 1, 2, 1)
)

sdf <- copy_to(sc, df, name = sparklyr::random_string("tmp"))

sdf %>% distinct() %>% mutate(r = 1)
sdf %>% distinct() %>% left_join(., sdf, by = c("x"))

```
Error: org.apache.spark.sql.AnalysisException: cannot resolve '`__row_num_1b0e27d7_efa9_4aea_b83d_e9fc2f016df3`' given input columns: [q03.x, q03.y, q03.z]; line 1 pos 22;
'Project [x#82, y#83, z#84, '__row_num_1b0e27d7_efa9_4aea_b83d_e9fc2f016df3, 1.0 AS r#85]
+- SubqueryAlias `q03`
   +- Project [x#82, y#83, z#84]
      +- SubqueryAlias `q02`
         +- Aggregate [x#8, y#9, z#10], [first(__row_num_1b0e27d7_efa9_4aea_b83d_e9fc2f016df3#80, false) AS __row_num_1b0e27d7_efa9_4aea_b83d_e9fc2f016df3#81, first(x#8, false) AS x#82, first(y#9, false) AS y#83, first(z#10, false) AS z#84]
            +- SubqueryAlias `q01`
               +- Project [x#8, y#9, z#10, __row_num_1b0e27d7_efa9_4aea_b83d_e9fc2f016df3#80]
                  +- Project [x#8, y#9, z#10, __row_num_1b0e27d7_efa9_4aea_b83d_e9fc2f016df3#80, __row_num_1b0e27d7_efa9_4aea_b83d_e9fc2f016df3#80]
                     +- Window [row_number() windowspecdefinition(null ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) AS __row_num_1b0e27d7_efa9_4aea_b83d_e9fc2f016df3#80], [null ASC NULLS FIRST]
                        +- Project [x#8, y#9, z#10]
                           +- SubqueryAlias `tmp_ff21169f_2690_4a38_953e_6cf84e11402c`
                              +- LogicalRDD [x#8, y#9, z#10], false

	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:111)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:108)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:280)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:280)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:279)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:93)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:93)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:105)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:105)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:104)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:116)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$2.apply(QueryPlan.scala:121)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:121)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$2.apply(QueryPlan.scala:126)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:126)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:93)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:108)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:86)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:86)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:95)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:108)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:105)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:105)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:56)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:48)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:78)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at sparklyr.BackendHandler.channelRead0(handler.scala:38)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.ru
In addition: Warning messages:
1: ORDER BY is ignored in subqueries without LIMIT
ℹ Do you need to move arrange() later in the pipeline or use window_order() instead? 
2: ORDER BY is ignored in subqueries without LIMIT
ℹ Do you need to move arrange() later in the pipeline or use window_order() instead? 

### Session Info 
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Amazon Linux 2

Matrix products: default
BLAS:   /opt/R/3.6.3/lib64/R/lib/libRblas.so
LAPACK: /opt/R/3.6.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.5.1 dplyr_1.0.2   

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    rappdirs_0.3.1    uuid_0.1-4        tidyselect_1.1.0  R6_2.5.0          rlang_0.4.9      
 [8] fansi_0.4.1       httr_1.4.2        tools_3.6.3       parallel_3.6.3    config_0.3        cli_2.2.0         DBI_1.1.0        
[15] withr_2.3.0       dbplyr_2.0.0      askpass_1.1       htmltools_0.5.0   ellipsis_0.3.1    openssl_1.4.3     yaml_2.2.1       
[22] rprojroot_2.0.2   assertthat_0.2.1  digest_0.6.27     tibble_3.0.4      lifecycle_0.2.0   forge_0.2.0       crayon_1.3.4     
[29] tidyr_1.1.2       purrr_0.3.4       base64enc_0.1-3   htmlwidgets_1.5.2 vctrs_0.3.5       glue_1.4.2        compiler_3.6.3   
[36] pillar_1.4.7      r2d3_0.2.3        generics_0.1.0    jsonlite_1.7.1    pkgconfig_2.0.3

**Comment by yitao-li** [comment]
@tschutte Good catch! I will try to send a hot-fixed version of `sparklyr` to CRAN (and I don't know what the response from CRAN will be for frequent updates on packages...)

Meanwhile you can run `remotes::install_github("yitao-li/sparklyr", ref = "dplyr_distinct_bug_fix")` to install the fixed version.

**Comment by tschutte** [comment]
Thank you @yitao-li !
