### ISSUE TITLE
Error using spark_apply on Kubernetes clusters

### ISSUE THREAD

**Issue by ZackBarry** [sparklyr/sparklyr#2888]
I have a Docker image built via Spark's docker build tool with the addition of the sparklyr JARs. Spark 3.0.1, Hadoop 2.7, sparklyr 1.5.2. I'm able to use this image to connect to a Kubernetes cluster, but I can't use `spark_apply`:

```r
master = "https://<my-ip>:443"
image = "<my-image>"
account = "spark"  # k8s service account
driver = "spark-driver-r"

config <- spark_config_kubernetes(
  master = master,
  image = image,
  account = account,
  driver = driver,
  ports = c(8880, 8881, 4040),
  version = '3.0.1'
)

config["spark.kubernetes.file.upload.path"] <- "file:///tmp"
config["spark_home"] <- "/local/path/to/spark-3.0.1-bin-hadoop2.7"
config["sparklyr.app.jar"] <- "local:///opt/sparklyr/sparklyr-3.0-2.12.jar"

sc <- spark_connect(config = config, spark_home = "/local/path/to/spark-3.0.1-bin-hadoop2.7")

temp <- sdf_len(sc, 3)

# I can print temp and it is returned as expected

temp %>%
    spark_apply(function(df) I(df))

ERROR sparklyr: Gateway (29438) failed calling addFile on 11: java.io.FileNotFoundException: File file:/var/folders/jf/lqnngxkj0x75cdmv_xjygfq40000gq/T/RtmpfBxKfX/packages/packages.29438.tar does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:611)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:824)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:601)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:428)
	at org.apache.spark.SparkContext.addFile(SparkContext.scala:1534)
	at org.apache.spark.SparkContext.addFile(SparkContext.scala:1498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:39)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
Neither of the executor pods report any new logs after `spark_apply` is called; only the driver has the error listed above.

Since `I()` is a base R function, I'm assuming I don't need to have anything other than base R installed in the image? In general, if I use spark apply to apply a function from a CRAN package does that package need to be installed on the image in a special way? Or does it only need to be installed on the machine I'm connecting from?

Here is the head of my driver logs:
```
++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/bash
+ set -e
+ '[' -z root:x:0:0:root:/root:/bin/bash ']'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
+ readarray -t SPARK_EXECUTOR_JAVA_OPTS
+ '[' -n '' ']'
+ '[' '' == 2 ']'
+ '[' '' == 3 ']'
+ '[' -n '' ']'
+ '[' -z ']'
+ case "$1" in
+ shift 1
+ CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
+ exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.40.1.7 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class sparklyr.Shell local:///opt/sparklyr/sparklyr-3.0-2.12.jar 8880 29438 --remote
21/01/12 17:41:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/01/12 17:41:40 INFO sparklyr: Session (29438) is starting under 127.0.0.1 port 8880
21/01/12 17:41:40 INFO sparklyr: Session (29438) is configuring for remote connections
21/01/12 17:41:40 INFO sparklyr: Session (29438) found port 8880 is available
21/01/12 17:41:40 INFO sparklyr: Gateway (29438) is waiting for sparklyr client to connect to port 8880
21/01/12 17:41:40 WARN sparklyr: Gateway (29438) Failed to get network interface of gateway server socketnull
21/01/12 17:42:34 INFO sparklyr: Gateway (29438) accepted connection
21/01/12 17:42:34 INFO sparklyr: Gateway (29438) is waiting for sparklyr client to connect to port 8880
21/01/12 17:42:34 WARN sparklyr: Gateway (29438) Failed to get network interface of gateway server socketnull
21/01/12 17:42:34 INFO sparklyr: Gateway (29438) received command 0
21/01/12 17:42:34 INFO sparklyr: Gateway (29438) found requested session matches current session
21/01/12 17:42:34 INFO sparklyr: Gateway (29438) is creating backend and allocating system resources
21/01/12 17:42:34 INFO sparklyr: Gateway (29438) is using port 8881 for backend channel
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
21/01/12 17:42:34 INFO sparklyr: Gateway (29438) created the backend
21/01/12 17:42:34 INFO sparklyr: Gateway (29438) is waiting for r process to end
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/01/12 17:42:35 INFO SparkContext: Running Spark version 3.0.1
21/01/12 17:42:35 INFO ResourceUtils: ==============================================================
21/01/12 17:42:35 INFO ResourceUtils: Resources for spark.driver:

21/01/12 17:42:35 INFO ResourceUtils: ==============================================================
21/01/12 17:42:35 INFO SparkContext: Submitted application: sparklyr
```

**Comment by ZackBarry** [comment]
@yitao-li sorry to ping you, but do you have insight on this? totally blocked at the moment

**Comment by yitao-li** [comment]
@ZackBarry You can try `tmp %>% spark_apply(<function>, packages = FALSE)` if only base-R functions are used by <function>

**Comment by ZackBarry** [comment]
Thanks for the tip! That worked for me. In case this is helpful to others, I was also able to use `spark_apply()` with a function from a CRAN library. To do this I added an install command to my Dockerfile:
```
RUN R -e "install.packages('CranPackage', repos = c(CRAN = 'https://cran.rstudio.com'))"
```
Looking at the logs from the image build, this was installed to `/usr/local/lib/R/site-library`. So I specified that in my config:
```
config <- spark_config_kubernetes(
  master = master,
  image = image,
  account = account,
  driver = driver,
  ports = c(8880, 8881, 4040),
  version = '3.0.1'
)
config["spark.r.libpaths"] <- "local:///usr/local/lib/R/site-library"
```
Then `spark_apply()` could use the package:
```
df <- sdf_len(sc, 5)
spark_apply(
    df,
    function(df) CranPackage::cran_function(df),
    packages = FALSE
```
