### ISSUE TITLE
All Applications Return Exit Code 1

### ISSUE THREAD

**Issue by jj-ookla** [sparklyr/sparklyr#2950]
All sparklyr apps submitted via cli using batch mode are returning exit code 1 regardless of completing successfully. I have encountered this issue on both EMR 6 and Kubernetes (EKS). This includes test jobs (modified from the handy [benchmarks](https://github.com/yitao-li/sparklyr-pyspark-benchmarks/tree/master/sparklyr_spark_apply_benchmark) scripts) without dependencies. After running `spark-submit`, the return code can be retrieved using `echo $?`.

```r
spark_version <- "3.0.0"

# test code without dependencies:
n <- 100
df <- data.frame(lapply(seq(10), function(c) sapply(runif(n = n, min = -2147483648, max = 2147483647), as.integer)))
colnames(df) <- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J")
sdf <- sdf_copy_to(sc, df, overwrite = TRUE)
tdf <- sdf_collect(sdf)
```

**Example EMR command:**

```
spark-submit \
    --master yarn \
    --deploy-mode client \
    --driver-memory 3G \
    --executor-memory 2G \
    --conf spark.executor.instances=1 \
    --conf spark.dynamicAllocation.enabled=true \
    --conf spark.dynamicAllocation.initialExecutors=1 \
    --conf spark.dynamicAllocation.minExecutors=1 \
    --conf spark.dynamicAllocation.maxExecutors=2 \
    --conf spark.r.command="/opt/R/4.0.3/bin/Rscript" \
    --conf spark.r.libpaths="/opt/R/4.0.3/lib64/R/library" \
    --class sparklyr.Shell "/opt/R/4.0.3/lib64/R/library/sparklyr/java/sparklyr-3.0-2.12.jar" 8880 1234 \
    --files test_sparklyr.R \
    --batch test_sparklyr.R
```

---

My best guess is that the expected `SocketException` is somehow passed through to the driver. Log output from the end of a completed job (writes results to s3 and verified to be complete):

```
21/02/26 21:48:55 INFO FileFormatWriter: Finished processing stats for write job c098c69a-6942-4ec5-b81b-06bd11a27b1a.
(21/02/26 21:48:55 INFO sparklyr: Gateway (7030) is shutting down with expected SocketException,java.net.SocketException: Socket closed)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
21/02/26 21:48:55 INFO sparklyr: Gateway (7030) is terminating backend
21/02/26 21:48:55 INFO SparkContext: Invoking stop() from shutdown hook
21/02/26 21:48:55 INFO sparklyr: Gateway (7030) completed R process
21/02/26 21:48:55 INFO SparkUI: Stopped Spark web UI at http://spark-c9284077e04b61c7-driver-svc.spark-apps.svc:4040
21/02/26 21:48:55 INFO KubernetesClusterSchedulerBackend: Shutting down all executors
21/02/26 21:48:55 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Asking each executor to shut down
21/02/26 21:48:55 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed (this is expected if the application is shutting down.)
21/02/26 21:48:55 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/02/26 21:48:55 INFO MemoryStore: MemoryStore cleared
21/02/26 21:48:55 INFO BlockManager: BlockManager stopped
21/02/26 21:48:55 INFO BlockManagerMaster: BlockManagerMaster stopped
21/02/26 21:48:55 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/02/26 21:48:55 INFO SparkContext: Successfully stopped SparkContext
21/02/26 21:48:55 INFO ShutdownHookManager: Shutdown hook called
21/02/26 21:48:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-local-dir-dm/spark-c7204019-18fc-415a-a21c-752adb7022a0
21/02/26 21:48:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-e4f7439d-ceae-4835-aa10-7f597d81c67a
21/02/26 21:48:55 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
21/02/26 21:48:55 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
21/02/26 21:48:55 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
```

**Comment by yitao-li** [comment]
:open_mouth: Oh no it looks like someone has copy-pasted some `System.exit(1)` statement from one place to another but it should have been `System.exit(0)`
