### ISSUE TITLE
Multiple notebook cannot be run by the same user on databricks (probably due to package.-guid-.tar name)

### ISSUE THREAD

**Issue by robin-loche** [sparklyr/sparklyr#2954]
We have a workflow where we execute multiple R notebook one after another on databricks (on a permanent cluster, job cluster is not possible due to corporate rules), and it's not possible to do so without restarting the cluster between 2 notebook.

The error appears when one of the notebook uses spark_apply, the following notebook fails, sometimes even if it does not uses spark_apply.

The error is the following:

```
Error : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1784.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1784.0 (TID 19041, 10.139.64.26, executor 2): org.apache.spark.SparkException: Failed to fetch spark://10.139.64.6:36467/files/packages.251a2b18-7a93-11eb-982d-00163e7af4e9.tar during dependency update Error : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1784.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1784.0 (TID 19041, 10.139.64.26, executor 2): org.apache.spark.SparkException: Failed to fetch spark://10.139.64.6:36467/files/packages.251a2b18-7a93-11eb-982d-00163e7af4e9.tar during dependency update
	at org.apache.spark.executor.Executor.$anonfun$updateDependencies$4(Executor.scala:1109)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
	at org.apache.spark.executor.Executor.updateDependencies(Executor.scala:1100)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:583)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Stream '/files/packages.251a2b18-7a93-11eb-982d-00163e7af4e9.tar' was not found.
	at org.apache.spark.network.client.TransportResponseHandler.handle(TransportResponseHandler.java:242)
	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:142)
	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:53)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.apache.spark.network.util.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2519)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2466)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2460)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2460)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1152)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1152)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1152)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2721)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2668)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2656)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
Caused by: org.apache.spark.SparkException: Failed to fetch spark://10.139.64.6:36467/files/packages.251a2b18-7a93-11eb-982d-00163e7af4e9.tar during dependency update
	at org.apache.spark.executor.Executor.$anonfun$updateDependencies$4(Executor.scala:1109)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
	at org.apache.spark.executor.Executor.updateDependencies(Executor.scala:1100)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:583)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Stream '/files/packages.251a2b18-7a93-11eb-982d-00163e7af4e9.tar' was not found.
	at org.apache.spark.network.client.TransportResponseHandler.handle(TransportResponseHandler.java:242)
	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:142)
	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:53)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.nett
...
```

```r
print(.libPaths())
print(sessionInfo())
print(version)


[1] "/databricks/spark/R/lib"       "/usr/local/lib/R/site-library"
[3] "/usr/lib/R/site-library"       "/usr/lib/R/library"           
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] arrow_3.0.0     sparklyr_1.5.2  DBI_1.1.0       forcats_0.5.0  
 [5] stringr_1.4.0   purrr_0.3.4     readr_1.3.1     tidyr_1.1.0    
 [9] tibble_3.0.3    ggplot2_3.3.2   tidyverse_1.3.0 dplyr_1.0.4    

loaded via a namespace (and not attached):
 [1] hwriterPlus_1.0-3  tidyselect_1.1.0   forge_0.2.0        haven_2.3.1       
 [5] colorspace_1.4-1   vctrs_0.3.6        generics_0.0.2     htmltools_0.5.0   
 [9] base64enc_0.1-3    blob_1.2.1         SparkR_3.0.0       rlang_0.4.10      
[13] pillar_1.4.6       glue_1.4.1         withr_2.2.0        Rserve_1.8-7      
[17] bit64_0.9-7        dbplyr_1.4.4       modelr_0.1.8       readxl_1.3.1      
[21] lifecycle_0.2.0    munsell_0.5.0      gtable_0.3.0       cellranger_1.1.0  
[25] hwriter_1.3.2      rvest_0.3.5        htmlwidgets_1.5.1  fansi_0.4.1       
[29] broom_0.7.0        r2d3_0.2.3         Rcpp_1.0.5         scales_1.1.1      
[33] backports_1.1.8    jsonlite_1.7.0     bit_1.1-15.2       fs_1.4.2          
[37] TeachingDemos_2.10 hms_0.5.3          digest_0.6.25      stringi_1.4.6     
[41] grid_3.6.3         rprojroot_1.3-2    cli_2.0.2          tools_3.6.3       
[45] magrittr_1.5       crayon_1.3.4       pkgconfig_2.0.3    ellipsis_0.3.1    
[49] xml2_1.3.2         reprex_0.3.0       lubridate_1.7.9    assertthat_0.2.1  
[53] httr_1.4.1         rstudioapi_0.11    R6_2.5.0           compiler_3.6.3    
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock        
```

It's something that is quite painfull to handle in production (restart is tricky, and a lot time is lost) and can make it impossible to have a good notebook workflows. Plus it's also painfull when developping on multiple notebooks, that need a cluster each or a lot of restarts.

The error seems to be like https://github.com/sparklyr/sparklyr/issues/2244

To reproduce, you need 2 notebook on databricks. The cluster need to have multiple nodes and the computation needs to be long enough so the nodes can launch and execute code. For exemple, with the demo dataset:

```r
require(tidyverse)
require(sparklyr)
sc <- spark_connect(method="databricks")
dfs <- spark_read_csv(sc, "/databricks-datasets/COVID/coronavirusdataset/SeoulFloating.csv")
dfs %>% sdf_repartition(partition_by="city") %>% spark_apply(function(x){require(dplyr); x %>% group_by(date) %>% summarise(nb=n())})
dbutils.notebook.exit("")
```

Execute the first, wait until it's done, then the second (on the same cluster without restart), and there should be the error. I tested it while adding "require(broom)" in the second notebook because I though it could be linked to the loaded packages but I don't think it's necessary actually.

My hypothesis is that having a different name for each session seems not enough. I don't know exactly how databricks notebooks works, but I think they have independant R session but with the same GUID.

Maybe it's possible to add another unique identifiant to the name ? (timestamp, hash of the path of the script, ...) Or is there any other workaround (job cluster is not possible due to corporate rules) ?

**Comment by robin-loche** [comment]
I think I've finally found a workaround (I have this problem from months):

1. Create an init script for your cluster that install your packages. If possible prepare them from the source tar in binary with ```devtools::build``` with ```binary=TRUE``` (see script below) and in your script install them from the binary instead of the repos, because in can be quite long to install packages and slow down your cluster when resizing.
2. When using spark_apply, add the option "packages=FALSE"

This way it doesn't copy the packages in a tar file so there is no conflicts. It should also be quicker.

That's still a workaround, and other people can fall in the trap easily. Also if you miss the parameter in one of your script your whole processing chain could fail and you can spend a lot a time finding the problem (that's what I did).

I put the file that I use to generate the init script for the cluster, and that automatically download and compile the given packages:

[Create_init_script_7.3.r.zip](https://github.com/sparklyr/sparklyr/files/6078407/Create_init_script_7.3.r.zip)

Maybe that can help someone else.

**Comment by yitao-li** [comment]
@robin-loche I think this is likely a case where a Databricks cluster has some special cluster topology such that the usual R package distribution mechanism in https://github.com/sparklyr/sparklyr/blob/c00bb732487dd2be19dda38e118ba79473e76158/R/spark_apply_bundle.R#L140 simply didn't work.

I think it's best to leave this for Databricks folks to figure out.
