### ISSUE TITLE
Strange behaviour of sparklyr::invoke() with Kudu

### ISSUE THREAD

**Issue by Frizz783** [sparklyr/sparklyr#2957]
Hi all,

I'm trying to write some data from Spark into a Kudu Table via sparklyr.

```r
library(sparklyr)

conf = spark_config()
conf$`sparklyr.shell.driver-class-path` = "/path/to/kudu-spark2_2.11.jar"
conf$`sparklyr.shell.jars` = "/path/to/kudu-spark2_2.11.jar"
sc = spark_connect(master = "yarn-client", 
                   spark_home = "/my/spark/home", 
                   app_name = "test",
                   config = conf)
kudu_master = "my.kudu.master"
sc$kudu_context = invoke_new(sc,"org.apache.kudu.spark.kudu.KuduContext",kudu_master,spark_context(sc))
sc$kudu_master = kudu_master

read_kudu_table = function(sc, kudu_table){
  ss = spark_session(sc)
  kudu_master = sc$kudu_master
  df = ss %>%
    invoke("read") %>%
    invoke("format","org.apache.kudu.spark.kudu") %>%
    invoke("option","kudu.master",kudu_master) %>%
    invoke("option","kudu.table",kudu_table) %>%
    invoke("load")
  return(df)
}
a = read_kudu_table(sc,'dev.tableKudu')
a 
# <jobj[27]>
# org.apache.spark.sql.Dataset
# ...
# works fine

kudu_table_exists = function(sc,kudu_table){
  resp = sc$kudu_context %>% invoke("tableExists", kudu_table)
  return(resp)
}
kudu_table_exists(sc,'dev.tableKudu') 
# [1] TRUE
# works fine

kudu_upsert_rows = function(sc,df,kudu_table){
  resp = sc$kudu_context %>% invoke("upsertRows", df, kudu_table)
  return(resp)
}
kudu_upsert_rows(sc,a,'dev.tableKudu')
# Error: java.lang.Exception: No matched method found for class org.apache.kudu.spark.kudu.KuduContext.upsertRows
# 	  at sparklyr.Invoke.invoke(invoke.scala:144)
# 	  at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
# 	  at sparklyr.StreamHandler.read(stream.scala:66)
# 	  at sparklyr.BackendHandler.channelRead0(handler.scala:51)
# 	  at sparklyr.BackendHandler.channelRead0(handler.scala:4)
# 	  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
# 	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
# 	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
# 	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
# 	  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
# 	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
# 	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
# 	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
# 	  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
# 	  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
# 	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
# 	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
# 	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
# 	  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
# 	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
# 	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
# 	  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
# 	  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
# 	  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
# 	  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
# 	  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
# 	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
# 	  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
# 	  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
# 	  at java.lang.Thread.run(Thread.java:748)
```

If I try to write the same thing in the Scala language (via spark-shell) everything works
```scala
import org.apache.kudu.spark.kudu._
val kuduContext = new KuduContext("my.kudu.master", spark.sparkContext)
val spTable = spark.read.options(Map("kudu.master" -> "my.kudu.master", "kudu.table" -> "dev.tableKudu")).format("kudu").load
kuduContext.upsertRows(spTable, "dev.tableKudu")
```

I have already checked the code in the kudusparklyr package (no longer supported and not working), the kudu-spark2 package documentation on github and also the invoke related issues here, but nothing has changed.

Thanks for the support 😄

**Comment by yitao-li** [comment]
@Frizz783 Someone else has complained this to me before as well.

The error is because `kudusparklyr` is not exactly designed to be compatbile with multiple versions of the kudu library, and you happened to have picked a version of that library that contains some incompatible API method signatures. I think the best thing to do here is to either modify `kudusparklyr` or even create your own fork of `kudusparklyr` with your changes on top, and make it compatible with multiple versions of the kudu library.

In particular, I noticed https://github.com/cloudera/kudu/blob/ccdb6b557d440423843952cace3e7d351a743fa6/java/kudu-spark/src/main/scala/org/apache/kudu/spark/kudu/KuduContext.scala#L236 where the `upsertRows()` method actually needs 3 parameters. Default parameter value is not supported by `sparklyr` invoke yet unfortunately, so you'd have to supply the 3rd parameter (presumably by calling `invoke_new(sc, "org.apache.kudu.spark.kudu.KuduWriteOptions")` or similar.

**Comment by yitao-li** [comment]
PS: there is a wish-list item of making default params work with `sparklyr::invoke()` -- see https://github.com/sparklyr/sparklyr/issues/940
It's not clear whether there is a good way to actually accomplish that through Java/Scala reflection yet. Suggestions are welcome.

**Comment by Frizz783** [comment]
@yitao-li thank you very much for the reply.

> Default parameter value is not supported by sparklyr invoke yet 

was what I was missing and therefore the cause of the problems ( both `invoke("upsertRows", df, kudu_table)` and `invoke_new(sc, "org.apache.kudu.spark.kudu.KuduWriteOptions")`).

Here is my working code
```r
library(sparklyr)

conf = spark_config()
conf$`sparklyr.shell.driver-class-path` = "/path/to/kudu-spark2_2.11.jar"
conf$`sparklyr.shell.jars` = "/path/to/kudu-spark2_2.11.jar"
sc = spark_connect(master = "yarn-client", 
                   spark_home = "/my/spark/home", 
                   app_name = "test",
                   config = conf)
kudu_master = "my.kudu.master"
sc$kudu_context = invoke_new(sc,"org.apache.kudu.spark.kudu.KuduContext",kudu_master,spark_context(sc))
sc$kudu_master = kudu_master

read_kudu_table = function(sc, kudu_table){
  ss = spark_session(sc)
  kudu_master = sc$kudu_master
  df = ss %>%
    invoke("read") %>%
    invoke("format","org.apache.kudu.spark.kudu") %>%
    invoke("option","kudu.master",kudu_master) %>%
    invoke("option","kudu.table",kudu_table) %>%
    invoke("load")
  return(df)
}
t1 = read_kudu_table(sc,'dev.tableKudu')

kudu_write_options = function(sc, ignoreDuplicateRowErrors = FALSE, ignoreNull = FALSE, repartition = FALSE, repartitionSort = TRUE){
  resp = sc %>% invoke_new("org.apache.kudu.spark.kudu.KuduWriteOptions", ignoreDuplicateRowErrors, ignoreNull, repartition, repartitionSort)
  return(resp)
}
wo = kudu_write_options(sc)

kudu_upsert_rows = function(sc,df,kudu_table,writeoptions){
  resp = sc$kudu_context %>% invoke("upsertRows", df, kudu_table, writeoptions)
  return(resp)
}
kudu_upsert_rows(sc,t1,'dev.tableKudu',wo)

#note
#if t1 is a tbl_spark, use spark_dataframe(t1) in order to have a jobj
```

useful links
#2830
bkvarda/kudusparklyr#10
[kudu](https://github.com/apache/kudu/tree/4abb4eae4375fd25fa21c5a4469937cca4795672/java/kudu-spark/src/main/scala/org/apache/kudu/spark/kudu)
