### ISSUE TITLE
Error Adding Config spark.sql.pivotMaxValues on Sparklyr

### ISSUE THREAD

**Issue by Vanderser** [sparklyr/sparklyr#2997]
I want to change spark.sql.pivotMaxValues limit to 50000, since I need to do crosstab/pivot with movie_rating datasets that have 240K Users Unique and 44K Movies Unique, But Theres an error limitation occurs if it happens to crosstab more than 10K unique Columns using `sdf.crosstab()` or `sdf.pivot()` But after I add this to config, spark connection refused to connect

Output of my utils:sessionInfo()

    > utils::sessionInfo()
    R version 4.0.3 (2020-10-10)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1
    
    Matrix products: default
    
    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    
    system code page: 932
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] sparklyr_1.6.2 config_0.3.1  
    
    loaded via a namespace (and not attached):
     [1] Rcpp_1.0.5        lattice_0.20-41   forge_0.2.0       tidyr_1.1.2       prettyunits_1.1.1 ps_1.5.0         
     [7] assertthat_0.2.1  rprojroot_2.0.2   digest_0.6.27     R6_2.5.0          backports_1.2.0   httr_1.4.2       
    [13] pillar_1.4.7      rlang_0.4.10      rstudioapi_0.13   minqa_1.2.4       callr_3.5.1       nloptr_1.2.2.2   
    [19] Matrix_1.2-18     desc_1.2.0        devtools_2.3.2    splines_4.0.3     lme4_1.1-26       statmod_1.4.35   
    [25] r2d3_0.2.5        htmlwidgets_1.5.3 tinytex_0.28      broom_0.7.3       compiler_4.0.3    xfun_0.20        
    [31] pkgconfig_2.0.3   askpass_1.1       base64enc_0.1-3   pkgbuild_1.2.0    htmltools_0.5.1.1 openssl_1.4.3    
    [37] tidyselect_1.1.0  tibble_3.0.4      fansi_0.4.1       crayon_1.3.4      dplyr_1.0.2       dbplyr_2.0.0     
    [43] withr_2.4.0       MASS_7.3-53       grid_4.0.3        nlme_3.1-149      jsonlite_1.7.2    lifecycle_0.2.0  
    [49] DBI_1.1.1         magrittr_2.0.1    cli_2.2.0         fs_1.5.0          remotes_2.2.0     testthat_3.0.1   
    [55] ellipsis_0.3.1    generics_0.1.0    vctrs_0.3.6       boot_1.3-25       tools_4.0.3       glue_1.4.2       
    [61] purrr_0.3.4       processx_3.4.5    pkgload_1.1.0     parallel_4.0.3    pbkrtest_0.5-0.1  yaml_2.2.1       
    [67] sessioninfo_1.1.1 memoise_1.1.0     usethis_2.0.0 

I use 2 alternative to set the spark.sql.pivotMaxValues:

1) From the local config connection of Sparklyr

```
spark_config_connect <- function(memory_executor = "4GB",
                                 memory_fraction = 0.9, 
                                 executor_core = 4,
                                 pivot_max_values = 50000,
                                 dynamic_memory_allocation="false",
                                 config_yaml=TRUE){
  library(sparklyr)
  conf <- spark_config()   # Load variable with spark_config()
  conf$spark.executor.memory <- memory_executor
  conf$spark.memory.fraction <- memory_fraction
  conf$spark.executor.cores <- executor_core
  conf$spark.dynamicAllocation.enabled <- dynamic_memory_allocation
  conf$spark.sql.pivotMaxValues <- pivot_max_values
  Sys.setenv(SPARK_HOME = "C:/Users/User/AppData/Local/spark/spark-3.1.1-bin-hadoop2.7")
  if(config_yaml){
    spark_conn <- spark_connect(master = "spark://local:7077") 
    print(spark_version(sc=spark_conn))
  }else{
    spark_conn <- spark_connect(master = "spark://local:7077", 
                                config = conf)  # Pass the conf variable 
    print(spark_version(sc=spark_conn))
  }
  return(spark_conn)
}
```

2) Using config.yml file from R config package, with these settings included

```
default:
  spark.sql.shuffle.partitions: 100
  spark.sql.pivotMaxValues: 50000
  spark.driver.memory: "1g"
  spark.driver.cores: 4
  spark.executor.memory: "1g"
  
production:
  spark.memory.fraction: 0.9
  spark.rdd.compress: true
```

Both of ways failed in attempt to make a Connection,  `Error in file(con, "r") : cannot open the connection `

**Comment by yitao-li** [comment]
@Vanderser I don't think the failure is related to the config you passed. If you only need to run Spark locally, then `spark_connect(master = "local", config = conf)` should work just file.

**Comment by Vanderser** [comment]
@yitao-li yes pardon me for the mistakes, I think its because the wrong master configuration makes it cannot open the connection..

I rerun this connection, 

spark_config_connect <- function(memory_executor = "4GB",
                                 memory_fraction = 0.9, 
                                 executor_core = 4,
                                 pivot_max_values = 50000,
                                 dynamic_memory_allocation="false",
                                 config_yaml=TRUE){
  library(sparklyr)
  conf <- spark_config()   # Load variable with spark_config()
  conf$spark.executor.memory <- memory_executor
  conf$spark.memory.fraction <- memory_fraction
  conf$spark.executor.cores <- executor_core
  conf$spark.dynamicAllocation.enabled <- dynamic_memory_allocation
  conf$spark.sql.pivotMaxValues <- pivot_max_values
  Sys.setenv(SPARK_HOME = "C:/Users/User/AppData/Local/spark/spark-3.1.1-bin-hadoop2.7")
  if(config_yaml){
    spark_conn <- spark_connect(master = "local") 
    print(spark_version(sc=spark_conn))
  }else{
    spark_conn <- spark_connect(master = "local", 
                                config = conf)  # Pass the conf variable 
    print(spark_version(sc=spark_conn))
  }
  return(spark_conn)
}

spark_conn <- spark_config_connect()

after this connection is successful, then when doing crosstabs, its still return error:

```
spark_read_data <- function(format="csv", filename=""){
  if(format=="csv"){
    csv <- spark_read_csv(spark_conn, name=filename, path=file.choose())
    writeLines("Spark DataFrame Dimensions")
    x <- c(sdf_nrow(csv),sdf_ncol(csv))
    print(x)
    return(csv)
  }
}

# this is movielens dataset that i use from https://www.kaggle.com/grouplens/movielens-20m-dataset
movie_rating <- spark_read_data(filename="movie_rating") 

user_unique <- movie_rating %>% 
  select(userId) %>% distinct() %>% count() %>% collect() %>%
  unlist %>% as.vector
movie_unique <- movie_rating %>% 
  select(movieId) %>% distinct() %>% count() %>% collect() %>%
  unlist %>% as.vector

> user_unique
[1] 270896
> movie_unique
[1] 45115

movie_cross <- sdf_crosstab(movie_rating, "userId", "movieId")
``` 
Error still popup:

```
Error: java.lang.IllegalArgumentException: requirement failed: The number of distinct values for movieId, can't exceed 1e4. Currently 19637
	at scala.Predef$.require(Predef.scala:281)
	at org.apache.spark.sql.execution.stat.StatFunctions$.crossTabulate(StatFunctions.scala:197)
	at org.apache.spark.sql.DataFrameStatFunctions.crosstab(DataFrameStatFunctions.scala:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.$anonfun$handleMethodCall$1(stream.scala:131)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:39)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Do I set the configuration incorrectly? what should I do to change the spark.sql.pivotMaxValues option to desired number?

**Comment by yitao-li** [comment]
@Vanderser This is a hard-coded limit in Spark unfortunately. See https://github.com/apache/spark/blob/3951e3371a83578a81474ed99fb50d59f27aac62/sql/core/src/main/scala/org/apache/spark/sql/execution/stat/StatFunctions.scala#L197-L198

You'll need to reduce the size of your input or split the input into several smaller pieces I guess.

**Comment by Vanderser** [comment]
I see.. so its limited to the core.. thank you @yitao-li
