### ISSUE TITLE
implement R interface for org.apache.spark.mllib.random.RandomRDDs functions

### ISSUE THREAD

**Issue by nathaneastwood** [sparklyr/sparklyr#3008]
I am trying to create a DataFrame of random values. I can do this from scala with

```scala
org.apache.spark.mllib.random.RandomRDDs.uniformRDD(sc, 10).toDF().show()
// +-------------------+
// |              value|
// +-------------------+
// |0.27116706178358974|
// |0.43860670227845455|
// | 0.4287061770490881|
// | 0.4023417822870039|
// | 0.8051721151223046|
// | 0.6124706169757794|
// | 0.9990971213966486|
// |0.41085247023327665|
// | 0.6008148713703578|
// | 0.8431822466362889|
// +-------------------+
```

I want to therefore be able to do this from R but `RandomRDDs` is a [singleton object](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/mllib/random/RandomRDDs.scala#L35). It would seem that support for this was added in https://github.com/sparklyr/sparklyr/pull/1387 but I cannot quite get it to work

```r
sc <- sparklyr::spark_connect(master = "local")

sparklyr::invoke( 
  sparklyr::invoke_static(sc, "org.apache.spark.mllib.random.RandomRDDs$", "MODULE$"), 
   "uniformRDD", 
   sparklyr::spark_context(sc), 
   10L 
)                                                                                                                                                                
# Error: java.lang.Exception: No matched method found for class org.apache.spark.mllib.random.RandomRDDs$.uniformRDD
#         at sparklyr.Invoke.invoke(invoke.scala:144)
#         at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
#         at sparklyr.StreamHandler.read(stream.scala:61)
#         at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:58)
#         at scala.util.control.Breaks.breakable(Breaks.scala:38)
#         at sparklyr.BackendHandler.channelRead0(handler.scala:38)
#         at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
#         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
#         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
#         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
#         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
#         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
#         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
#         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
#         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
#         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
#         at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
#         at java.lang.Thread.run(Thread.java:748)
```

For what it's worth, this part does work:

```r
sparklyr::invoke_static(sc, "org.apache.spark.mllib.random.RandomRDDs$", "MODULE$")                                                                                        
# <jobj[2149]>
#   org.apache.spark.mllib.random.RandomRDDs$
#   org.apache.spark.mllib.random.RandomRDDs$@17543943
```

**Comment by nathaneastwood** [comment]
I got a little further with this, this following works

```r
sparklyr::invoke(randomRDD, "uniformJavaRDD", sparklyr::java_context(sc), 10) %>%
  sparklyr::invoke("collect")
# [[1]]
# [1] 0.7764747
# 
# [[2]]
# [1] 0.4200194
# 
# ...
# 
# [[10]]
# [1] 0.2125503
```

Now I just need to figure out how to turn this into a DataFrame...

**Comment by yitao-li** [comment]
@nathaneastwood Hey sorry just got to see this issue.

Sparklyr::invoke doesn't support default parameters, so, in your first example, if you pass a Spark context, then you must specify all 4 parameters needed for the version of that method working with a Spark context.

Reason why default parameter is not supported: sparklyr needs to use reflection to make the method calls happen, and the default values of the params seem to be available at compile time only, and cannot be accessed at runtime via reflection. At least that was what I gathered so far. Before I started working on sparklyr I think Javier, Kevin, et al have also looked at this particular issue, and there was no good solution for it (yet).

Suggestions are welcome! :slightly_smiling_face:

**Comment by yitao-li** [comment]
Sparklyr issue related to the above: https://github.com/sparklyr/sparklyr/issues/940

**Comment by nathaneastwood** [comment]
No problem @yitao-li :) Indeed you are correct, the following works

```r
sparklyr::invoke_static(sc, "org.apache.spark.mllib.random.RandomRDDs$", "MODULE$") %>% 
      sparklyr::invoke("uniformRDD", sparklyr::spark_context(sc), 10L, 0L, 1L)                                                                                   
<jobj[78]>
  org.apache.spark.mllib.rdd.RandomRDD
  RandomRDD[37] at RDD at RandomRDD.scala:42
```

Same problem now figuring out how to turn this into a DataFrame, but I'm getting close :)

```r
sparklyr::invoke_static(sc, "org.apache.spark.mllib.random.RandomRDDs$", "MODULE$") %>% 
  sparklyr::invoke("uniformRDD", sparklyr::spark_context(sc), 10L, 0L, 1L) %>%
  sparklyr::invoke("toDF")                                                                
Error: java.lang.IllegalArgumentException: invalid method toDF for object 86/org.apache.spark.mllib.rdd.RandomRDD fields 1 selected 0
        at sparklyr.Invoke.invoke(invoke.scala:174)
        at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
        at sparklyr.StreamHandler.read(stream.scala:61)
        at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:58)
        at scala.util.control.Breaks.breakable(Breaks.scala:38)
        at sparklyr.BackendHandler.channelRead0(handler.scala:38)
        at sparklyr.BackendHandler.channelRead0(handler.scala:14)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by yitao-li** [comment]
@nathaneastwood I think some Scala code is needed in this case: `uniformRDD()` returns a `RDD[Double]`, but we need a `RDD[Row]` plus a schema in order to form a `Dataset[Row]` (aka `DataFrame`), and at the moment there is no conceivable way to just pass a lambda from R to Scala when calling RDD.map using reflection, so, the only way is to implement some of this in Scala and wrap everything in some interface easily callable by `sparklyr`.

I'm also wondering why not simply have `set.seed(5); df <- tibble::tibble(x = runif(1000));` and then copy the R dataframe to Spark with `copy_to()`. Is it because you want to generate a large quantity of pseudo-random numbers at scale, and also want this to happen lazily (so using the lazy-evaluation semantic of RDDs in Spark)?

In any case, I think it may be worthwhile to have R interfaces similar to `sdf_len()` for `uniformRDD()` type of Spark functionalities.

**Comment by nathaneastwood** [comment]
Yes, exactly I wanted to generate at scale, but also, the transfer of data between R and Spark can be a little slow. Ideally I want R to only be the instructor and Spark the executor. I know R, but not much Spark/Scala. Maybe I need to learn a little if I wanted to take this further.

**Comment by yitao-li** [comment]
@nathaneastwood Data transfer efficiency from R to Spark has been improved in recent versions of sparklyr, and also, you should consider arrow (https://spark.rstudio.com/guides/arrow/) for speeding up this process for large R dataframes. Generating random numbers in R would mean those numbers are evaluated eagerly in R though instead of lazily in Spark.

**Comment by nathaneastwood** [comment]
It doesn't do everything I would like, but I wrapped up what I've learnt into a small package: https://github.com/nathaneastwood/lightning/
