### ISSUE TITLE
Spark not working with Arrow loaded

### ISSUE THREAD

**Issue by zandergordan** [sparklyr/sparklyr#3012]
I am having an issue when using both sparklyr (1.6.2)/Spark (3.0.1) and Arrow (3.0.0) together, which looks related to an issue mentioned on the Spark documentation page regarding a Java option `-Dio.netty.tryReflectionSetAccessible=true`:

https://spark.apache.org/docs/3.0.1/

I've provided a `reprex` below, and also here is the result of `java -version` at my terminal:

```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

Also, though I've generated the reprex on my Mac, I originally encountered the issue using the same `sparklyr`, `arrow`, and `spark` versions on Ubuntu 18.04 with Java 11.

``` r
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter
sc <- spark_connect("local")
#> * Using Spark: 3.0.1
mtcars_tbl <- copy_to(sc, mtcars)
#> Error in value[[3L]](cond): Failed to fetch data: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): org.apache.spark.util.TaskCompletionListenerException: Memory was leaked by query. Memory leaked: (360448)
#> Allocator(toBatchIterator) 0/360448/360448/9223372036854775807 (res/actual/peak/limit)
#> 
#> 
#> Previous exception in task: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
#>  io.netty.util.internal.PlatformDependent.directBuffer(PlatformDependent.java:490)
#>  io.netty.buffer.NettyArrowBuf.getDirectBuffer(NettyArrowBuf.java:243)
#>  io.netty.buffer.NettyArrowBuf.nioBuffer(NettyArrowBuf.java:233)
#>  io.netty.buffer.ArrowBuf.nioBuffer(ArrowBuf.java:245)
#>  org.apache.arrow.vector.ipc.message.ArrowRecordBatch.computeBodyLength(ArrowRecordBatch.java:222)
#>  org.apache.arrow.vector.ipc.message.MessageSerializer.serialize(MessageSerializer.java:240)
#>  org.apache.arrow.vector.ipc.message.MessageSerializer.serialize(MessageSerializer.java:226)
#>  sparklyr.ArrowConvertersImpl$$anon$2.$anonfun$next$1(arrowconverters.scala:144)
#>  scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
#>  sparklyr.ArrowConvertersImpl.tryWithSafeFinally(arrowconverters.scala:42)
#>  sparklyr.ArrowConvertersImpl$$anon$2.next(arrowconverters.scala:147)
#>  sparklyr.ArrowConvertersImpl$$anon$2.next(arrowconverters.scala:122)
#>  scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
#>  org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
#>  org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
#>  org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
#>  org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:340)
#>  org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
#>  org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
#>  org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
#>  org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
#>  org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
#>  org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
#>  org.apache.spark.scheduler.Task.run(Task.scala:127)
#>  org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
#>  org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
#>  org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
#>  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
#>  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
#>  java.base/java.lang.Thread.run(Thread.java:830)
#>  at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:145)
#>  at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:124)
#>  at org.apache.spark.scheduler.Task.run(Task.scala:137)
#>  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
#>  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
#>  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
#>  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
#>  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
#>  at java.base/java.lang.Thread.run(Thread.java:830)
#> 
#> Driver stacktrace:
#>  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2059)
#>  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2008)
#>  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2007)
#>  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
#>  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
#>  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2007)
#>  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:973)
#>  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:973)
#>  at scala.Option.foreach(Option.scala:407)
#>  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:973)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2239)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2188)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2177)
#>  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
#>  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:775)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2120)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2139)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2164)
#>  at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
#>  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
#>  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
#>  at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
#>  at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
#>  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:385)
#>  at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3627)
#>  at org.apache.spark.sql.Dataset.$anonfun$collect$1(Dataset.scala:2940)
#>  at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3618)
#>  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
#>  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
#>  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
#>  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
#>  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
#>  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3616)
#>  at org.apache.spark.sql.Dataset.collect(Dataset.scala:2940)
#>  at sparklyr.ArrowConverters$.toArrowBatchRdd(arrowconverters.scala:271)
#>  at sparklyr.ArrowConverters.toArrowBatchRdd(arrowconverters.scala)
#>  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
#>  at sparklyr.Invoke.invoke(invoke.scala:147)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
#>  at sparklyr.StreamHandler.read(stream.scala:61)
#>  at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
#>  at scala.util.control.Breaks.breakable(Breaks.scala:42)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:39)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessa
```

<sup>Created on 2021-04-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.0.4 (2021-02-15)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> other attached packages:
#> [1] sparklyr_1.6.2 arrow_3.0.0   
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.0.4    pillar_1.4.7      dbplyr_2.0.0      highr_0.8        
#>  [5] r2d3_0.2.5        base64enc_0.1-3   tools_4.0.4       digest_0.6.27    
#>  [9] bit_4.0.4         jsonlite_1.7.2    evaluate_0.14     lifecycle_0.2.0  
#> [13] tibble_3.0.5      pkgconfig_2.0.3   rlang_0.4.10      reprex_1.0.0     
#> [17] cli_2.2.0         DBI_1.1.1         rstudioapi_0.13   parallel_4.0.4   
#> [21] yaml_2.2.1        xfun_0.20         withr_2.4.0       httr_1.4.2       
#> [25] stringr_1.4.0     dplyr_1.0.3       knitr_1.30        askpass_1.1      
#> [29] rappdirs_0.3.3    htmlwidgets_1.5.3 generics_0.1.0    fs_1.5.0         
#> [33] vctrs_0.3.6       rprojroot_2.0.2   bit64_4.0.5       tidyselect_1.1.0 
#> [37] forge_0.2.0       glue_1.4.2        R6_2.5.0          fansi_0.4.2      
#> [41] rmarkdown_2.6     tidyr_1.1.2       purrr_0.3.4       magrittr_2.0.1   
#> [45] htmltools_0.5.1   ellipsis_0.3.1    assertthat_0.2.1  renv_0.12.5      
#> [49] config_0.3.1      stringi_1.5.3     openssl_1.4.3     crayon_1.3.4
```

</details>

**Comment by zandergordan** [comment]
I have for now solved the issue on my Ubuntu machine by purging Java 11 and installing java 8 with:

```
sudo apt install openjdk-8-jdk
```

I had initially tried the instructions at the `sparklyr` site, which refer to an outdated apt repository:

https://spark.rstudio.com/examples/stand-alone-aws/

I gave up and just used `apt install default-jre`, which defaults to Java 11 for Ubuntu 18.04. The homepage should be more clear under the Installation section that Java 8 is strongly recommended:

**Comment by yitao-li** [comment]
Glad you figured out the JDK version on your own. I'll revise the spark.rstudio.com page mentioning known JDK versions that are currently supported by Spark.

**Comment by yitao-li** [comment]
Done -- https://github.com/rstudio/spark.rstudio.com/pull/116
