### ISSUE TITLE
Unable to create a sparklyr connection in databricks due to java.lang.ClassNotFoundException: sparklyr.UdfUtils

### ISSUE THREAD

**Issue by nviraj** [sparklyr/sparklyr#3053]
---

I am trying to create a sparklyr connection using databricks with the following commands.

```
message("Spark Connection")
sc <- sparklyr::spark_connect(method = "databricks")

message("Spark Context")
ctx <- sparklyr::spark_context(sc)

message("Checking Spark Connection")
print(sparklyr::spark_connection_is_open(sc = sc))
```

The error displayed is as follows:
```
Failed during initialize_connection: java.lang.ClassNotFoundException: sparklyr.UdfUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:106)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:39)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Session Info:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.5    sparklyr_1.6.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         rstudioapi_0.11    magrittr_1.5       tidyselect_1.1.0  
 [5] R6_2.4.1           rlang_0.4.10       hwriter_1.3.2      httr_1.4.1        
 [9] SparkR_3.0.0       tools_3.6.3        parallel_3.6.3     config_0.3        
[13] DBI_1.1.1          withr_2.2.0        dbplyr_2.1.1       htmltools_0.5.0   
[17] ellipsis_0.3.1     yaml_2.2.1         rprojroot_2.0.2    assertthat_0.2.1  
[21] digest_0.6.25      tibble_3.0.3       Rserve_1.8-7       lifecycle_1.0.0   
[25] forge_0.2.0        crayon_1.3.4       tidyr_1.1.0        purrr_0.3.4       
[29] htmlwidgets_1.5.1  base64enc_0.1-3    vctrs_0.3.7        hwriterPlus_1.0-3 
[33] glue_1.4.1         compiler_3.6.3     pillar_1.4.6       r2d3_0.2.3        
[37] generics_0.0.2     TeachingDemos_2.10 jsonlite_1.7.0     pkgconfig_2.0.3   
```

Because the error seems to be Java related pasting paths as well:
```
print(Sys.getenv("PATH"))
print(Sys.getenv("JAVA_HOME"))
```
```
[1] "/databricks/python3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
[1] "/usr/lib/jvm/zulu8-ca-amd64/jre/"
```

**Comment by yitao-li** [comment]
This is something similar to https://github.com/sparklyr/sparklyr/issues/2999 and (at least I think) is not something that can be addressed by modifying the open-source `sparklyr` repo.

Please file a bug/ticket(?) for Databricks runtime instead. Databricks runtime appears to have customized the location to install and load `sparklyr` jar files and I don't think this customized logic is open-source, so, I will be unable to help unfortunately.
