### ISSUE TITLE
spark_read_delta fails when on RStudio Desktop connected via databricks connect

### ISSUE THREAD

**Issue by tsengj** [sparklyr/sparklyr#3108]
I'm trying to work off RStudio Desktop and utilize Databricks. I can connect through databricks connect, and have no issues mounting delta tables using SparkR from RStudio Desktop. Also no issues running spark_read_delta when running it on Databricks Notebook R. But when on RStudio Desktop (Via DataBricks Connect) and try to mount using sparklyr's spark_read_delta, that failed. 

# Successful only if i pre-mount delta tables in DataBricks Notebook R. Subsequently, through databricks connect, read tables using RStudio Desktop
```r
> sc <- spark_connect(method = "databricks", spark_home = "c:/programdata/anaconda3/lib/site-packages/pyspark")
library(dplyr
> src_tbls(sc)
[1] "cust"    "sales"   "scv"     "scv_ref"
> cust_tbl <- spark_read_table(sc,"cust")
```

# Also successful when using SparkR to mount delta data tables through databricks connect on RStudio Desktop
```r
# Point to the OSS package path, e.g., /path/to/.../spark-2.4.0-bin-hadoop2.7
library(SparkR, lib.loc = .libPaths(c(file.path('C:/Users/user.name/AppData/Local/spark/spark-3.1.1-bin-hadoop3.2', 'R', 'lib'), .libPaths())))

# Point to the Databricks Connect PySpark installation, e.g., /path/to/.../pyspark
Sys.setenv(SPARK_HOME = "c:/programdata/anaconda3/lib/site-packages/pyspark")
sparkR.session()

cust_tbl <- read.df(path = "/mnt/dataLake/<some directory>/<some directory>/<some directory>/<some directory>/", source = "delta")
```

# But if I want to mount the delta tables directly from RStudio Desktop via Databricks Connect using spark_read_delta, it errors out 
```r

> #load tables
> cust_tbl <- spark_read_delta(sc, path = "/mnt/dataLake/<some directory>/<some directory>/<some directory>/<some directory>/")
Error: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: H:%5Cmnt%5CdataLake%5C<some directory>%5C<some directory>%5<some directory>%5C<some directory>%5C
	at org.apache.hadoop.fs.Path.initialize(Path.java:205)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at com.databricks.sql.transaction.tahoe.DeltaValidation$.validateDeltaRead(DeltaValidation.scala:94)
	at org.apache.spark.sql.DataFrameReader.preprocessDeltaLoading(DataFrameReader.scala:308)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:356)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:278)
	at com.databricks.service.SparkServiceRPCHandler$$anon$1.call(SparkServiceRPCHandler.scala:99)
	at com.databricks.service.SparkServiceRPCHandler$$anon$1.call(SparkServiceRPCHandler.scala:80)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4724)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4721)
	at com.databricks.service.SparkServiceRPCHandler$.getOrLoadAnonymousRelation(SparkServiceRPCHandler.scala:80)
	at com.databricks.service.SparkServiceRPCHandler.execute0(SparkServiceRPCHandler.scala:711)
	at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC0$1(SparkServiceRPCHandler.scala:474)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.service.SparkServiceRPCHandler.executeRPC0(SparkServiceRPCHandler.scala:370)
	at com.databricks.service.SparkServiceRPCHandler$$anon$2.call(SparkServiceRPCHandler.scala:321)
	at com.databricks.service.SparkServiceRPCHandler$$anon$2.call(SparkServiceRPCHandler.scala:307)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC$1(SparkServiceRPCHandler.scala:357)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.service.SparkServiceRPCHandler.executeRPC(SparkServiceRPCHandler.scala:334)
	at com.databricks.service.SparkServiceRPCServlet.doPost(SparkServiceRPCServer.scala:152)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Relative path in absolute URI: H:%5Cmnt%5CdataLake%5C<some directory>%5C<some directory>%5C<some directory>%5C<some directory>%5C
	at java.net.URI.checkPath(URI.java:1849)
	at java.net.URI.<init>(URI.java:745)
	at org.apache.hadoop.fs.Path.initialize(Path.java:202)
	... 50 more
```
# Session Info as below

```r
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.5    sparklyr_1.6.2

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    uuid_0.1-4        tidyselect_1.1.0  R6_2.5.0          rlang_0.4.10      fansi_0.4.2       httr_1.4.2        tools_4.0.5       parallel_4.0.5   
[11] xfun_0.22         config_0.3.1      tinytex_0.31      utf8_1.2.1        DBI_1.1.1         withr_2.4.2       dbplyr_2.1.1      askpass_1.1       htmltools_0.5.1.1 ellipsis_0.3.1   
[21] openssl_1.4.3     yaml_2.2.1        rprojroot_2.0.2   assertthat_0.2.1  digest_0.6.27     tibble_3.1.1      lifecycle_1.0.0   forge_0.2.0       crayon_1.4.1      tidyr_1.1.3      
[31] purrr_0.3.4       base64enc_0.1-3   htmlwidgets_1.5.3 vctrs_0.3.8       glue_1.4.2        compiler_4.0.5    pillar_1.6.0      r2d3_0.2.5        generics_0.1.0    jsonlite_1.7.2   
[41] pkgconfig_2.0.3  
```

**Comment by yitao-li** [comment]
@tsengj I think prepending `"file://"` to a path will do the trick (assuming the path in question, from Databricks runtime point-of-view, in fact points to a local file):

```
cust_tbl <- spark_read_delta(sc, path = "file:///mnt/dataLake/<some directory>/<some directory>/<some directory>/<some directory>/")
```

**Comment by yitao-li** [comment]
@tsengj Did you consider what was suggested in https://github.com/sparklyr/sparklyr/issues/3091 (i.e., it was similar to my suggestion above except for the correct schema should be `dbfs://` instead of `file://`)?

I'm not entirely sure how Databricks runtime works, but my guess is one of the 2 suggestions above is likely to be correct :slightly_smiling_face:  (I hope).

**Comment by yitao-li** [comment]
Feel free to re-open this issue if neither of our suggestions worked for you.

**Comment by tsengj** [comment]
Success. that did it.
thanks!
```r
"dbfs:///mnt/dataLake/<some directory>/<some directory>/<some directory>/<some directory>/")
```
