### ISSUE TITLE
Failed to fetch data: java.lang.NullPointerException when querying (selecting) array type columns with Null values

### ISSUE THREAD

**Issue by gauri-nagavkar** [sparklyr/sparklyr#3113]
I am using this code to run Spark sql queries in R:

```
# Import packages
library(sparklyr)
library(DBI)
# Establish a spark connection
sc <- spark_connect(master = 'local')
# Write query
sql <- "SELECT <column_name> FROM fixed_all_data_all_relationships.<table_name>"
# Use dbGetQuery function of DBI to run query
my_df <- dbGetQuery(sc, sql)
```

Here are some of my observations:

- We get an error only when the data_type of the column is array and there is a NULL value in the column.
- Array column with no NULL values- works
`SELECT * FROM VALUES (array(1)), (array(2, 3)),  (array(4, 5)) AS tab(foo)`
- Array column with NULL values- ERROR!
`SELECT * FROM VALUES (array(1)), (array(2, 3)), (NULL), (array(4, NULL, 5)) AS tab(foo)`
- Array column with NULL values, but only non-null values selected- works
`SELECT * FROM VALUES (array(1)), (array(2, 3)), (NULL), (array(4, NULL, 5)) AS tab(foo) WHERE foo IS NOT NULL`

Here's an reproducible query:
```
sql <- "SELECT * FROM VALUES (array(1)), (array(2, 3)), (NULL), (array(4, NULL, 5)) AS tab(foo)"
my_df <- dbGetQuery(sc, sql)
```
Here's the error that I'm getting:
```
Error in value[[3L]](cond): Failed to fetch data: java.lang.NullPointerException
	at sparklyr.Collectors$.collectIntegerArr(collectors.scala:30)
	at sparklyr.Collectors$$anonfun$mkColumnCtx$14.apply(collectors.scala:239)
	at sparklyr.Collectors$$anonfun$mkColumnCtx$14.apply(collectors.scala:239)
	at sparklyr.Collectors$ColumnCtx.collect(collectors.scala:201)
	at sparklyr.Utils$.sparklyr$Utils$$collectRows(utils.scala:92)
	at sparklyr.Utils$.collect(utils.scala:116)
	at sparklyr.Utils.collect(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at sparklyr.BackendHandler.channelRead0(handler.scala:38)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

Traceback:

1. dbGetQuery(sc, sql)
2. dbGetQuery(sc, sql)
3. tryCatch(dbFetch(rs, n = -1, ...), error = function(e) {
 .     stop("Failed to fetch data: ", e$message)
 . })
4. tryCatchList(expr, classes, parentenv, handlers)
5. tryCatchOne(expr, names, parentenv, handlers[[1L]])
6. value[[3L]](cond)
7. stop("Failed to fetch data: ", e$message)
```

**Comment by yitao-li** [comment]
Seems like a bug.

**Comment by gauri-nagavkar** [comment]
Thanks, @yitao-li ! I appreciate your quick response. Do you have a rough estimate as to when will v1.7.0 be released?

**Comment by yitao-li** [comment]
@gauri-nagavkar It's in progress and I estimate the CRAN release will complete before next Tuesday (depending on how fast CRAN can process the submission).
