### ISSUE TITLE
Sparklyr 1.7 can no longer connect to Databricks (Databricks connect)

### ISSUE THREAD

**Issue by tsengj** [sparklyr/sparklyr#3129]
No issues when using sparklyr 1.6.2 decided to update sparklyr and now I can no longer connect to databricks through databricks connect.

Is the new version compatible with http proxy? My anaconda has to go through a proxy which has been set at the environment variables via http_proxy.

```r
library(sparklyr)
> options(sparklyr.log.console = TRUE)
> sc <- spark_connect(method = "databricks", spark_home = "c:/programdata/anaconda3/lib/site-packages/pyspark")
Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  : 
  Gateway in localhost:8880 did not respond.


Try running `options(sparklyr.log.console = TRUE)` followed by `sc <- spark_connect(...)` for more debugging info.
> 
```

my session info

```r
> Sys.getenv("http_proxy")
[1] "<ip add>:8080"

sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.7.0

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    rappdirs_0.3.3    tidyselect_1.1.0  R6_2.5.0          rlang_0.4.10      fansi_0.4.2       httr_1.4.2        dplyr_1.0.5       tools_4.0.5       parallel_4.0.5    config_0.3.1      utf8_1.2.1        DBI_1.1.1         withr_2.4.2       dbplyr_2.1.1      askpass_1.1      
[18] htmltools_0.5.1.1 ellipsis_0.3.1    openssl_1.4.3     yaml_2.2.1        rprojroot_2.0.2   assertthat_0.2.1  digest_0.6.27     tibble_3.1.1      lifecycle_1.0.0   forge_0.2.0       crayon_1.4.1      tidyr_1.1.3       purrr_0.3.4       base64enc_0.1-3   htmlwidgets_1.5.3 vctrs_0.3.8       glue_1.4.2       
[35] compiler_4.0.5    pillar_1.6.0      r2d3_0.2.5        generics_0.1.0    jsonlite_1.7.2    pkgconfig_2.0.3  
> spark_installed_versions()
  spark hadoop                                                                    dir
1 2.4.3    2.7 C:\\Users\\james.tseng\\AppData\\Local/spark/spark-2.4.3-bin-hadoop2.7
> spark_home_dir()
[1] "C:\\Users\\james.tseng\\AppData\\Local/spark/spark-2.4.3-bin-hadoop2.7"
> 
```

And my Databricks-connect test
```
(base) C:\>databricks-connect test
* PySpark is installed at c:\programdata\anaconda3\lib\site-packages\pyspark
* Checking SPARK_HOME
* Checking java version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
* Skipping scala command test on Windows
* Testing python command
21/06/14 23:46:02 ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
        at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:382)
        at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:397)
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:390)
        at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:80)
        at org.apache.hadoop.security.SecurityUtil.getAuthenticationMethod(SecurityUtil.java:611)
        at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:274)
        at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:262)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:807)
        at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:777)
        at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:650)
        at org.apache.spark.util.Utils$.$anonfun$getCurrentUserName$1(Utils.scala:2761)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2761)
        at org.apache.spark.SecurityManager.<init>(SecurityManager.scala:79)
        at org.apache.spark.deploy.SparkSubmit.secMgr$lzycompute$1(SparkSubmit.scala:368)
        at org.apache.spark.deploy.SparkSubmit.secMgr$1(SparkSubmit.scala:368)
        at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$8(SparkSubmit.scala:376)
        at scala.Option.map(Option.scala:230)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:376)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/06/14 23:46:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
21/06/14 23:46:03 WARN MetricsSystem: Using default name SparkStatusTracker for source because neither spark.metrics.namespace nor spark.app.id is set.
21/06/14 23:46:09 WARN HTTPClient: Setting proxy configuration for HTTP client based on env var HTTPS_PROXY=<IP Address>:8080
View job details at <url>/?o=0#/setting/clusters/0331-130342-rages795/sparkUi
21/06/14 23:46:17 WARN ProcfsMetricsGetter: Exception when trying to compute pagesize, as a result reporting of ProcessTree metrics is stopped
* Simple PySpark test passed                                        (0 + 4) / 4]
* Testing dbutils.fs
21/06/14 23:46:23 WARN DBFS: DBFS listStatus on / took 1264 ms
[FileInfo(path='dbfs:/FileStore/', name='FileStore/', size=0), FileInfo(path='dbfs:/databricks-datasets/', name='databricks-datasets/', size=0), FileInfo(path='dbfs:/databricks-results/', name='databricks-results/', size=0), FileInfo(path='dbfs:/ml/', name='ml/', size=0), FileInfo(path='dbfs:/mnt/', name='mnt/', size=0), FileInfo(path='dbfs:/prod/', name='prod/', size=0), FileInfo(path='dbfs:/target/', name='target/', size=0), FileInfo(path='dbfs:/tmp/', name='tmp/', size=0), FileInfo(path='dbfs:/user/', name='user/', size=0)]
* Simple dbutils test passed
* All tests passed.

(base) C:\>SUCCESS: The process with PID 19156 (child process of PID 16380) has been terminated.
SUCCESS: The process with PID 16380 (child process of PID 14260) has been terminated.
SUCCESS: The process with PID 14260 (child process of PID 18564) has been terminated.
```

**Comment by yitao-li** [comment]
@tsengj I'm aware of an issue with `sparklyr` connecting to Spark 3.1.x and this might be something that's related to that issue.

Sparklyr does not officially supported Spark 3.1.x yet, but it should be a supported Spark version very soon. I'm working on it and releasing the fix in sparklyr 1.7.1 asap.

**Comment by yitao-li** [comment]
@tsengj Could you see whether re-installing `sparklyr` by running `remotes::install_github("yitao-li/sparklyr", ref = "bugfix/spark-3.1.x-compat")` fixes the problem?

The error message you mentioned just says "Could not locate executable null\bin\winutils.exe in the Hadoop binaries." which may or may not be related to the Spark 3.1.x issue I mentioned. It is not entirely clear why the `null` value is in the path to wintuils.exe from the Spark submit stack trace.

**Comment by tsengj** [comment]
I've checked. it worked. Thanks.
FYI
The winutils isn't an issue as indicated here. https://github.com/dotnet/spark/issues/61
prior to version 1.7, my previous version of 1.6.2 connected successfully/

**Comment by alopezespino** [comment]
Thank you @yitao-li!! I had this issue yesterday, I reinstalled after your latest commit and now it is working :D
