### ISSUE TITLE
Need help in computing Ranking metrics through invoke

### ISSUE THREAD

**Issue by nviraj** [sparklyr/sparklyr#3199]
Hi, 

I am looking for some guidance on how to generate Ranking metrics such as mean average precision. I am trying to achieve it through "[RankingMetrics](https://spark.apache.org/docs/latest/api/java/org/apache/spark/mllib/evaluation/RankingMetrics.html)" class from mllib which works on a RDD as we don't have a Ranking evaluator at the moment.

So far I have been unsuccessful (Certainly due to my lack of understanding of how invoke/ RDD based method/ Java works in general) and I would appreciate any guidance. 

Please see the attached reprex. The flow is as follows:
- Generate dummy data
- Create ALS model and generate predictions
- Combining predictions and actuals to create merged data for RankingMetrics
- Convert merged data to RDD
- Invoke RankingMetrics and call meanAveragePrecision method

Thanks! 

``` r
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter

# Resource
# https://spark.apache.org/docs/latest/api/java/org/apache/spark/mllib/evaluation/RankingMetrics.html

# Testing with local spark
sc <-
  spark_connect(master = "local")

# Printing out Spark version
sparklyr::spark_version(sc)
#> [1] '3.1.1'

# Creating a dummy movies dataset and copying to spark
movies <- data.frame(
  user   = c(1, 2, 0, 1, 2, 0),
  item   = c(1, 1, 1, 2, 2, 0),
  rating = c(3, 1, 2, 4, 5, 4)
)
movies_tbl <- sdf_copy_to(sc, movies)

# Create an ALS model and run predictions
model <- ml_als(movies_tbl, rating ~ user + item)

# Predict with ALS model
pred <- ml_predict(model, movies_tbl)

# For reprex, both actual and predicted items will be the same
actual_items <- pred %>%
  dplyr::group_by(user) %>%
  dplyr::summarise(actual_items = collect_set(item))
predicted_items <- pred %>%
  dplyr::group_by(user) %>%
  dplyr::summarise(predicted_items = collect_set(item))

# Joining predictions with actual items in the way expected for RankingMetric
merged_data <- predicted_items %>%
  dplyr::inner_join(actual_items) %>%
  dplyr::mutate(pred_and_truth = map(predicted_items, actual_items)) %>%
  dplyr::select(pred_and_truth)
#> Joining, by = "user"
sdf_register(x = merged_data, name = "merged_data")
#> Error in readTypedObject(con, type): Unsupported type for deserialization

# Print schema of our merged data
sparklyr::sdf_schema(
  x = merged_data,
  expand_nested_cols = TRUE,
  expand_struct_cols = TRUE
)
#> $pred_and_truth
#> $pred_and_truth$name
#> [1] "pred_and_truth"
#> 
#> $pred_and_truth$type
#> [1] "MapType(ArrayType(DoubleType,false),ArrayType(DoubleType,false),false)"

# Creating RDD for ranking metrics
java_df <- spark_dataframe(merged_data)
java_rdd <- sparklyr::invoke(spark_jobj(java_df), "rdd")
# Checking if it is rdd class
sparklyr::jobj_class(java_rdd)
#> [1] "MapPartitionsRDD" "RDD"              "Object"

# Invoke RankingMetrics
ranking_metric <- invoke_static(
  sc = sc,
  class = "org.apache.spark.mllib.evaluation.RankingMetrics",
  method = "RankingMetrics", java_rdd
)
#> Error: java.lang.IllegalArgumentException: invalid method RankingMetrics for object org.apache.spark.mllib.evaluation.RankingMetrics/org.apache.spark.mllib.evaluation.RankingMetrics fields 0 selected 0
#>  at sparklyr.Invoke.invoke(invoke.scala:188)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:141)
#>  at sparklyr.StreamHandler.read(stream.scala:62)
#>  at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:60)
#>  at scala.util.control.Breaks.breakable(Breaks.scala:42)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:41)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
#>  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
#>  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
#>  at java.lang.Thread.run(Thread.java:748)

# Calculating mean average precision
final_metric <- ranking_metric %>%
  invoke(method = "meanAveragePrecision")
#> Error in spark_connection(jobj): object 'ranking_metric' not found
```

<sup>Created on 2021-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gregleleu** [comment]
You're instantiating a new object, so you'll want to use `invoke_new`not `invoke_static`. As per the java documentation the constructor needs two parameters (not sure why). Hence you're looking at something like:
```
## Making the second argument -> a bit convoluted, not sure why
a <- invoke_static(
  sc,
  "java.lang.Class",
  "forName",
  "java.lang.Number"
)

b <- invoke_static(
  sc,
  "scala.reflect.ClassManifestFactory",
  "fromClass",
  a
)

## making the object
ranking_metric <- invoke_new(
  sc = sc,
  class = "org.apache.spark.mllib.evaluation.RankingMetrics",
  java_rdd, b
  )

## running the evaluation --> still fails, see below
final_metric <- ranking_metric %>%
  invoke(method = "meanAveragePrecision")
```

The evaluation still fails, because the RDD needs to extend the scala.Product class, but I'll leave that to you
