### ISSUE TITLE
Cannot connect RStudio desktop to Spark through sparklyr

### ISSUE THREAD

**Issue by JinghongZeng** [sparklyr/sparklyr#3243]
I am trying to connect to a local master through sparklyr. My code is :
```r
pacman::p_load(sparklyr, sparknlp, tidyverse)
options(sparklyr.log.console = TRUE)
sc <- spark_connect(master = "local", version = "3.0.0")
```

An error message is returned, saying `Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  :  Gateway in localhost:8880 did not respond.` Then I printed out the log, which looks like below:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.spark.unsafe.array.ByteArrayMethods.<clinit>(ByteArrayMethods.java:54)
	at org.apache.spark.internal.config.package$.<init>(package.scala:1006)
	at org.apache.spark.internal.config.package$.<clinit>(package.scala)
	at org.apache.spark.deploy.SparkSubmitArguments.$anonfun$loadEnvironmentArguments$3(SparkSubmitArguments.scala:157)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.deploy.SparkSubmitArguments.loadEnvironmentArguments(SparkSubmitArguments.scala:157)
	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:115)
	at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:990)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:990)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.nio.DirectByteBuffer(long,int) accessible: module java.base does not "opens java.nio" to unnamed module @13545af8
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at org.apache.spark.unsafe.Platform.<clinit>(Platform.java:56)
	... 13 more
```

I did install Java updates and figured out there may be some issue related to Spark configuration, but I don't know what to do next.

I am on Mac OS 12.3, RStudio 2021.09.1. Any help would be much appreciated.

**Comment by JinghongZeng** [comment]
It is because of the Java version. A lower Java version would work. Please see the [link](https://community.rstudio.com/t/cannot-connect-rstudio-desktop-to-spark-through-sparklyr/133362?u=jinghong_zeng) for my solution.
