### ISSUE TITLE
handleInvalid arg inaccessible when trying to fit rand_forest

### ISSUE THREAD

**Issue by Athospd** [sparklyr/sparklyr#3252]
I would like to set handleInvalid = "keep" when fitting rand_forest() trough tidymodels, but it seems to be inaccessible. 

I tried some versions of `set_engine("spark", seed = 42, handleInvalid = "keep")` with no luck!

Ty

``` r
library(tidymodels)
library(sparklyr)
config <- sparklyr::spark_config()
sc <- spark_connect(method = "databricks", spark_home = Sys.getenv("DATABRICKS_CONNECT_SPARK_HOME"), config = config)

sparklyr::copy_to(sc, mtcars, name = "mtcars", overwrite = TRUE)
#> # Source: spark<mtcars> [?? x 11]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with more rows
mtcars_spark <- tbl(sc, "mtcars")

rf_with_seed <- 
    rand_forest(trees = 10, mtry = varying(), mode = "classification") %>%
    set_engine("spark", seed = 42)

rf_fit <- rf_with_seed %>% 
    set_args(mtry = 2) %>% 
    fit(vs ~ ., data = union(mtcars_spark, mtcars_spark %>% mutate(carb = NA)))
#> Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 8 in stage 46457.0 failed 4 times, most recent failure: Lost task 8.3 in stage 46457.0 (TID 12378182) (10.154.209.223 executor 123): org.apache.spark.SparkException: Failed to execute user defined function(VectorAssembler$$Lambda$20006/1823940938: (struct<mpg:double,cyl:double,disp:double,hp:double,drat:double,wt:double,qsec:double,am:double,gear:double,carb:double>) => struct<type:tinyint,size:int,indices:array<int>,values:array<double>>)
#>  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage4.agg_doAggregateWithKeysOutput_0$(Unknown Source)
#>  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage4.processNext(Unknown Source)
#>  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
#>  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:757)
#>  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
#>  at scala.collection.Iterator.foreach(Iterator.scala:941)
#>  at scala.collection.Iterator.foreach$(Iterator.scala:941)
#>  at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
#>  at org.apache.spark.rdd.RDD.$anonfun$foreach$2(RDD.scala:1017)
#>  at org.apache.spark.rdd.RDD.$anonfun$foreach$2$adapted(RDD.scala:1017)
#>  at org.apache.spark.SparkContext.$anonfun$runJob$2(SparkContext.scala:2517)
#>  at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
#>  at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
#>  at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
#>  at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
#>  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
#>  at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
#>  at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)
#>  at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
#>  at org.apache.spark.scheduler.Task.run(Task.scala:91)
#>  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:813)
#>  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1646)
#>  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:816)
#>  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
#>  at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
#>  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:672)
#>  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
#>  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
#>  at java.lang.Thread.run(Thread.java:748)
#> Caused by: org.apache.spark.SparkException: Encountered null while assembling a row with handleInvalid = "error". Consider
#> removing nulls from dataset or using handleInvalid = "keep" or "skip".
#>  at org.apache.spark.ml.feature.VectorAssembler$.$anonfun$assemble$1(VectorAssembler.scala:292)
#>  at org.apache.spark.ml.feature.VectorAssembler$.$anonfun$assemble$1$adapted(VectorAssembler.scala:261)
#>  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
#>  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
#>  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
#>  at org.apache.spark.ml.feature.VectorAssembler$.assemble(VectorAssembler.scala:261)
#>  at org.apache.spark.ml.feature.VectorAssembler.$anonfun$transform$6(VectorAssembler.scala:144)
#>  ... 29 more
#> 
#> Driver stacktrace:
#>  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2828)
#>  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2775)
#>  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2769)
#>  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
#>  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
#>  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2769)
#>  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1305)
#>  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1305)
#>  at scala.Option.foreach(Option.scala:407)
#>  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1305)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3036)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2977)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2965)
#>  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
#>  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1067)
#>  at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2477)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2460)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2498)
#>  at com.databricks.service.SparkServiceImpl$.$anonfun$executeRDD$3(SparkServiceImpl.scala:147)
#>  at org.apache.spark.SparkContext.withCallSite(SparkContext.scala:2440)
#>  at com.databricks.service.SparkServiceImpl$.$anonfun$executeRDD$1(SparkServiceImpl.scala:147)
#>  at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:395)
#>  at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:484)
#>  at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$4(UsageLogging.scala:504)
#>  at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:266)
#>  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
#>  at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:261)
#>  at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:258)
#>  at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:20)
#>  at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:305)
#>  at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:297)
#>  at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:20)
#>  at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:479)
#>  at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:404)
#>  at com.databricks.spark.util.PublicDBLogging.recordOperationWithResultTags(DatabricksSparkUsageLogger.scala:20)
#>  at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:395)
#>  at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:367)
#>  at com.databricks.spark.util.PublicDBLogging.recordOperation(DatabricksSparkUsageLogger.scala:20)
#>  at com.databricks.spark.util.PublicDBLogging.recordOperation0(DatabricksSparkUsageLogger.scala:57)
#>  at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:137)
#>  at com.databricks.spark.util.UsageLogger.recordOperation(UsageLogger.scala:71)
#>  at com.databricks.spark.util.UsageLogger.recordOperation$(UsageLogger.scala:58)
#>  at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:98)
#>  at com.databricks.spark.util.UsageLogging.recordOperation(UsageLogger.scala:429)
#>  at com.databricks.spark.util.UsageLogging.recordOperation$(UsageLogger.scala:408)
#>  at com.databricks.service.SparkServiceImpl$.recordOperation(SparkServiceImpl.scala:92)
#>  at com.databricks.service.SparkServiceImpl$.executeRDD(SparkServiceImpl.scala:144)
#>  at com.databricks.service.SparkServiceRPCHandler.execute0(SparkServiceRPCHandler.scala:725)
#>  at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC0$1(SparkServiceRPCHandler.scala:477)
#>  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
#>  at com.databricks.se
#> Timing stopped at: 0.268 0.017 5.507
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edgararuiz** [comment]
Hi, I think believe that this would be a request that needs to go to `parsnip`.  The integration with `sparklyr` lives in that code set: https://github.com/tidymodels/parsnip/blob/9c2bdbb902c1bfbe74d80a8c3bb8f6d65046c647/R/rand_forest_data.R#L484
