### ISSUE TITLE
Unable to access AWS S3 - `Error : java.nio.file.AccessDeniedException:`

### ISSUE THREAD

**Issue by GitHunter0** [sparklyr/sparklyr#3254]
Hi folks, 

I'm not being able to access AWS S3 via `sparklyr`. Please, see the MWE below.
I tried to access the same S3 file via `aws.s3` package and it worked without any problem, therefore I don't believe it is an AWS access restriction issue.
I running this inside a Databricks notebook with a Spark cluster.

Any help will be much appreciated.

``` r
library(sparklyr)

Sys.setenv(
  "AWS_ACCESS_KEY_ID" = "hidden",
  "AWS_SECRET_ACCESS_KEY" = "hidden",
  "AWS_DEFAULT_REGION" = "us-east-2",
)

conf <- spark_config()
conf$sparklyr.defaultPackages <-  c("org.apache.hadoop:hadoop-aws:3.3.2")

spark_version <- "3.1.2"
sc <- spark_connect(method = "databricks", config = conf, version = spark_version)
sc

sparklyr::spark_read_csv(sc, path="s3a://my-bucket-name/my-folder-name/my-filename.csv")
```
`spark_read_csv(...)` throws this error message:
```
Error : java.nio.file.AccessDeniedException: s3a://my-bucket-name/my-folder-name/my-filename.csv: getFileStatus on s3a://my-bucket-name/my-folder-name/my-filename.csv: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD https://my-bucket-name.s3.us-east-2.amazonaws.com my-folder-name/my-filename.csv {} Hadoop 2.7.4, aws-sdk-java/1.11.655 Linux/5.4.0-1071-aws OpenJDK_64-Bit_Server_VM/25.302-b08 java/1.8.0_302 scala/2.12.10 vendor/Azul_Systems,_Inc. com.amazonaws.services.s3.model.GetObjectMetadataRequest; Request ID: 4KZAZ961HQGG0RSG, Extended Request ID: 4GjELy99Qdktrl9GhYnsYMunDxvPq1Hh35k+hmCL5GIpk6cH55ELlNSocLIHl8gfZmpQB7sltiI=, Cloud Provider: AWS, Instance ID: i-0b21b7dc916ba6a31 (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 4KZAZ961HQGG0RSG; S3 Extended Request ID: 4GjELy99Qdktrl9GhYnsYMunDxvPq1Hh35k+hmCL5GIpk6cH55ELlNSocLIHl8gfZmpQB7sltiI=), S3 Extended Request ID: 4GjELy99Qdktrl9GhYnsYMunDxvPq1Hh35k+hmCL5GIpk6cH55ELlNSocLIHl8gfZmpQB7sltiI=:403 Forbidden
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:248)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:159)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3227)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:3197)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:3136)
	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1439)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.isDirectory(S3AFileSystem.java:4056)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:50)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:412)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:444)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:400)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:400)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:964)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:744)
	at sun.reflect.GeneratedMethodAccessor446.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:161)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:138)
	at sparklyr.StreamHandler.read(stream.scala:62)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:59)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:40)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD 
...
shaded.databricks.org.apache.hadoop.fs.s3a.EnforcingDatabricksS3Client.getObjectMetadata(EnforcingDatabricksS3Client.scala:222)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$getObjectMetadata$4(S3AFileSystem.java:1697)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:333)
	at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:294)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:1694)
	at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3218)
	... 48 more

Some(<code style = 'font-size:10p'> Error: java.nio.file.AccessDeniedException: s3a://... com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD ... {} Hadoop 2.7.4, aws-sdk-java/1.11.655 Linux/5.4.0-1071-aws OpenJDK_64-Bit_Server_VM/25.302-b08 java/1.8.0_302 scala/2.12.10 vendor/Azul_Systems,_Inc. com.amazonaws.services.s3.model.GetObjectMetadataRequest; Request ID: 4KZAZ961HQGG0RSG, Extended Request ID: 4GjELy99Qdktrl9GhYnsYMunDxvPq1Hh35k+hmCL5GIpk6cH55ELlNSocLIHl8gfZmpQB7sltiI=, Cloud Provider: AWS, Instance ID: i-0b21b7dc916ba6a31 (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 4KZAZ961HQGG0RSG; S3 Extended Request ID: 4GjELy99Qdktrl9GhYnsYMunDxvPq1Hh35k+hmCL5GIpk6cH55ELlNSocLIHl8gfZmpQB7sltiI=), S3 Extended Request ID: 4GjELy99Qdktrl9GhYnsYMunDxvPq1Hh35k+hmCL5GIpk6cH55ELlNSocLIHl8gfZmpQB7sltiI=:403 Forbidden </code>)
```

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glue_1.4.2     aws.s3_0.3.21  dplyr_1.0.7    sparklyr_1.7.1
```

**Comment by edgararuiz** [comment]
Hi, This seems to be an access rights issue: 
```
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD 
```
 Can you try connecting to S3 via another method, but using the exact same credentials?

**Comment by GitHunter0** [comment]
> Hi, This seems to be an access rights issue:

Hey @edgararuiz , that's what I thought initially, but this procedure with `aws.s3` package works smoothly:
```
library(tidyverse)
library(data.table)
# install.packages("aws.s3")
library(aws.s3)

Sys.setenv(
  "AWS_ACCESS_KEY_ID" = "hidden",
  "AWS_SECRET_ACCESS_KEY" = "hidden",
  "AWS_DEFAULT_REGION" = "us-east-2"
)

# Export table to a temporary file path
obj_name = "mtcars_imported.csv"
filepath = file.path(tempdir(), obj_name)
data.table::fwrite(mtcars[1:2], filepath)

# display S3 buckets 
aws.s3::bucketlist()

# Upload file to S3 bucket 
bucket_and_folder = "bucket_name/folder_name"
aws.s3::put_object(
  file = filepath, 
  object = obj_name, 
  bucket = bucket_and_folder 
)

# Read csv files from S3 bucket 
df_imported <- aws.s3::s3read_using(
  data.table::fread, 
  object = glue("s3://{bucket_and_folder}/{obj_name}") 
)
print(df_imported)
```

**Comment by edgararuiz** [comment]
Ok, and just to confirm, the test with `aws.s3` was made in the same machine as the one used for the Spark test?

**Comment by wangyaopw** [comment]
@GitHunter0 

I am having the same issue now. Did you figure out what the cause was? 

Thanks

**Comment by GitHunter0** [comment]
> I am having the same issue now. Did you figure out what the cause was?

Hey @wangyaopw , unfortunately I think I didn't...

**Comment by DoyleDev** [comment]
@GitHunter0 any update here? Also having the same issue

**Comment by GitHunter0** [comment]
Hey @DoyleDev , see with @edgararuiz , I don't have a follow up here, we are waiting for the developers feedback.

**Comment by edgararuiz** [comment]
What version of Databricks are you using?

**Comment by DoyleDev** [comment]
@edgararuiz The runtime version? I have tried 12.2LTS as well as 13.1

**Comment by sayedabdallah** [comment]
the same issue on emr serverless 7.5 with pyspark.

**Comment by tarenrug** [comment]
I managed to solve a similar issue by specifying the two following additional pieces of configuration:

    .config("spark.hadoop.fs.s3a.endpoint", "link_to_your_s3_endpoint") \
    .config("spark.hadoop.fs.s3a.signing-algorithm", "AWSS3V4SignerType")
