### ISSUE TITLE
Cannot arrange and summarize spark data frame

### ISSUE THREAD

**Issue by vvomhoff** [sparklyr/sparklyr#3257]
Hey all,

we encountered an issue concerning arranging a spark data frame based on a column and then summarize it. We tried multiple times changing the order of the methods or use other functions in summarize, but it did not work for us. Below is an example in dplyr what we are trying to achieve and an example in spark.

```r
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tidyverse)

spark_version <- "3.2.1"
spark_version
#> [1] "3.2.1"
version$version.string
#> [1] "R version 4.2.0 (2022-04-22)"
packageVersion("sparklyr")
#> [1] '1.7.5'
packageVersion("tidyverse")
#> [1] '1.3.1'

config <- spark_config()
sc <- spark_connect(master = "spark://172.16.50.100:7077", config = config)

# Create an example data frame

df <- data.frame(time = seq(1:20), id = c(rep(101, 7), rep(102,4), rep(103, 9)),
                 group = c(1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5, 6, 6, 7, 7, 7),
                 name = c("S", "C", "D", "S", "C", "S", "D", "C", "D", "C", "D", "S", "U", "C", "D", "S", "S", "D", "U", "C")) %>%  sample_n(20)

df
#>    time  id group name
#> 1     1 101     1    S
#> 2     7 101     2    D
#> 3    20 103     7    C
#> 4     9 102     3    D
#> 5    19 103     7    U
#> 6     4 101     2    S
#> 7    17 103     6    S
#> 8     3 101     1    D
#> 9    18 103     7    D
#> 10   13 103     5    U
#> 11   15 103     5    D
#> 12    5 101     2    C
#> 13   14 103     5    C
#> 14   12 103     5    S
#> 15   16 103     6    S
#> 16    2 101     1    C
#> 17    8 102     3    C
#> 18   10 102     4    C
#> 19   11 102     4    D
#> 20    6 101     2    S

# Execute using dplyr (works)

df %>% 
  arrange(time) %>% 
  filter(id == "101") %>% 
  group_by(id, group) %>%
  summarize(session = paste(name, collapse = " "))
#> `summarise()` has grouped output by 'id'. You can override using the `.groups`
#> argument.
#> # A tibble: 2 × 3
#> # Groups:   id [1]
#>      id group session
#>   <dbl> <dbl> <chr>  
#> 1   101     1 S C D  
#> 2   101     2 S C S D

# Execute using sparklyr (fails)

sdf_test <- sdf_copy_to(sc, df, name = "sdf_test")

sdf_test %>%
  arrange(time) %>% 
  filter(id == "101") %>% 
  group_by(id, group) %>%
  summarize(session = paste(collect_list(name)))
#> `summarise()` has grouped output by 'id'. You can override using the `.groups`
#> argument.
#> Error: org.apache.spark.sql.AnalysisException: cannot resolve 'time' given input columns: [sdf_test.group, sdf_test.id, session]; line 5 pos 9;
#> 'Sort ['time ASC NULLS FIRST], true
#> +- Aggregate [id#15, group#16], [id#15, group#16, concat_ws( , collect_list(name#17, 0, 0)) AS session#104]
#>    +- Filter (id#15 = cast(101 as double))
#>       +- SubqueryAlias sdf_test
#>          +- View (`sdf_test`, [time#14,id#15,group#16,name#17])
#>             +- LogicalRDD [time#14, id#15, group#16, name#17], false
#> 
#>  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:54)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:179)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:175)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUpWithPruning$2(TreeNode.scala:535)
#>  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUpWithPruning(TreeNode.scala:535)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUpWithPruning$1(TreeNode.scala:532)
#>  at scala.collection.immutable.List.map(List.scala:293)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:595)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUpWithPruning(TreeNode.scala:532)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$transformExpressionsUpWithPruning$1(QueryPlan.scala:181)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:193)
#>  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:193)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:204)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$3(QueryPlan.scala:209)
#>  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
#>  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
#>  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
#>  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
#>  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
#>  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:209)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$4(QueryPlan.scala:214)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:323)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:214)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUpWithPruning(QueryPlan.scala:181)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:161)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:175)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1$adapted(CheckAnalysis.scala:94)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:263)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:94)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:91)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:182)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:205)
#>  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:202)
#>  at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:88)
#>  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
#>  at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:196)
#>  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
#>  at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:196)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:88)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:86)
#>  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:78)
#>  at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:98)
#>  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
#>  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
#>  at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
#>  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:498)
#>  at sparklyr.Invoke.invoke(invoke.scala:161)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:141)
#>  at sparklyr.StreamHandler.read(stream.scala:62)
#>  at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:60)
#>  at scala.util.control.Breaks.breakable(Breaks.scala:42)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:41)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
#>  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
```

Any ideas what happens here or what we are doing wrong?

```r
utils::sessionInfo()
#> R version 4.2.0 (2022-04-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.4 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
#>  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
#>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
#> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] forcats_0.5.1   stringr_1.4.0   dplyr_1.0.9     purrr_0.3.4    
#>  [5] readr_2.1.2     tidyr_1.2.0     tibble_3.1.7    ggplot2_3.3.6  
#>  [9] tidyverse_1.3.1 sparklyr_1.7.5 
#> 
#> loaded via a namespace (and not attached):
#>  [1] lubridate_1.8.0   forge_0.2.0       assertthat_0.2.1  rprojroot_2.0.3  
#>  [5] digest_0.6.29     utf8_1.2.2        R6_2.5.1          cellranger_1.1.0 
#>  [9] backports_1.4.1   reprex_2.0.1      evaluate_0.15     httr_1.4.3       
#> [13] highr_0.9         pillar_1.7.0      rlang_1.0.2       readxl_1.4.0     
#> [17] rstudioapi_0.13   blob_1.2.3        rmarkdown_2.14    config_0.3.1     
#> [21] r2d3_0.2.6        htmlwidgets_1.5.4 munsell_0.5.0     broom_0.8.0      
#> [25] compiler_4.2.0    modelr_0.1.8      xfun_0.31         askpass_1.1      
#> [29] pkgconfig_2.0.3   base64enc_0.1-3   htmltools_0.5.2   openssl_2.0.0    
#> [33] tidyselect_1.1.2  fansi_1.0.3       crayon_1.5.1      tzdb_0.3.0       
#> [37] dbplyr_2.1.1      withr_2.5.0       grid_4.2.0        jsonlite_1.8.0   
#> [41] gtable_0.3.0      lifecycle_1.0.1   DBI_1.1.2         magrittr_2.0.3   
#> [45] scales_1.2.0      cli_3.3.0         stringi_1.7.6     fs_1.5.2         
#> [49] xml2_1.3.3        ellipsis_0.3.2    generics_0.1.2    vctrs_0.4.1      
#> [53] tools_4.2.0       glue_1.6.2        hms_1.1.1         parallel_4.2.0   
#> [57] fastmap_1.1.0     yaml_2.3.5        colorspace_2.0-3  rvest_1.0.2      
#> [61] knitr_1.39        haven_2.5.0
```

**Comment by edgararuiz** [comment]
Hi, I wonder if this has to do with the 1.7.5's integration with `dbplyr` . Would you mind testing that with the dev version of `sparklyr`?  To install it use: `remotes::install_github("sparklyr/sparklyr")`

**Comment by vvomhoff** [comment]
Unfortunately, the error still occurs.

``` r
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tidyverse)

spark_version <- "3.2.1"
spark_version
#> [1] "3.2.1"
version$version.string
#> [1] "R version 4.2.0 (2022-04-22)"
packageVersion("sparklyr")
#> [1] '1.7.5.9001'
packageVersion("tidyverse")
#> [1] '1.3.1'

config <- spark_config()
sc <- spark_connect(master = "spark://172.16.50.100:7077", config = config)

# Create an example data frame

df <- data.frame(time = seq(1:20), id = c(rep(101, 7), rep(102,4), rep(103, 9)),
                 group = c(1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5, 6, 6, 7, 7, 7),
                 name = c("S", "C", "D", "S", "C", "S", "D", "C", "D", "C", "D", "S", "U", "C", "D", "S", "S", "D", "U", "C")) %>%  sample_n(20)

df
#>    time  id group name
#> 1    10 102     4    C
#> 2    19 103     7    U
#> 3    15 103     5    D
#> 4     5 101     2    C
#> 5     8 102     3    C
#> 6     6 101     2    S
#> 7    18 103     7    D
#> 8    11 102     4    D
#> 9     9 102     3    D
#> 10   12 103     5    S
#> 11    2 101     1    C
#> 12    3 101     1    D
#> 13   17 103     6    S
#> 14   16 103     6    S
#> 15    4 101     2    S
#> 16    7 101     2    D
#> 17   14 103     5    C
#> 18    1 101     1    S
#> 19   13 103     5    U
#> 20   20 103     7    C

# Execute using dplyr (works)

df %>% 
  arrange(time) %>% 
  filter(id == "101") %>% 
  group_by(id, group) %>%
  summarize(session = paste(name, collapse = " "))
#> `summarise()` has grouped output by 'id'. You can override using the `.groups`
#> argument.
#> # A tibble: 2 × 3
#> # Groups:   id [1]
#>      id group session
#>   <dbl> <dbl> <chr>  
#> 1   101     1 S C D  
#> 2   101     2 S C S D

# Execute using sparklyr (fails)

sdf_test <- sdf_copy_to(sc, df, name = "sdf_test")

sdf_test %>%
  arrange(time) %>% 
  filter(id == "101") %>% 
  group_by(id, group) %>%
  summarize(session = paste(collect_list(name)))
#> `summarise()` has grouped output by 'id'. You can override using the `.groups`
#> argument.
#> Error: org.apache.spark.sql.AnalysisException: cannot resolve 'time' given input columns: [sdf_test.group, sdf_test.id, session]; line 5 pos 9;
#> 'Sort ['time ASC NULLS FIRST], true
#> +- Aggregate [id#15, group#16], [id#15, group#16, concat_ws( , collect_list(name#17, 0, 0)) AS session#104]
#>    +- Filter (id#15 = cast(101 as double))
#>       +- SubqueryAlias sdf_test
#>          +- View (`sdf_test`, [time#14,id#15,group#16,name#17])
#>             +- LogicalRDD [time#14, id#15, group#16, name#17], false
#> 
#>  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:54)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:179)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:175)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUpWithPruning$2(TreeNode.scala:535)
#>  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUpWithPruning(TreeNode.scala:535)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUpWithPruning$1(TreeNode.scala:532)
#>  at scala.collection.immutable.List.map(List.scala:293)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:595)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUpWithPruning(TreeNode.scala:532)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$transformExpressionsUpWithPruning$1(QueryPlan.scala:181)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:193)
#>  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:193)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:204)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$3(QueryPlan.scala:209)
#>  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
#>  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
#>  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
#>  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
#>  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
#>  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:209)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$4(QueryPlan.scala:214)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:323)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:214)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUpWithPruning(QueryPlan.scala:181)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:161)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:175)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1$adapted(CheckAnalysis.scala:94)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:263)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:94)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:91)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:182)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:205)
#>  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:202)
#>  at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:88)
#>  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
#>  at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:196)
#>  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
#>  at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:196)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:88)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:86)
#>  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:78)
#>  at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:98)
#>  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
#>  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
#>  at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
#>  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:498)
#>  at sparklyr.Invoke.invoke(invoke.scala:161)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:141)
#>  at sparklyr.StreamHandler.read(stream.scala:62)
#>  at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:60)
#>  at scala.util.control.Breaks.breakable(Breaks.scala:42)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:41)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
#>  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

utils::sessionInfo()
#> R version 4.2.0 (2022-04-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.4 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
#>  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
#>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
#> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] forcats_0.5.1       stringr_1.4.0       dplyr_1.0.9        
#>  [4] purrr_0.3.4         readr_2.1.2         tidyr_1.2.0        
#>  [7] tibble_3.1.7        ggplot2_3.3.6       tidyverse_1.3.1    
#> [10] sparklyr_1.7.5.9001
#> 
#> loaded via a namespace (and not attached):
#>  [1] lubridate_1.8.0   forge_0.2.0       assertthat_0.2.1  rprojroot_2.0.3  
#>  [5] digest_0.6.29     utf8_1.2.2        R6_2.5.1          cellranger_1.1.0 
#>  [9] backports_1.4.1   reprex_2.0.1      evaluate_0.15     httr_1.4.3       
#> [13] highr_0.9         pillar_1.7.0      rlang_1.0.2       readxl_1.4.0     
#> [17] rstudioapi_0.13   blob_1.2.3        rmarkdown_2.14    config_0.3.1     
#> [21] r2d3_0.2.6        htmlwidgets_1.5.4 munsell_0.5.0     broom_0.8.0      
#> [25] compiler_4.2.0    modelr_0.1.8      xfun_0.31         askpass_1.1      
#> [29] pkgconfig_2.0.3   base64enc_0.1-3   htmltools_0.5.2   openssl_2.0.0    
#> [33] tidyselect_1.1.2  fansi_1.0.3       crayon_1.5.1      tzdb_0.3.0       
#> [37] dbplyr_2.1.1      withr_2.5.0       grid_4.2.0        jsonlite_1.8.0   
#> [41] gtable_0.3.0      lifecycle_1.0.1   DBI_1.1.2         magrittr_2.0.3   
#> [45] scales_1.2.0      cli_3.3.0         stringi_1.7.6     fs_1.5.2         
#> [49] xml2_1.3.3        ellipsis_0.3.2    generics_0.1.2    vctrs_0.4.1      
#> [53] tools_4.2.0       glue_1.6.2        hms_1.1.1         parallel_4.2.0   
#> [57] fastmap_1.1.0     yaml_2.3.5        colorspace_2.0-3  rvest_1.0.2      
#> [61] knitr_1.39        haven_2.5.0
```

**Comment by edgararuiz** [comment]
Hi, I just realized that the field use for `arrange()` is one that does not end up in the final result. If I run this, it works: 

```
sdf_test %>%
  arrange(id) %>% 
  filter(id == "101") %>% 
  group_by(id, group) %>%
  summarize(session = paste(collect_list(name)))
``` 

In other words, would this really be a bug? Would there be an instance where we need to order, in a previous step and then group by something else that does not impact the result?

**Comment by vvomhoff** [comment]
We already found out that if the field we want to arrange is in the `group_by()`, it works. So `arrange(id)` works, because we do `group_by(id).` But we do not want to arrange on id but on time. 

We built the sql query that we exptected to achieve. So by doing this:
``` r
sdf_test %>%
  arrange(time) %>% 
  filter(id == "101") %>% 
  group_by(id, group) %>%
  summarize(session = paste(collect_list(name)))
```
We expected something similar to this sql query and result:
``` r
sdf_sql_test <- sdf_sql(sc, "SELECT id,
                                   CONCAT_WS(' ', Collect_list(name)) AS session
                            FROM   (SELECT *
                                    FROM   sdf_test
                                    WHERE  id = 101
                                    ORDER  BY time)
                            GROUP  BY group,
                                      id")
sdf_sql_test
#> # Source: spark<?> [?? x 2]
#>      id session
#>   <dbl> <chr>  
#> 1   101 S C D  
#> 2   101 S C S D
```
How can we do this with sparklyr?

**Comment by edgararuiz** [comment]
Thank you for that follow up. Normal `dbplyr` translations do not support `collapse` but your tip about using `COLLECT_LIST` may make it work. I'll take a look at that.
