### ISSUE TITLE
spark_apply UDF Error

### ISSUE THREAD

**Issue by EKtheSage** [sparklyr/sparklyr#3282]
Am I using UDF wrong? Why does anonymous function work but not function defined outside of spark_apply?

```
library(sparklyr)
sc = spark_connect(method = 'databricks')
tbl_mtcars = copy_to(sc, mtcars, 'spark_mtcars', overwrite  = TRUE)

# this works
spark_apply(tbl_mtcars, function(x) {x['cyl_half'] = x[['cyl']] / 2})

# Source: spark<?> [?? x 1]
   result
    <dbl>
 1      3
 2      3
 3      2
 4      3
 5      4
 6      3
 7      4
 8      2
 9      2
10      3
# … with more rows

# this doesn't
half = function(x) { x / 2}
spark_apply(tbl_mtcars, function(x) {x['cyl_half'] = half(x[['cyl']]})

# Error : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 603.0 failed 4 times, most recent failure: Lost task 0.3 in stage 603.0 (TID 1128) (10.2.13.9 executor 5): java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:83)
	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:138)

Some(<code style = 'font-size:10pt'> Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 603.0  failed 4 times, most recent failure: Lost task 0.3 in stage 603.0 (TID 1128) (10.2.13.9 executor 5): java.lang.Exception: sparklyr worker  rscript failure with status 255, check worker logs for details. </code>)


```

**Comment by edgararuiz** [comment]
Hi, try defining your function inside the function sent to `spark_apply()`, this works:

```r
spark_apply(
  tbl_mtcars, 
  function(x) {
    half <- function(x) { x / 2}  
    x['cyl_half'] = half(x[['cyl']])
    }
  )
```

**Comment by EKtheSage** [comment]
Thank you. this could be a solution. We wanted to make the `spark_apply` call less cluttered by defining the function outside of the call. But I guess there's no way around that.
