### ISSUE TITLE
Error: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Circ638** [sparklyr/sparklyr#3288]
Error when loading large datasets more than 200 MB in size.
**Code:**

options(java.parameters = "-Xms8g")
options(java.parameters = "-Xmx8g") 
options(java.parameters = "-Xmx4g") 
.jinit(parameters=c("-Xms1g","-Xmx4g"))
gc()
library(RJDBC)
library(rJava)
library(sparklyr)

library(dplyr)

options(sparklyr.console.log = TRUE)
databricks_connect_spark_home <- '/usr/local/lib/python3.8/site-packages/pyspark'
Sys.setenv(SPARK_HOME = '/usr/local/lib/python3.8/site-packages/pyspark')
config <- spark_config()
config$spark.executor.memory <- '16G'
config$spark.shell.driver.memory<-'16G'
config$spark.shell.executor.memory<-'16G'
config$spark.driver.maxResultSize<-'16G'

config$spark.executor.memory <- '16G'
config$spark.shell.driver.memory<-'16G'
config$spark.shell.executor.memory<-'16G'
config$spark.driver.maxResultSize<-'16G'

config$spark.driver.memory<-"64G"

config$spark.executor.memoryOverhead <- "16g"
data <- some large dataset.
sc <- spark_connect(method = "databricks",config = config, spark_home = databricks_connect_spark_home)
gc()
cars_tbl <- copy_to(sc, data, overwrite = TRUE)

**Session Info:**

R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS: /opt/microsoft/ropen/3.5.1/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.5.1/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                  LC_TIME=en_US.UTF-8          
 [4] LC_COLLATE=en_US.UTF-8        LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8           LC_ADDRESS=en_US.UTF-8       
[10] LC_TELEPHONE=en_US.UTF-8      LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.9          sparklyr_1.7.7       RJDBC_0.2-10         rJava_0.9-10        
[5] DBI_1.1.0            RevoUtils_11.0.1     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        pillar_1.7.0      compiler_3.5.1    dbplyr_2.2.0      r2d3_0.2.3       
 [6] base64enc_0.1-3   tools_3.5.1       odbc_1.2.2        digest_0.6.27     bit_4.0.4        
[11] jsonlite_1.5      lifecycle_1.0.1   tibble_3.0.3      pkgconfig_2.0.2   rlang_1.0.2      
[16] cli_3.3.0         rstudioapi_0.11   parallel_3.5.1    yaml_2.1.19       withr_2.1.2      
[21] httr_1.4.2        askpass_1.0       generics_0.1.0    vctrs_0.4.1       htmlwidgets_1.5.1
[26] hms_0.4.2         rprojroot_1.3-2   bit64_0.9-7       tidyselect_1.1.2  glue_1.6.2       
[31] forge_0.2.0       R6_2.2.2          fansi_0.4.0       tidyr_1.2.0       purrr_0.3.4      
[36] blob_1.2.0        magrittr_1.5      backports_1.1.2   ellipsis_0.3.2    htmltools_0.5.1.1
[41] assertthat_0.2.0  config_0.3        utf8_1.1.4        openssl_1.3       crayon_1.3.4     

**Error: java.lang.OutOfMemoryError: GC overhead limit exceeded**
	at sun.nio.cs.UTF_8.newDecoder(UTF_8.java:68)
	at java.lang.StringCoding.decode(StringCoding.java:213)
	at java.lang.String.<init>(String.java:463)
	at java.lang.String.<init>(String.java:515)
	at sparklyr.RUtils$.$anonfun$unserializeColumn$1(rutils.scala:121)
	at sparklyr.RUtils$.$anonfun$unserializeColumn$1$adapted(rutils.scala:68)
	at sparklyr.RUtils$$$Lambda$2740/1321215515.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.TraversableLike$$Lambda$35/2043318969.apply(Unknown Source)
	at scala.collection.immutable.NumericRange.foreach(NumericRange.scala:75)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at sparklyr.RUtils$.unserializeColumn(rutils.scala:67)
	at sparklyr.Utils$.$anonfun$parallelize$1(utils.scala:211)
	at sparklyr.Utils$$$Lambda$2739/1202052677.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.TraversableLike$$Lambda$35/2043318969.apply(Unknown Source)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at sparklyr.Utils$.parallelize(utils.scala:205)
	at sparklyr.Utils.parallelize(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:161)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:141)

---

your brief description of the problem

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)

# your reproducible example here
```

**Comment by edgararuiz** [comment]
> data <- some large dataset.
sc <- spark_connect(method = "databricks",config = config, spark_home = databricks_connect_spark_home)
gc()
cars_tbl <- copy_to(sc, data, overwrite = TRUE)

Hi, instead of uploading the data form R, can the Spark session just read the files directly? Or is the data created in R?
