### ISSUE TITLE
Databricks connection error `There is no Credential Scope`

### ISSUE THREAD

**Issue by wurli** [sparklyr/sparklyr#3318]
Using RStudio server on databricks I get the following error:

``` r
sparklyr::spark_connect(method = "databricks")
#> Error in value[[3L]](cond) : 
#>  Failed to start sparklyr backend: java.util.concurrent.ExecutionException: org.apache.spark.SparkException: There is no Credential Scope. 
#>	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
#>	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
#>	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
#>	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:135)
#>	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2344)
#>	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316)
#>	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
#>	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
#>	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
#>	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
#>	at com.google.common.cache.Loc
#> In addition: Warning messages:
#> 1: In file.create(to[okay]) :
#>   cannot create file '/usr/local/lib/R/site-library/sparklyr/java//sparklyr-2.2-2.11.jar', reason 'Permission denied'
#> 2: In file.create(to[okay]) :
#>  cannot create file '/usr/local/lib/R/site-library/sparklyr/java//sparklyr-2.1-2.11.jar', reason'Permission denied'
```

Grateful for any help with this. I'm new to databricks and I really don't know where to begin with this error!

Here is my session info:

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.2 Patched (2022-11-10 r83330)
#>  os       Ubuntu 20.04.5 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  C
#>  ctype    en_US.UTF-8
#>  tz       Etc/UTC
#>  date     2023-02-22
#>  pandoc   2.17.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cachem        1.0.6   2021-08-19 [3] CRAN (R 4.2.2)
#>  callr         3.7.3   2022-11-02 [3] CRAN (R 4.2.2)
#>  cli           3.4.1   2022-09-23 [3] CRAN (R 4.2.2)
#>  crayon        1.5.2   2022-09-29 [3] CRAN (R 4.2.2)
#>  devtools      2.4.5   2022-10-11 [3] CRAN (R 4.2.2)
#>  digest        0.6.30  2022-10-18 [3] CRAN (R 4.2.2)
#>  ellipsis      0.3.2   2021-04-29 [3] CRAN (R 4.2.2)
#>  evaluate      0.18    2022-11-07 [3] CRAN (R 4.2.2)
#>  fastmap       1.1.0   2021-01-25 [3] CRAN (R 4.2.2)
#>  fs            1.5.2   2021-12-08 [3] CRAN (R 4.2.2)
#>  glue          1.6.2   2022-02-24 [3] CRAN (R 4.2.2)
#>  highr         0.9     2021-04-16 [3] CRAN (R 4.2.2)
#>  htmltools     0.5.3   2022-07-18 [3] CRAN (R 4.2.2)
#>  htmlwidgets   1.5.4   2021-09-08 [3] CRAN (R 4.2.2)
#>  httpuv        1.6.6   2022-09-08 [3] CRAN (R 4.2.2)
#>  knitr         1.40    2022-08-24 [3] CRAN (R 4.2.2)
#>  later         1.3.0   2021-08-18 [3] CRAN (R 4.2.2)
#>  lifecycle     1.0.3   2022-10-07 [3] CRAN (R 4.2.2)
#>  magrittr      2.0.3   2022-03-30 [3] CRAN (R 4.2.2)
#>  memoise       2.0.1   2021-11-26 [3] CRAN (R 4.2.2)
#>  mime          0.12    2021-09-28 [3] CRAN (R 4.2.2)
#>  miniUI        0.1.1.1 2018-05-18 [3] CRAN (R 4.2.2)
#>  pkgbuild      1.3.1   2021-12-20 [3] CRAN (R 4.2.2)
#>  pkgload       1.3.1   2022-10-28 [3] CRAN (R 4.2.2)
#>  prettyunits   1.1.1   2020-01-24 [3] CRAN (R 4.2.2)
#>  processx      3.8.0   2022-10-26 [3] CRAN (R 4.2.2)
#>  profvis       0.3.7   2020-11-02 [3] CRAN (R 4.2.2)
#>  promises      1.2.0.1 2021-02-11 [3] CRAN (R 4.2.2)
#>  ps            1.7.2   2022-10-26 [3] CRAN (R 4.2.2)
#>  purrr         0.3.5   2022-10-06 [3] CRAN (R 4.2.2)
#>  R6            2.5.1   2021-08-19 [3] CRAN (R 4.2.2)
#>  Rcpp          1.0.9   2022-07-08 [3] CRAN (R 4.2.2)
#>  remotes       2.4.2   2021-11-30 [3] CRAN (R 4.2.2)
#>  reprex        2.0.2   2022-08-17 [3] CRAN (R 4.2.2)
#>  rlang         1.0.6   2022-09-24 [3] CRAN (R 4.2.2)
#>  rmarkdown     2.18    2022-11-09 [3] CRAN (R 4.2.2)
#>  rstudioapi    0.14    2022-08-22 [3] CRAN (R 4.2.2)
#>  sessioninfo   1.2.2   2021-12-06 [3] CRAN (R 4.2.2)
#>  shiny         1.7.3   2022-10-25 [3] CRAN (R 4.2.2)
#>  stringi       1.7.8   2022-07-11 [3] CRAN (R 4.2.2)
#>  stringr       1.4.1   2022-08-20 [3] CRAN (R 4.2.2)
#>  urlchecker    1.0.1   2021-11-30 [3] CRAN (R 4.2.2)
#>  usethis       2.1.6   2022-05-25 [3] CRAN (R 4.2.2)
#>  withr         2.5.0   2022-03-03 [3] CRAN (R 4.2.2)
#>  xfun          0.34    2022-10-18 [3] CRAN (R 4.2.2)
#>  xtable        1.8-4   2019-04-21 [3] CRAN (R 4.2.2)
#>  yaml          2.3.6   2022-10-18 [3] CRAN (R 4.2.2)
#> 
#>  [1] /home/jacob.scott@education.gov.uk/R/x86_64-pc-linux-gnu-library/4.2
#>  [2] /databricks/spark/R/lib
#>  [3] /usr/local/lib/R/site-library
#>  [4] /usr/lib/R/site-library
#>  [5] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

**Comment by wurli** [comment]
This was using databricks runtime 12.1. Experimenting a bit more using some clues from #3101, I've found that rolling back my runtime to 7.3 allows me to connect - albeit still with a warning:
``` r
SparkR::sparkR.session()
#> Spark package found in SPARK_HOME: /databricks/spark

sc <- sparklyr::spark_connect(method = "databricks")
#> Warning messages:
#> 1: In file.create(to[okay]) :
#>   cannot create file '/usr/local/lib/R/site-library/sparklyr/java//sparklyr-2.2-2.11.jar', reason #> 'Permission denied'
#> 2: In file.create(to[okay]) :
#>   cannot create file '/usr/local/lib/R/site-library/sparklyr/java//sparklyr-2.1-2.11.jar', reason 'Permission denied'
```

**Comment by zacdav-db** [comment]
Credential scopes are indeed related to Unity Catalog. I believe there is an outstanding Databricks engineering ticket to investigate this.

**Comment by RobinLoche** [comment]
I opened a case at Databricks, and apparently they fixed the issue (it effectively is something between Sparklyr and Unity Catalog) and it should be deployed in runtimes >= 11.3 during the next release (normally at the end of April).

**Comment by CarlaFernandez** [comment]
Hello, did you manage to solve the error using runtime 11.3 with Unity Catalog and databricks-connect? We've tried moving to the next dbconnect version (13.0.0) with runtime 13 but it is not a good option for us at the moment due to its limitations.

**Comment by zacdav-db** [comment]
@wurli if you don't encounter this issue anymore (due to fix) its probably worth closing since the root cause is Databricks related - nothing {sparklyr} related.

**Comment by smingerson** [comment]
Can confirm this was a bug in Databricks and their Unity Catalog, and unrelated to sparklyr itself.

**Comment by wurli** [comment]
Thanks for your responses. If this is due to a bug on the Databricks side then happy for this issue to be closed. However I’d suggest it’s left open until the bug is addressed by Databricks for the benefit of anyone else who encounters the issue.

Thanks!

**Comment by zacdav-db** [comment]
I'd suggest just closing it as this repo isn't going to be where Databricks tracks this issue and it's confirmed to be unrelated to sparklyr.

**Comment by wurli** [comment]
Closing since this is an issue on Databricks' side which is, apparently, fixed in more recent versions of the runtime.

**Comment by kmishra9** [comment]
Just ran into this again (and there are a few other similar unresolved threads floating around on the internet: [community thread 1](https://community.databricks.com/t5/data-governance/sparkexception-there-is-no-credential-scope/td-p/38767), [thread 2](https://community.databricks.com/t5/data-engineering/bug-unity-catalog-incompatible-with-sparklyr-in-rstudio-on/td-p/17032), [thread 3](https://stackoverflow.com/questions/74575249/sparklyr-multiple-databricks-notebooks-second-connections-fails-with-org-apache)) on Runtime "13.2 ML (includes Apache Spark 3.4.0, Scala 2.12)". 

It may be useful to have some helpful verbosity around possible things to try here (i.e. change the runtime) for folks who run into this when using `method = 'databricks'`, as I was at a complete loss. In the meantime, I'll try playing with the runtime version to see if anything helps and leave my findings here
