### ISSUE TITLE
Collect UDT with arrow enabled 

### ISSUE THREAD

**Issue by gregleleu** [sparklyr/sparklyr#3326]
Working with a DataFrame that has UDT columns:
* with arrow disabled: on collect we get a list-column of jobj objects
* with arrow enabled: on collect we get an error

This also impact the connection pane in RStudio (error when trying to view the schema of an object with UDT)

Without arrow:
```r
library(sparklyr)
library(apache.sedona)
spark_version <- "3.3.1"
sc <- spark_connect(master = "local", version = spark_version)
geojson_sdf <- sc %>% spark_read_geojson(test_data("testPolygon.json"), name = "test")
a <- geojson_sdf %>% collect() 
a$geometry[[1]]

## <jobj[4132]>
##  org.locationtech.jts.geom.Polygon
##  POLYGON ((-87.621765 34.873444, -87.617535 34.873369, -87.6123 34.873337, -87.604049 34.873303, -87.604033 34.872316, -87.60415 34.867502, -87.604218 34.865687, -87.604409 34.858537, -87.604018 34.851336, -87.603716 34.844829, -87.603696 34.844307, -87.603673 34.841884, -87.60372 34.841003, -87.603879 34.838423, -87.603888 34.837682, -87.603889 34.83763, -87.613127 34.833938, -87.616451 34.832699, -87.621041 34.831431, -87.621056 34.831526, -87.62112 34.831925, -87.621603 34.8352, -87.62158 34.836087, -87.621383 34.84329, -87.621359 34.844438, -87.62129 34.846387, -87.62119 34.85053, -87.62144 34.865379, -87.621765 34.873444))

```
Connection pane
<img width="460" alt="image" src="https://user-images.githubusercontent.com/33321678/225710301-ca58da99-8ff6-4624-a53e-198526487673.png">

With arrow
```r
library(arrow)
a <- geojson_sdf %>% collect() 


Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 15.0 failed 1 times, most recent failure: Lost task 0.0 in stage 15.0 (TID 15) (localhost executor driver): java.lang.UnsupportedOperationException: Unsupported data type: binary
	at org.apache.spark.sql.errors.QueryExecutionErrors$.unsupportedDataTypeError(QueryExecutionErrors.scala:930)
	at org.apache.spark.sql.util.ArrowUtils$.toArrowType(ArrowUtils.scala:59)
	at org.apache.spark.sql.util.ArrowUtils$.toArrowField(ArrowUtils.scala:110)
	at org.apache.spark.sql.util.ArrowUtils$.$anonfun$toArrowSchema$1(ArrowUtils.scala:139)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:102)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at org.apache.spark.sql.types.StructType.map(StructType.scala:102)
	at org.apache.spark.sql.util.ArrowUtils$.toArrowSchema(ArrowUtils.scala:138)
	at org.apache.spark.sql.util.__THIS_IS_THE_ROAD_TO_CLOWNTOWN__ArrowUtils$.$anonfun$toArrowSchema$1(clowntown.scala:8)
	at sparklyr.ArrowConvertersImpl.toBatchIterator(arrowconverters.scala:103)
	at sparklyr.ArrowConvertersImpl.toBatchIterator(arrowconverters.scala:67)
	at sparklyr.ArrowConverters$.$anonfun$toArrowDataset$1(arrowconverters.scala:249)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:201)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```
Connection pane leads to
<img width="279" alt="image" src="https://user-images.githubusercontent.com/33321678/225710388-f6fb9b70-afa6-4358-86c1-2cdcaea6dad6.png">

**Comment by edgararuiz** [comment]
Where is `test_data()` coming from? I'm trying to recreate

**Comment by gregleleu** [comment]
It's a helper in the sedona tests, you can just grab the file here: https://github.com/apache/sedona/tree/master/core/src/test/resources

**Comment by gregleleu** [comment]
It doesn't happen anymore with Spark 3.4.0, and now the column is collected as a binary column (not a jobj pointer).
(Still the same on 3.3.1)
