### ISSUE TITLE
Use multiple sdf as input parameter for spark_apply

### ISSUE THREAD

**Issue by emmayang** [sparklyr/sparklyr#3446]
We have a function inside our customer library in native R, which basically check & combines & merge couple of native data.table together. We tried to execute this function in Spark cluster with `spark_apply()`, however seems spark_apply would only accept ONE `x` as input. How can we pass multiple sdf as function input varibles? 

function we need to invoke in `spark_apply` looks like:
```r
merge <- function(df1, df2, df3, df4){
   ...  ### some check logics here
   return c(df1_1, df2_2, df3_3, df4_4)
}
```

And in our code, df1-4 are output from previous calls, and we've successfully converted them from native R object to `tbl_spark` type, via "spark_apply" successfully. However during the last function call, it would need all 4 SDFs as input variables as in above merge function, and we don't know how to pass the values to it. 

We've tried passing these multiple dfs as variables in context, but they're so big and would cause OOM. 
```r
res <- df1 %>% spark_apply(function(df, context) {
  res <- merge_func(df, context$df2, context$df3, context$df4)
  return(res)
}, context = list(
  df2= as.data.table(df2), 
  df3= as.data.table(df3),
  df4= as.data.table(df4)
),
memory = FALSE,
fetch_result_as_sdf = FALSE,
package = FALSE)
```

Sessin info details are:
```r
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16)
 os       Ubuntu 22.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2024-06-26
 rstudio  2023.09.1+494.pro2 Desert Sunflower (server)
 pandoc   3.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 askpass       1.2.0   2023-09-03 [2] CRAN (R 4.3.1)
 cachem        1.0.8   2023-05-01 [2] CRAN (R 4.3.1)
 cli           3.6.2   2023-12-11 [2] CRAN (R 4.3.1)
 DBI           1.2.2   2024-02-16 [2] CRAN (R 4.3.1)
 dbplyr        2.5.0   2024-03-19 [2] CRAN (R 4.3.1)
 devtools      2.4.5   2022-10-11 [2] CRAN (R 4.3.1)
 digest        0.6.35  2024-03-11 [2] CRAN (R 4.3.1)
 dplyr         1.1.4   2023-11-17 [2] CRAN (R 4.3.1)
 ellipsis      0.3.2   2021-04-29 [2] CRAN (R 4.3.1)
 evaluate      0.23    2023-11-01 [2] CRAN (R 4.3.1)
 fansi         1.0.6   2023-12-08 [2] CRAN (R 4.3.1)
 fastmap       1.1.1   2023-02-24 [2] CRAN (R 4.3.1)
 fs            1.6.4   2024-04-25 [2] CRAN (R 4.3.1)
 generics      0.1.3   2022-07-05 [2] CRAN (R 4.3.1)
 glue          1.7.0   2024-01-09 [2] CRAN (R 4.3.1)
 htmltools     0.5.8.1 2024-04-04 [2] CRAN (R 4.3.1)
 htmlwidgets   1.6.4   2023-12-06 [2] CRAN (R 4.3.1)
 httpuv        1.6.15  2024-03-26 [2] CRAN (R 4.3.1)
 httr          1.4.7   2023-08-15 [2] CRAN (R 4.3.1)
 jsonlite      1.8.8   2023-12-04 [2] CRAN (R 4.3.1)
 knitr         1.46    2024-04-06 [2] CRAN (R 4.3.1)
 later         1.3.2   2023-12-06 [2] CRAN (R 4.3.1)
 lifecycle     1.0.4   2023-11-07 [2] CRAN (R 4.3.1)
 magrittr      2.0.3   2022-03-30 [2] CRAN (R 4.3.1)
 memoise       2.0.1   2021-11-26 [2] CRAN (R 4.3.1)
 mime          0.12    2021-09-28 [2] CRAN (R 4.3.1)
 miniUI        0.1.1.1 2018-05-18 [2] CRAN (R 4.3.1)
 openssl       2.1.2   2024-04-21 [2] CRAN (R 4.3.1)
 pillar        1.9.0   2023-03-22 [2] CRAN (R 4.3.1)
 pkgbuild      1.4.4   2024-03-17 [2] CRAN (R 4.3.1)
 pkgconfig     2.0.3   2019-09-22 [2] CRAN (R 4.3.1)
 pkgload       1.3.4   2024-01-16 [2] CRAN (R 4.3.1)
 profvis       0.3.8   2023-05-02 [2] CRAN (R 4.3.1)
 promises      1.3.0   2024-04-05 [2] CRAN (R 4.3.1)
 purrr         1.0.2   2023-08-10 [2] CRAN (R 4.3.1)
 R6            2.5.1   2021-08-19 [2] CRAN (R 4.3.1)
 Rcpp          1.0.12  2024-01-09 [2] CRAN (R 4.3.1)
 remotes       2.5.0   2024-03-17 [2] CRAN (R 4.3.1)
 rlang         1.1.3   2024-01-10 [2] CRAN (R 4.3.1)
 rmarkdown     2.26    2024-03-05 [2] CRAN (R 4.3.1)
 rstudioapi    0.16.0  2024-03-24 [2] CRAN (R 4.3.1)
 sessioninfo   1.2.2   2021-12-06 [2] CRAN (R 4.3.1)
 shiny         1.8.1.1 2024-04-02 [2] CRAN (R 4.3.1)
 sparklyr      1.8.6   2024-04-29 [1] RSPM (R 4.3.1)
 stringi       1.8.4   2024-05-06 [2] CRAN (R 4.3.1)
 stringr       1.5.1   2023-11-14 [2] CRAN (R 4.3.1)
 tibble        3.2.1   2023-03-20 [2] CRAN (R 4.3.1)
 tidyr         1.3.1   2024-01-24 [2] CRAN (R 4.3.1)
 tidyselect    1.2.1   2024-03-11 [2] CRAN (R 4.3.1)
 urlchecker    1.0.1   2021-11-30 [2] CRAN (R 4.3.1)
 usethis       2.2.3   2024-02-19 [2] CRAN (R 4.3.1)
 utf8          1.2.4   2023-10-22 [2] CRAN (R 4.3.1)
 vctrs         0.6.5   2023-12-01 [2] CRAN (R 4.3.1)
 xfun          0.43    2024-03-25 [2] CRAN (R 4.3.1)
 xtable        1.8-4   2019-04-21 [2] CRAN (R 4.3.1)
 yaml          2.3.8   2023-12-11 [2] CRAN (R 4.3.1)
```

**Comment by emmayang** [comment]
@edgararuiz Thank you so much for your reply! We've got similar ideas at the beginning, and also tried yourcode snippet, but it would cause "Object Not Found" exception.

Ideally, we hope below code could work:

```r
res <- df %>% spark_apply(function(sdf,context) {
  df1 = context$df1
  df2 = context$df2
  df3 = context$df3
  ## this function is provided by 3rd party library, that would accepts 4 data.frame as input
  r <- some_function_from_external_lib(sdf, as.data.frame(df1), as.data.frame(df2), as.data.frame(df3))
  return(r)
}, context = list(
  df1 = df1,
  df2 = df2,
  df3 = df3
),
memory = FALSE,
fetch_result_as_sdf = TRUE,
columns = columns,
package = FALSE) 
```

However it produced below exception:
```java
24/07/03 08:59:24 ERROR sparklyr: Session (3931) failed calling sql on 37: java.lang.IllegalArgumentException: Object not found 37
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:115)
	at sparklyr.StreamHandler.read(stream.scala:62)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:60)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:41)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

After reading spark_apply source code, I assume it is looking for the obejct in ObjectMap inside the compiled closure, where it does not exist.
