### ISSUE TITLE
Error in `src_databases()` when connected to Spark through the `Spark Connect` method

### ISSUE THREAD

**Issue by weichisyu** [sparklyr/sparklyr#3461]
Cannot list the database using `src_databases()` when connected to Spark through the `Spark Connect` method.
```R
> pysparklyr::spark_connect_service_start("3.5")
> sc <- spark_connect(
  master = "sc://localhost", 
  method = "spark_connect", 
  version = "3.5"
)
> src_databases(sc)
Error in py_call_impl(x, dots$unnamed, dots$named) : 
  pyspark.errors.exceptions.base.PySparkTypeError: [NOT_LIST_OF_COLUMN_OR_STR] Argument `columns` should be a list[Column].
── R Traceback ──────────────────────────────────────────────
    ▆
 1. └─sparklyr::src_databases(sc)
 2.   ├─sparklyr::sdf_read_column(dbs, "databaseName")
 3.   └─sparklyr:::sdf_read_column.spark_jobj(dbs, "databaseName")
 4.     ├─sparklyr::invoke(sdf, "select", column, list())
 5.     └─pysparklyr:::invoke.spark_pyobj(sdf, "select", column, list())
 6.       └─pysparklyr:::invoke_conn(...)
 7.         └─reticulate::py_call(x, ...)
 8.           └─reticulate:::py_call_impl(x, dots$unnamed, dots$named)
```
I tried to narrow it down and found that the issue might be a bug in `sdf_read_column.spark_jobj()`. 
https://github.com/sparklyr/sparklyr/blob/34daa972f1f9839a430fdf02af8defb8a85ab0ae/R/sdf_wrapper.R#L147

Original code:
```R
> sdf <- spark_dataframe(invoke(hive_context(sc), "sql", "SHOW DATABASES"))
> invoke(sdf, "select","namespace" ,list())
Error in py_call_impl(x, dots$unnamed, dots$named) : 
  pyspark.errors.exceptions.base.PySparkTypeError: [NOT_LIST_OF_COLUMN_OR_STR] Argument `columns` should be a list[Column].
```
Revised code:
```R
> sdf <- spark_dataframe(invoke(hive_context(sc), "sql", "SHOW DATABASES"))
> invoke(sdf, "select", list("namespace"))
- PySpark object
  pyspark.sql.connect.dataframe.DataFrame
  DataFrame[namespace: string]
```
I propose revising the code to:
```R
col_df <- invoke(sdf, "select", list(column))
```

**Comment by weichisyu** [comment]
I tried the revised code in Spark, connected through the default `shell` method, and encountered another error. However, the original code works. It seems that `sdf_read_column.spark_jobj()` should handle these two situations differently.
```R
> sc <- spark_connect(master="local")
> sdf <- spark_dataframe(invoke(hive_context(sc), "sql", "SHOW DATABASES"))
```
Original code
```R
> invoke(sdf, "select","namespace" ,list())

<jobj[17]>
  org.apache.spark.sql.Dataset
  [namespace: string]
```

Revised code
```R
> invoke(sdf, "select", list("namespace"))

Error:
! java.lang.ClassCastException: class java.lang.String cannot be cast to class
  org.apache.spark.sql.Column (java.lang.String is in module java.base of loader 'bootstrap';
  org.apache.spark.sql.Column is in unnamed module of loader 'app')

Run `sparklyr::spark_last_error()` to see the full Spark error (multiple lines)
To use the previous style of error message set `options("sparklyr.simple.errors" = TRUE)`
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace(drop = FALSE)
Backtrace:
    ▆
 1. ├─sparklyr::invoke(sdf, "select", list("namespace"))
 2. └─sparklyr:::invoke.shell_jobj(sdf, "select", list("namespace"))
 3.   ├─sparklyr::invoke_method(...)
 4.   └─sparklyr:::invoke_method.spark_shell_connection(...)
 5.     └─sparklyr:::core_invoke_method(...)
 6.       └─sparklyr:::core_invoke_method_impl(...)
 7.         └─sparklyr:::spark_error(msg)
 8.           └─rlang::abort(message = msg, use_cli_format = TRUE, call = NULL)
> sparklyr::spark_last_error()
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.apache.spark.sql.Column (java.lang.String is in module java.base of loader 'bootstrap'; org.apache.spark.sql.Column is in unnamed module of loader 'app')
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1525)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sparklyr.Invoke.invoke(invoke.scala:161)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:141)
	at sparklyr.StreamHandler.read(stream.scala:62)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:60)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:41)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by edgararuiz** [comment]
Hi! Yes, currently `src_databases()` is not yet supported in the `pysparklyr` extension. You're welcome to open an Issue there to request the functionality: https://github.com/mlverse/pysparklyr/issues

Thanks!

**Comment by weichisyu** [comment]
Hi! According to[ this information](https://sparkfromr.com/using-the-lower-level-invoke-api-to-manipulate-sparks-java-objects-from-r#:~:text=the%20empty%20list()%20at%20the%20end%20of%20the%20%22groupBy%22%20and%20%22agg%22%20invokes.%20This%20is%20needed%20as%20a%20workaround%20some%20Scala%20methods%20take%20String%2C%20String*%20as%20arguments%20and%20sparklyr%20currently%20does%20not%20support%20variable%20parameters.%20We%20can%20pass%20list()%20to%20represent%20an%20empty%20String%5B%5D%20in%20Scala%20as%20the%20needed%20second%20argument.), the use of `list()` here seems to be just a workaround for some Scala methods. I suggest adding a condition to handle cases where the connection method is Spark Connect.
This is because, when using Spark Connect, it calls the [method](https://github.com/apache/spark/blob/ab7aea144da40f7b2ef57ff1d289a9b3bea2d19f/python/pyspark/sql/connect/dataframe.py#L229-L240) in the `pyspark.sql.connect.dataframe.DataFrame` class, which requires a list of columns as the input argument.
I propose the following revision:
```R
sdf_read_column.spark_jobj <- function(x, column) {
  sdf <- spark_dataframe(x)
  if (inherits(sdf, "spark_pyobj")) {
    col_df <- invoke(sdf, "select", list(column))
  } else {
    col_df <- invoke(sdf, "select", column, list())
  }
  col_df <- collect(col_df)
  col_df[[column]]
}
```
