### ISSUE TITLE
src_databases(sc) has argument error when connecting to databricks

### ISSUE THREAD

**Issue by leesahanders** [sparklyr/sparklyr#3465]
I am trying to connect to a databricks cluster and trying to run the exploratory command to list databases with `src_databases(sc)`. Not sure but wanted to reach out for thoughts on what could be going on. 

Error: 
> Error: Error in py_call_impl(x, dots$unnamed, dots$named) : 
  pyspark.errors.exceptions.base.PySparkTypeError: [NOT_LIST_OF_COLUMN_OR_STR] Argument `columns` should be a list[Column].

The connection is set up using the attached databricks credentials through the Workbench extension and connecting with this (successfully): 

```r
library(tidyverse)
library(DBI)
library(dbplyr)
library(scales)

con <- dbConnect(
  odbc::databricks(),
  HTTPPath = Sys.getenv("DATABRICKS_PATH"),
  )

con
```

After connecting using this to create `sc` for specifically my cluster: 

```r
library(sparklyr)

sc <- spark_connect(
  cluster_id = "<redacted>",
  method = "databricks_connect",
  dbr_version = "14.3"
)
```

I'm able to successfully run other operations (`spark_read_table`, etc). 

Trying this command results in the above error: 
```{r}
# Doesn't work? 
src_databases(sc)
```

Error message: 
```
Error in py_call_impl(x, dots$unnamed, dots$named) : 
  pyspark.errors.exceptions.base.PySparkTypeError: [NOT_LIST_OF_COLUMN_OR_STR] Argument `columns` should be a list[Column].
Run `reticulate::py_last_error()` for details.
```

Output of `reticulate::py_last_error()`: 
```
── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/lisa.anders/.virtualenvs/r-sparklyr-databricks-14.3/lib/python3.12/site-packages/pyspark/sql/connect/dataframe.py", line 193, in select
    return DataFrame(plan.Project(self._plan, *cols), session=self._session)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lisa.anders/.virtualenvs/r-sparklyr-databricks-14.3/lib/python3.12/site-packages/pyspark/sql/connect/plan.py", line 471, in __init__
    self._verify_expressions()
  File "/home/lisa.anders/.virtualenvs/r-sparklyr-databricks-14.3/lib/python3.12/site-packages/pyspark/sql/connect/plan.py", line 477, in _verify_expressions
    raise PySparkTypeError(
pyspark.errors.exceptions.base.PySparkTypeError: [NOT_LIST_OF_COLUMN_OR_STR] Argument `columns` should be a list[Column].

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─sparklyr::src_databases(sc)
 2.   ├─sparklyr::sdf_read_column(dbs, "databaseName")
 3.   └─sparklyr:::sdf_read_column.spark_jobj(dbs, "databaseName")
 4.     ├─sparklyr::invoke(sdf, "select", column, list())
 5.     └─pysparklyr:::invoke.spark_pyobj(sdf, "select", column, list())
 6.       └─pysparklyr:::invoke_conn(...)
 7.         └─reticulate::py_call(x, ...)
 8.           └─reticulate:::py_call_impl(x, dots$unnamed, dots$named)
See `reticulate::py_last_error()$r_trace$full_call` for more details.
```

The output of  `spark_version(sc)`: 
```
[1] "3.5.0"
```

The output of `utils::sessionInfo()`: 

```
R version 4.4.0 (2024-04-24)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sparklyr_1.8.6  scales_1.3.0    dbplyr_2.5.0    DBI_1.2.3       lubridate_1.9.3 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4     purrr_1.0.2    
[10] readr_2.1.5     tidyr_1.3.1     tibble_3.2.1    ggplot2_3.5.1   tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] config_0.3.2      rappdirs_0.3.3    utf8_1.2.4        generics_0.1.3    lattice_0.22-6    stringi_1.8.4     hms_1.1.3         magrittr_2.0.3   
 [9] grid_4.4.0        timechange_0.3.0  blob_1.2.4        Matrix_1.7-0      jsonlite_1.8.8    processx_3.8.4    ps_1.7.7          httr_1.4.7       
[17] fansi_1.0.6       httr2_1.0.3       cli_3.6.3         rlang_1.1.4       bit64_4.0.5       munsell_0.5.1     yaml_2.3.9        withr_3.0.0      
[25] parallel_4.4.0    tools_4.4.0       tzdb_0.4.0        odbc_1.5.0        colorspace_2.1-0  pysparklyr_0.1.5  curl_5.2.1        reticulate_1.39.0
[33] png_0.1-8         vctrs_0.6.5       R6_2.5.1          lifecycle_1.0.4   fs_1.6.4          bit_4.0.5         pkgconfig_2.0.3   pillar_1.9.0     
[41] gtable_0.3.5      rsconnect_1.3.1   glue_1.7.0        Rcpp_1.0.12       xfun_0.45         tidyselect_1.2.1  rstudioapi_0.16.0 knitr_1.48       
[49] compiler_4.4.0    askpass_1.2.0     openssl_2.2.0  
```

**Comment by leesahanders** [comment]
Update: For anyone else these commands did work for me for exploratory analysis (thanks Edgar!) 

```r
sdf_sql(sc, "show catalogs") |> dplyr::pull()
sdf_sql(sc, "show databases") |> dplyr::pull()
```
