### ISSUE TITLE
concatenating string columns

### ISSUE THREAD

**Issue by lumatt** [sparklyr/sparklyr#813]
Hi,

I tried invoking java methods with respect to concatenating two string columns. The most obvious (at least for me) dplyr-like way for doing this is...

```r
config <- spark_config()
config[["sparklyr.shell.executor-memory"]] <- "20G"
config[["sparklyr.shell.executor-cores"]] <- "3"
config[["sparklyr.shell.total-executor-cores"]] <- "30"
config[["sparklyr.shell.driver-memory"]] <- "10G"

spark_version <- "2.0.0"

sc <- spark_connect(master = "spark://host:7077", version = spark_version, config = config)

data <- data.frame(x = c(1, 2, 3, 4), 
                   y = c("a", "b", "c", "d"), 
                   z = c("m", "n", "o", "p"))
sdf_data <- sdf_copy_to(sc, data, "data_spark")
sdf_data

# option1 - paste

concat_option1 <- sdf_data %>%
  mutate(concat_yz1 = paste0(y, z))
```
... and it works. However, I tried to do the exact same thing invoking java methods - either writing sql expressions...

```r
concat_option2 <- sdf_data %>% 
  spark_dataframe %>%
  invoke("withColumn", 
         "concat_yz2", 
         spark_session(sc) %>% 
           invoke("sql", "select concat(y, z) as concat_yz2 from data_spark") %>% 
           invoke("col", "concat_yz2")
  ) %>% 
  sdf_register
```

...or using method from org.apache.spark.sql.functions:

```r
concat_option3 <- sdf_data %>% 
  spark_dataframe %>%
  invoke("withColumn", 
         "concat_yz3", 
         invoke_static(spark_session(sc), 
                       "org.apache.spark.sql.functions", 
                       "concat", 
                       spark_session(sc) %>% invoke("sql", "select y from data_spark") %>% invoke("col", "y"),
                       spark_session(sc) %>% invoke("sql", "select z from data_spark") %>% invoke("col", "z"))
         ) %>%
  sdf_register
```

I assume it might be written more elegant (don't know what is the easiest way for extracting column class and put it as a parameter to java method), anyway both ways didn't work:

error for option 2:
```r
Error: org.apache.spark.sql.AnalysisException: resolved attribute(s) concat_yz2#264 missing from x#11,y#12,z#13 in operator !Project [x#11, y#12, z#13, concat_yz2#264 AS concat_yz2#267];
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.failAnalysis(CheckAnalysis.scala:40)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.failAnalysis(Analyzer.scala:58)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:291)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:67)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:67)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:2589)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:969)
	at org.apache.spark.sql.Dataset.withColumn(Dataset.scala:1687)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
``` 

error for option 3:
```r
Error in UseMethod("invoke_static") : 
  no applicable method for 'invoke_static' applied to an object of class "c('spark_jobj', 'shell_jobj')"
```

And one last thing: given the assumption that options 2 and 3 will give no errors, are they totally different comparing to the usage of mutate? Or mutate-itself does the similar thing (like invoking some sql-like expression to do the concatenation).

Also, might be helpful:
```r
R version 3.3.1 (2016-06-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.4 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggplot2_2.2.1    DBI_0.6-1        readr_1.1.0      withr_1.0.2      config_0.2       h2o_3.10.3.2     rsparkling_0.2.0 sparklyr_0.5.6   dplyr_0.7.0      dbplyr_1.0.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7      rstudioapi_0.6   magrittr_1.5     hms_0.3          munsell_0.4.3    colorspace_1.3-2 xtable_1.8-2     R6_2.2.0         rlang_0.1.1      plyr_1.8.4      
[11] httr_1.2.1       tools_3.3.1      parallel_3.3.1   grid_3.3.1       gtable_0.2.0     htmltools_0.3.5  lazyeval_0.2.0   yaml_2.1.14      assertthat_0.1   rprojroot_1.2   
[21] digest_0.6.12    tibble_1.3.3     shiny_1.0.3      base64enc_0.1-3  bitops_1.0-6     RCurl_1.95-4.8   glue_1.1.0       mime_0.5         scales_0.4.1     backports_1.0.5 
[31] jsonlite_1.1     httpuv_1.3.3 
```
Thanks for any tips.

**Comment by javierluraschi** [comment]
@lumatt could you explain what you are trying to accomplish? why is concatenating with `dplyr` not sufficient in this case? `dplyr` uses `invoke()` under the covers; however, would be nice to help you resolve this without the use of the extensions API.

**Comment by lumatt** [comment]
@javierluraschi the question is more about using and understanding java extensions in sparklyr. in this case dplyr-like approach is sufficient, but the whole example was mentioned just to present my understanding how to accomplish it alternatively, asking what basically went wrong .

additionally, I thought that, using typical R function (like paste0) is suboptimal, because the whole engine might collect spark dataframe to R object/objects, apply the function and then recreate original set (instead of invoking already implemented functions in spark like concat or concat_ws) - this is the approach actually used for gapply/dapply functions in sparkR (that's why I was hoping to avoid that)

**Comment by javierluraschi** [comment]
@lumatt sounds good, I was just trying to make sure that you were not writing expression without fixing first `dplyr`.

This one is easier to answer:

```
concat_option3 <- sdf_data %>% 
  spark_dataframe %>%
  invoke("withColumn", 
         "concat_yz3", 
         invoke_static(spark_session(sc), 
                       "org.apache.spark.sql.functions", 
                       "concat", 
                       spark_session(sc) %>% invoke("sql", "select y from data_spark") %>% invoke("col", "y"),
                       spark_session(sc) %>% invoke("sql", "select z from data_spark") %>% invoke("col", "z"))
         ) %>%
  sdf_register
```

The issue is that `invoke_static` only operates over `static` objects, say, objects that were not already created through `invoke()`, if you change `invoke_static(spark_session(sc)` to `invoke(spark_session(sc)` you might get the results you are looking for.
